---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: Durch ein Upgrade aller NetApp Storage-Komponenten können Sie Ihr SolidFire Element Storage-System nach der Implementierung auf dem neuesten Stand halten. 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= Übersicht der Aktualisierungssequenz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können das SolidFire Element Storage-System nach der Implementierung immer auf dem neuesten Stand halten, indem Sie alle NetApp Storage-Komponenten sequenziell aktualisieren.

Zu diesen Komponenten gehören Managementservices, NetApp Hybrid Cloud Control, Element Software, Management-Node und (je nach Installation) das Element Plug-in für vCenter Server.

[NOTE]
====
* Ab dem 2023. November können Sie kein Komponenten-Upgrade mit der Hybrid Cloud Control oder REST-API von NetApp starten, da die Signaturschlüsselzertifikate (privat und öffentlich) am 5. November 2023 abgelaufen sind. Sie können dieses Problem bis  zu Version 12.8 umgehenlink:task_hcc_upgrade_management_node.html["Durchführen eines in-Place-Upgrades des Management-Node"], bevor Sie die Managementservices, Element Software und Storage-Firmware mit der Hybrid Cloud Control oder REST-API von NetApp aktualisieren.
+
Wenn Sie einen neuen Management-Node mit Version 12.8 implementieren, können Sie die NetApp-Hybrid-Cloud-Steuerung oder die REST-API verwenden, um Komponenten-Upgrades in der Reihenfolge auszuführen<<sys_upgrade,Systemaktualisierungssequenz>>, die im aufgeführt ist.

* Die folgenden Nodes werden nicht unterstützt. Wenn Sie versuchen, einen dieser Knoten auf eine nicht unterstützte Elementversion zu aktualisieren, wird eine Fehlermeldung angezeigt, die besagt, dass der Knoten nicht von Element 12.x unterstützt wird:
+
** Ab Element 12.8, SF4805, SF9605, SF19210 und SF38410 Storage-Nodes
** Ab Element 12.7, SF2405 und SF9608 Storage-Nodes und FC-Nodes FC0025 und SF-FCN-01


* Ab Element 12.5 werden NetApp HealthTools bei Upgrades der Element Software nicht mehr unterstützt. Wenn Sie Element 11.0 oder 11.1 ausführen, müssen Sie zuerst https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Upgrade auf Element 12.3 mit HealthTools"^] Und dann upgraden Sie mithilfe von NetApp Hybrid Cloud Control auf Element 12.5 oder höher.


====
Der <<sys_upgrade,Systemaktualisierungssequenz>> Inhalt beschreibt die Aufgaben, die zum Abschluss eines Upgrades eines SolidFire All-Flash-Storage-Systems erforderlich sind. Idealerweise werden diese Verfahren als Teil der größeren Aufrüstsequenz und nicht isoliert durchgeführt. Wenn ein komponentenbasiertes Upgrade oder eine Aktualisierung erforderlich ist, lesen Sie die Verfahrensvoraussetzungen, um sicherzustellen, dass zusätzliche Komplexität bewältigt wird.

Der link:task_sf_upgrade_all_vsphere.html["VSphere-Upgrade-Sequenz"] Der Inhalt des Element Plug-ins für vCenter Server enthält zusätzliche Schritte vor und nach dem Upgrade, die zur Neuinstallation des Element Plug-ins für vCenter Server erforderlich sind.

.Bevor Sie beginnen
* Sie führen Management-Node 11.3 oder höher aus. Neuere Versionen des Management-Node verfügen über eine modulare Architektur, die individuelle Services zur Verfügung stellt.
+

TIP: Um die Version zu überprüfen, melden Sie sich bei Ihrem Management-Node an, und zeigen Sie die Versionsnummer des Elements im Anmeldebanner an. Wenn Sie keine 11.3 haben, lesen Sie link:task_hcc_upgrade_management_node.html["Upgrade Ihres Management-Node"].

* Sie haben Ihre Managementservices auf mindestens Version 2.1.326 aktualisiert.
+
Upgrades mit NetApp Hybrid Cloud Control sind in früheren Service-Bundle-Versionen nicht verfügbar.

* Sie stellen sicher, dass die Systemzeit auf allen Knoten synchronisiert ist und dass NTP für den Speicher-Cluster und die Knoten korrekt konfiguriert ist. Jeder Node muss in der Web-UI pro Node mit einem DNS-Nameserver konfiguriert sein (`https://[IP address]:442`) Ohne ungelöste Cluster Fehler im Zusammenhang mit Zeitverzerrung.
* Sie haben genügend Zeit für Ihr geplant link:task_hcc_upgrade_element_software.html#element-upgrade-time["Element Software"] Und link:task_hcc_upgrade_storage_firmware.html#storage-firmware-upgrade["Storage-Firmware"] Upgrades: Bei einem Upgrade auf Element Software 12.5 oder höher variiert die Dauer des Upgradevorgangs je nach Version der Element Software und Firmware-Updates.




== [[sys_Upgrade]]Systemaktualisierungssequenz

Mithilfe der folgenden Sequenz können Sie Ihr NetApp SolidFire All-Flash-Storage-System für Element 12.5 oder höher aktualisieren.

.Schritte
. link:task_hcc_update_management_services.html["Aktualisierung der Managementservices von Hybrid Cloud Control"].
+

IMPORTANT: Wenn Sie Managementservices auf Version 2.16 oder höher aktualisieren und einen Management-Node 11.3 bis 11.8 ausführen, müssen Sie vor der Aktualisierung der Managementservices den RAM der Management-Node-VM erhöhen.

+

IMPORTANT: Vor einem Upgrade der Element Software müssen Sie das neueste Management-Services-Bundle aktualisieren.

. link:task_hcc_upgrade_element_prechecks.html["Integritätsprüfungen von Element Storage vor einem Storage Upgrade durchführen"].
. link:task_hcc_upgrade_element_software.html["Aktualisieren Sie die Element Software und die Storage-Firmware"].
. link:task_hcc_upgrade_storage_firmware.html["(Optional) Aktualisieren Sie nur die Element Storage-Firmware"].
+

NOTE: Möglicherweise führen Sie diese Aufgabe aus, wenn außerhalb einer Hauptversion ein neues Speicher-Firmware-Upgrade verfügbar wird.

. link:task_hcc_upgrade_management_node.html["(Optional) Upgrade Ihres Management-Node"].
+

NOTE: Zum Upgrade der Element Software auf dem Storage-Cluster ist kein Upgrade des Betriebssystems des Management-Node mehr erforderlich. Wenn der Management-Node Version 11.3 oder höher ist, können die Managementservices einfach auf die neueste Version aktualisiert werden, um Element-Upgrades mithilfe von NetApp Hybrid Cloud Control durchzuführen. Befolgen Sie für Ihr Szenario die Vorgehensweise zum Upgrade des Management-Node, wenn Sie aus anderen Gründen, wie z. B. Sicherheitsbehebungsmaßnahmen, ein Upgrade des Betriebssystems des Management-Node durchführen möchten.

. link:task_vcp_upgrade_plugin.html["Aktualisieren Sie Ihr Element Plug-in für vCenter Server"].


[discrete]
== Weitere Informationen

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"]

