---
sidebar: sidebar 
permalink: mnode/task_mnode_enable_activeIQ.html 
summary: 'Sie können den Management-Node (mNode) verwenden, um Active IQ für SolidFire All-Flash-Storage zu aktivieren.' 
keywords: netapp, Element, api, enable, active iq, activeiq 
---
= Monitoring von Active IQ und NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die Active IQ Storage-Überwachung aktivieren, wenn Sie dies bei der Installation oder einem Upgrade nicht bereits getan haben. Möglicherweise müssen Sie dieses Verfahren anwenden, wenn Sie SolidFire Active IQ nicht während der Installation für ein SolidFire All-Flash-Storage-System eingerichtet haben.

Der Active IQ Collector Service leitet Konfigurationsdaten und softwarebasierte Element Cluster-Performance-Metriken an SolidFire Active IQ weiter, um historische Berichte zu erstellen und Performance-Monitoring nahezu in Echtzeit zu überwachen. Der NetApp Monitoring Service ermöglicht die Weiterleitung von Storage-Cluster-Fehlern an vCenter zur Alarmbenachrichtigung.

.Bevor Sie beginnen
* Einige Funktionen in Active IQ, beispielsweise Quality of Service (QoS), erfordern Element 11.3 oder höher die ordnungsgemäße Funktion. Um sicherzustellen, dass Sie alle Active IQ-Funktionen nutzen können, empfiehlt NetApp Folgendes:
+
** Im Storage Cluster wird die NetApp Element Software 11.3 oder höher ausgeführt.
** Sie haben einen Management-Node mit Version 11.3 oder höher implementiert.


* Sie haben Internetzugang. Der Active IQ Collector Service kann nicht von dunklen Standorten verwendet werden, die keine externe Verbindung haben.


.Schritte
. Holen Sie sich die Basis-Asset-ID für die Installation:
+
.. Öffnen Sie die REST API-UI für den Bestandsdienst auf dem Managementknoten:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Wählen Sie *autorisieren* aus, und füllen Sie Folgendes aus:
+
... Geben Sie den Benutzernamen und das Passwort für den Cluster ein.
... Geben Sie die Client-ID als ein `mnode-client`.
... Wählen Sie *autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Fenster.


.. Wählen Sie in DER REST API UI *GET ​/Installations* aus.
.. Wählen Sie *Probieren Sie es aus*.
.. Wählen Sie *Ausführen*.
.. Kopieren Sie aus dem Text Code 200 Antwort den `id` Für die Installation.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: Die Installation verfügt über eine Basiskonfiguration, die während der Installation oder eines Upgrades erstellt wurde.



. Telemetrie aktivieren:
+
.. Rufen Sie die mNode-Service-API-UI auf dem Management-Node auf, indem Sie die Management-Node-IP-Adresse, gefolgt von eingeben `/mnode`:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. Wählen Sie *autorisieren* oder ein Schloss-Symbol aus, und füllen Sie Folgendes aus:
+
... Geben Sie den Benutzernamen und das Passwort für den Cluster ein.
... Geben Sie die Client-ID als ein `mnode-client`.
... Wählen Sie *autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Fenster.


.. Konfigurieren der BasisinAssets:
+
... Wählen Sie *PUT /Assets/{Asset_id}* aus.
... Wählen Sie *Probieren Sie es aus*.
... Geben Sie die folgende in die JSON-Nutzlast ein:
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... Geben Sie die Basis-ID des vorherigen Schritts in *Asset_ID* ein.
... Wählen Sie *Ausführen*.
+
Der Active IQ Service wird automatisch neu gestartet, sobald die Assets geändert werden. Das Ändern von Anlagen führt zu einer kurzen Verzögerung, bevor Einstellungen angewendet werden.





. Falls noch nicht geschehen, fügen Sie dem Management-Node bekannte Ressourcen eine vCenter Controller Ressource für NetApp Hybrid Cloud Control hinzu:
+

NOTE: Für NetApp Monitoring Services ist ein Controller-Asset erforderlich.

+
.. Wählen Sie *POST /Assets/{Asset_id}/Controllers* aus, um eine Unterressource des Controllers hinzuzufügen.
.. Wählen Sie *Probieren Sie es aus*.
.. Geben Sie im Feld *Asset_id* die ID der übergeordneten Basis ein, die Sie in die Zwischenablage kopiert haben.
.. Geben Sie die erforderlichen Nutzlastwerte mit ein `type` Als `vCenter` Und vCenter Zugangsdaten.
+
[listing]
----
{
"username": "string",
"password": "string",
"ip": "string",
"type": "vCenter",
"host_name": "string",
"config": {}
}
----
+

NOTE: `ip` Ist die vCenter IP-Adresse.

.. Wählen Sie *Ausführen*.




[discrete]
== Weitere Informationen

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Seite „SolidFire und Element Ressourcen“"^]

