---
sidebar: sidebar 
permalink: mnode/task_mnode_work_overview_UI.html 
summary: Mit der Management-Node-UI , Sie können Änderungen an Netzwerk- und Cluster-Einstellungen vornehmen, Systemtests ausführen oder Systemdienstprogramme verwenden. 
keywords: 'netapp, management node ui, mnode ui, :442, Element' 
---
= Übersicht über die Management-Node-UI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mit der Management-Node-UI (`https://<ManagementNodeIP>:442`) Können Sie Änderungen an Netzwerk- und Clustereinstellungen vornehmen, Systemtests ausführen oder Systemdienstprogramme verwenden.

Aufgaben, die Sie mit der Management-Node-UI durchführen können:

* link:task_mnode_enable_alerts.html["Konfigurieren der Meldungsüberwachung"]
* link:task_mnode_settings.html["Ändern und Testen der Netzwerk-, Cluster- und Systemeinstellungen des Management-Node"]
* link:task_mnode_run_system_utilities.html["Führen Sie Systemdienstprogramme vom Management-Node aus"]


[discrete]
== Weitere Informationen

* link:task_mnode_access_ui.html["Greifen Sie auf den Management-Node zu"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Seite „SolidFire und Element Ressourcen“"^]

