= Weitere Informationen
:allow-uri-read: 


Sie können mithilfe der NetApp Element API das Standard-SSL-Zertifikat und den privaten Schlüssel des Storage-Node im Cluster ändern.

Beim Erstellen eines NetApp Element-Software-Clusters erstellt das Cluster ein einzigartiges SSL-Zertifikat (Secure Sockets Layer) mit einem privaten Schlüssel, das für die gesamte HTTPS-Kommunikation über die Element-UI, die UI pro Node oder die APIs verwendet wird. Die Element Software unterstützt selbstsignierte Zertifikate sowie Zertifikate, die von einer vertrauenswürdigen Zertifizierungsstelle (CA) ausgestellt und verifiziert werden.

Sie können die folgenden API-Methoden verwenden, um mehr Informationen über das Standard-SSL-Zertifikat zu erhalten und Änderungen vorzunehmen.

* *GetSSLZertifikat*
+
Sie können das verwenden link:../api/reference_element_api_getsslcertificate.html["GetSSLCertificate-Methode"] So rufen Sie Informationen zum derzeit installierten SSL-Zertifikat ab, einschließlich aller Zertifikatdetails.

* *SetSSLZertifikat*
+
Sie können das verwenden link:../api/reference_element_api_setsslcertificate.html["SetSSLCertificate-Methode"] Zum Festlegen der Cluster- und Node-SSL-Zertifikate auf das von Ihnen zur Verfügung gestellt Zertifikat und den privaten Schlüssel. Das System überprüft das Zertifikat und den privaten Schlüssel, um zu verhindern, dass ein ungültiges Zertifikat angewendet wird.

* *RemoveSSLZertifikat*
+
Der link:../api/reference_element_api_removesslcertificate.html["RemoveSSLCertificate-Methode"] Entfernt das derzeit installierte SSL-Zertifikat und den privaten Schlüssel. Das Cluster generiert dann ein neues selbstsigniertes Zertifikat und einen privaten Schlüssel.




NOTE: Das Cluster-SSL-Zertifikat wird automatisch auf alle neuen Nodes angewendet, die dem Cluster hinzugefügt wurden. Jeder Node, der aus dem Cluster entfernt wurde, wird auf ein selbstsigniertes Zertifikat zurückgesetzt und alle benutzerdefinierten Zertifikate und Schlüsselinformationen werden vom Node entfernt.



== Weitere Informationen

* link:../mnode/reference_change_mnode_default_ssl_certificate.html["Ändern Sie das Standard-SSL-Zertifikat für den Management-Node"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_are_the_requirements_around_setting_custom_SSL_certificates_in_Element_Software%3F["Welche Anforderungen gelten für das Festlegen benutzerdefinierter SSL-Zertifikate in der Element Software?"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Seite „SolidFire und Element Ressourcen“"^]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

