---
permalink: concepts/concept_rn_whats_new_element.html 
sidebar: sidebar 
keywords: netapp, solidfire, element, storage, solidfire enterprise sds 
summary: NetApp aktualisiert regelmäßig SolidFire und Element Software, um Ihnen neue Funktionen, Verbesserungen und Fehlerkorrekturen zu bieten. 
---
= Was ist neu in Element Software 12.5 und später
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Element_Software_-_Apache_Log4j_Vulnerability_-_Workaround
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp aktualisiert regelmäßig SolidFire und Element Software, um Ihnen neue Funktionen, Verbesserungen und Fehlerkorrekturen zu bieten. Element 12.7 ist die neueste Version und beinhaltet Sicherheits- und Systemkomponenten-Updates, Verbesserungen der Betriebsabläufe sowie behobene Probleme.


NOTE: Die kumulativen Software- und Firmware-Updates werden im Rahmen eines Upgrades von Element 12.7 auf Basis der aktuellen Element-Version installiert, die auf einem Storage-Cluster ausgeführt wird. Wenn beispielsweise aktuell in einem Cluster Element 12.3.x ausgeführt wird, können Sie ein Upgrade direkt auf Element 12.7 durchführen, um die kumulativen Updates von Element 12.5 und 12.7 zu erhalten. Weitere Informationen zu unterstützten Upgrade-Pfaden finden Sie unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software["KB-Artikel"^]



== Element 12.7

Informieren Sie sich über die Neuerungen in Element 12.7.



=== Sichere CHAP-Algorithmen

Element 12.7 bietet Unterstützung für sichere FIPS-konforme CHAP-Algorithmen (Challenge-Handshake Authentication Protocol) SHA1, SHA-256 und SHA3-256. link:../storage/task_data_manage_accounts_work_with_accounts_task.html["Weitere Informationen ."].



=== Dynamische Blocksynchronisation (bin)

Cluster-Vorgänge wie Ergänzungen, Upgrades oder Wartungen von Nodes oder das Hinzufügen von Laufwerken usw. lösen Block-Sync (bin) aus, um Block-Daten an die neuen oder aktualisierten Nodes in einem Cluster-Layout zu verteilen. Die Verwendung einer einzigen, langsamen Geschwindigkeit als Standard-Synchronisationsrate führt dazu, dass diese Vorgänge viel Zeit in Anspruch nehmen, und nutzt nicht die höhere Verarbeitungsleistung größerer Nodes. Ab Element 12.7 wird die Sync-in-Rate basierend auf der Anzahl der Kerne im Storage-Node dynamisch optimiert, sodass diese Vorgänge deutlich schneller ablaufen.

Wenn Sie beispielsweise großen 28-Core Storage-Nodes (H610S, SF19210 und SF38410) mit Element 12.7 zu einem vorhandenen Cluster hinzufügen, wird die Synchronisationsrate für Daten automatisch auf 110 MB/s anstatt 60 Mbps eingestellt. Wenn Sie diese großen Storage-Nodes zusätzlich aus dem Wartungsmodus für den Node-Wartungsmodus bringen, beispielsweise bei einem Upgrade von Element 12.3.x oder höher zu Element 12.7 mit NetApp Hybrid Cloud Control, wird die Sync-in-Rate für geänderte Block-Datenraten automatisch auf 110 MB anstatt 20 MB/s eingestellt.

Wenn Sie einem Element 12.7 Cluster die mittleren 16-Core Storage-Nodes (H410S) und kleinen 12-Core Storage-Nodes (SF4805) hinzufügen, bleibt die Synchronisationsrate für Daten mit 60 MB/s; Wenn geänderte Blöcke jedoch synchronisiert werden, wenn Sie sie während einer Aktualisierung von Element 12.3.x zu Element 12.7 aus dem Wartungsmodus des Node verlassen, wird die Sync-in-Rate für mittelgroße Storage-Nodes automatisch von 20 Mbit/s bis 60 Mbit/s und für kleinere Storage Nodes mit 40 Mbit/s synchronisiert.

Wenn Sie Storage-Nodes entfernen, wird die Synchronisationsrate des Blocks nicht beeinträchtigt, sodass Performance-Beeinträchtigungen für Client-I/O vermieden werden



=== Verbesserung der Speicherbereinigung

Bei Clustern mit größeren Storage-Nodes beispielsweise führt ein H610S-4 mit einem belegten Speicherplatz von 1 PB sehr hohe Workloads mit Überschreibungen aus, Dank hoher Deduplizierung und Komprimierung kann der Speicherbereinigung jetzt mithalten, da die standardmäßige Bloom-Filtergröße für die größeren Nodes von 700 GB oder mehr Speicher auf 1048576 Bit erhöht wurde. Diese Änderung wird automatisch wirksam, wenn Sie Ihre Storage-Nodes auf Element 12.7 aktualisieren. Es hat keine Auswirkungen auf kleinere Nodes.



=== Verbesserung der Skalierbarkeit

Bei Element 12.7 sind keine spezifischen Sequenzen mehr nötig, wenn einem vorhandenen Cluster mehrere Storage-Nodes mit Block- und Metadatenlaufwerken hinzugefügt werden müssen. Über die Element UI oder API können Sie einfach alle verfügbaren Laufwerke auswählen und dann alle Massenvorgänge gleichzeitig hinzufügen. Element 12.7 verwaltet die Datensynchronisierung automatisch, sodass alle Block-Services gleichzeitig synchronisiert werden. Wenn die Block-Services für jeden Node die Synchronisierung abgeschlossen haben, kann das Metadatenlaufwerk dieses Node den Host-Volumes zugewiesen werden. Diese Verbesserung durch Skalierung reduziert deutlich die Latenz bei der Lesereaktionszeit und verhindert eine Verschlechterung der Performance, während Daten zwischen neu hinzugefügten Storage-Nodes synchronisiert werden.



=== Updates der Storage Node-Firmware

Element 12.7 enthält das Storage-Firmware-Bundle Version 2.164.0, das auch die Unterstützung neuer Systemkomponenten bietet. link:https://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.164.0.html["Weitere Informationen ."].


NOTE: In Element 12.7 sind keine neuen Firmware-Updates vorhanden. Basierend auf dem aktuellen Firmware-Bundle, das auf den Storage-Nodes ausgeführt wird, werden jedoch die kumulativen Updates beim Upgrade auf Element 12.7 installiert.



=== SolidFire Active IQ-Dokumentation

In der SolidFire Active IQ-Benutzeroberfläche können Sie jetzt auf der Seite QoS-Management navigieren, um Empfehlungen und Informationen zur Knotendrosselung für das Cluster anzuzeigen. Darüber hinaus wird auf dem Cluster-Dashboard jetzt die Gesamtanzahl der Snapshots angezeigt. Weitere aktuelle Verbesserungen sind das Hinzufügen primärer und sekundärer Node-Informationen für aktive Volumes und des durchschnittlichen Durchsatzes, der IOPS-Werte und der durchschnittlichen Latenz der letzten 30 Minuten auf primären Volumes auf einem Node.

Sie haben jetzt über die Dokumentation der Element Software Zugriff auf die SolidFire Active IQ Dokumentation. link:https://docs.netapp.com/us-en/element-software/monitor-storage-active-iq.html["Weitere Informationen ."].



=== NetApp Bugs Online enthält gelöste und bekannte Probleme

Gelöste und bekannte Probleme sind im NetApp Bugs Online-Tool aufgeführt. Sie können diese Themen für Element Software und andere Produkte hier durchsuchen https://mysupport.netapp.com/site/products/all/details/element-software/bugsonline-tab["NetApp Bugs Online"^].



== Element 12.5

Element 12.5 bietet einen verbesserten Zugriff auf Storage-Nodes, eine erweiterte Managementfunktionen für benutzerdefinierte Protection-Domänen, neue und verbesserte Cluster-Fehler und -Ereignisse, eine verbesserte Funktionalität der Create Cluster UI, verbesserte Sicherheit und automatisierte Upgrades mit Ansible.



=== Verbesserter Zugriff auf Storage-Nodes

Element 12.5 bietet mithilfe signierter SSH-Zertifikate einen verbesserten Remote-Zugriff auf einzelne Knoten. Für sicheren Remote-Zugriff auf Storage-Nodes wird ein neues lokales Benutzerkonto mit beschränkter Berechtigung aufgerufen `sfreadonly` Wird jetzt während RTFI eines Speicherknotens erstellt. Der `sfreadonly` Account ermöglicht den Zugriff auf das Backend des Storage-Nodes zu grundlegenden Wartungs- oder Fehlerbehebungszwecken. Sie können nun die konfigurieren `supportAdmin` Zugriffstyp für Cluster-Administratorbenutzer, damit der NetApp Support nach Bedarf auf das Cluster zugreifen kann



=== Verbessertes Management individueller Sicherungsdomänen

Element 12.5 verfügt über eine neue Benutzeroberfläche, mit der Sie vorhandene benutzerdefinierte Schutz-Domains schnell und einfach anzeigen und neue benutzerdefinierte Schutz-Domains konfigurieren können.



=== Neue und verbesserte Fehler, Ereignisse und Warnmeldungen im Cluster

Element 12.5 verbessert die Fehlerbehebung im System durch die Einführung der neuen Cluster-Fehlercodes `BmcSelfTestFailed` Und `CpuThermalEventThreshold`. Element 12.5 enthält auch Verbesserungen der Robustheit bei vorhandenen Cluster-Ereignissen und Warnungen, z. B. `nodeOffline`, `volumeOffline`, `driveHealthFault`, `networkEvent`, und	`cSumEvent`.



=== Aktivieren Sie die Softwareverschlüsselung im Ruhezustand über die Benutzeroberfläche Cluster erstellen

Durch Hinzufügen eines neuen Kontrollkästchens in der Benutzeroberfläche „Cluster erstellen“ bietet Element 12.5 die Möglichkeit, während der Cluster-Erstellung Cluster-übergreifende Softwareverschlüsselung für SolidFire All-Flash-Storage-Cluster zu aktivieren.



=== Updates der Storage Node-Firmware

Element 12.5 umfasst Firmware-Updates für Storage-Nodes. link:../concepts/concept_rn_relatedrn_element.html#storage-firmware["Weitere Informationen ."].



=== Erhöhte Sicherheit

Element 12.5 enthält die Minderung, die das Risiko der Element Software gegenüber der Apache Log4j-Sicherheitsanfälligkeit schließt. NetApp SolidFire Storage-Cluster mit aktivierter Funktion Virtual Volumes (VVols) sind der Apache Log4j Sicherheitsanfälligkeit ausgesetzt. Informationen zum Workaround für die Sicherheitsanfälligkeit von Apache Log4j in der NetApp Element-Software finden Sie im {url-Peak}[KB-Artikel^].

Wenn Sie Element 11.x, 12.0 oder 12.2 verwenden oder sich Ihr Storage-Cluster bereits bei Element 12.3 oder 12.3.1 befindet und die VVols-Funktion aktiviert ist, sollten Sie ein Upgrade auf 12.5 durchführen.

Element 12.5 umfasst außerdem mehr als 120 CVE-Sicherheitsvorkehrungen.



=== Automatisierte Upgrades mit Ansible

Bei Element 12.5 lässt sich der Workflow für Element Software-Upgrades mithilfe von Ansible automatisieren, um ein Rolling Upgrade des gesamten Storage-Clusters durchzuführen. Navigieren Sie zum, um zu beginnen https://github.com/NetApp-Automation["NetApp Ansible Repository"^] Auf GitHub und laden Sie die herunter `nar_solidfire_sds_upgrade` Rolle und Dokumentation:

[discrete]
== Weitere Informationen

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["Versionshinweise zu NetApp Hybrid Cloud Control and Management Services"^]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"]
* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire und Element Software Dokumentationszentrum für frühere Versionen"^]
* https://www.netapp.com/us/documentation/hci.aspx["Ressourcen-Seite zu NetApp HCI"^]
* link:../hardware/fw_storage_nodes.html["Unterstützte Storage-Firmware-Versionen für SolidFire Storage-Nodes"]

