---
permalink: concepts/concept_intro_management_node.html 
sidebar: sidebar 
keywords: what is, element mnode, management node, mnode 
summary: 'Der Management-Node \(mNode\) ist eine virtuelle Maschine, die parallel zu einem oder mehreren auf Element basierenden Storage-Clustern ausgeführt wird. Er dient als Upgrade und zur Bereitstellung von Systemservices wie Monitoring und Telemetrie, zum Management von Cluster-Ressourcen und -Einstellungen, zur Ausführung von Systemtests und Dienstprogrammen und zur Aktivierung des NetApp Support-Zugriffs zur Fehlerbehebung.' 
---
= Management-Node für Element Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der link:../mnode/task_mnode_work_overview.html["Management-Node (mNode)"] Ist eine Virtual Machine, die mit einem oder mehreren auf Element basierenden Storage-Clustern parallel ausgeführt wird. Er dient als Upgrade und zur Bereitstellung von Systemservices wie Monitoring und Telemetrie, zum Management von Cluster-Ressourcen und -Einstellungen, zur Ausführung von Systemtests und Dienstprogrammen und zur Aktivierung des NetApp Support-Zugriffs zur Fehlerbehebung.

Der Management-Node interagiert mit einem Storage-Cluster, um Managementaktionen auszuführen, ist jedoch nicht Mitglied des Storage-Clusters. Managementknoten erfassen regelmäßig über API-Aufrufe Informationen über das Cluster und melden diese Informationen zur Remote-Überwachung an Active IQ (sofern aktiviert). Management-Nodes sind auch für die Koordinierung von Software-Upgrades der Cluster-Nodes verantwortlich.

Ab Element 11.3 fungiert der Management Node als Microservice-Host, wodurch sich ausgewählte Softwareservices schneller außerhalb der Hauptversionen aktualisieren lassen. Diese Microservices oder link:../concepts/concept_intro_management_services_for_afa.html["Management Services"] Werden häufig als Service-Bundles aktualisiert.
