---
permalink: concepts/reference_solidfire_element_ug_where_to_find_additional_information.html 
sidebar: sidebar 
keywords:  
summary: Weitere Informationen zu Aufgaben im Zusammenhang mit dem SolidFire Storage-System erhalten Sie im NetApp SolidFire Documentation Center und von den Ressourcen von NetApp SolidFire auf der Seite. 
---
= Wo Sie weitere Informationen finden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weitere Informationen zu Aufgaben im Zusammenhang mit dem SolidFire Storage-System erhalten Sie im NetApp SolidFire Documentation Center und von den Ressourcen von NetApp SolidFire auf der Seite.

Im Documentation Center finden Sie zudem Informationen zur Hardwareinstallation und -Wartung, zusätzliche Inhaltsressourcen verfügbar, Links zu bekannten Problemen und behobenen Problemen sowie die neuesten Versionshinweise.

* *NetApp SolidFire Ressourcen Seite*
+
Enthält Ressourcen zur Element Software, einschließlich Links zu Videoinhalten und technischen Berichten

+
https://www.netapp.com/us/documentation/solidfire.aspx["SolidFire All-Flash-Storage-Ressourcen"]

* *NetApp SolidFire Documentation Center*
+
Bietet Informationen zur Installation und Wartung der Hardware, zusätzliche verfügbare Content-Ressourcen, Links zu bekannten Problemen und behobenen Problemen sowie die neuesten Versionshinweise.

+
https://docs.netapp.com/sfe-113/index.jsp["SolidFire und Element 11.3 Documentation Center"]

* *https://kb.netapp.com/app/answers/answer_view/a_id/1000941/loc/en_US[NetApp SolidFire Element Bekannte Probleme]*
+
Zeigt bekannte Probleme in aktuellen und früheren Versionen der Element Software an.

* *https://kb.netapp.com/app/answers/answer_view/a_id/1000933[NetApp SolidFire Element hat Probleme gelöst]*
+
Zeigt eine Liste der behobenen Probleme in den aktuellen und früheren Versionen der Element Software an.


