---
permalink: storage/concept_data_manage_vol_access_group_work_with_volume_access_groups_and_initiators.html 
sidebar: sidebar 
keywords: volume access groups, initiators, working with, chap, fc, iscsi 
summary: ISCSI-Initiatoren oder Fibre Channel-Initiatoren können auf die in den Volume-Zugriffsgruppen definierten Volumes zugreifen. 
---
= Arbeiten Sie mit Volume-Zugriffsgruppen und -Initiatoren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ISCSI-Initiatoren oder Fibre Channel-Initiatoren können auf die in den Volume-Zugriffsgruppen definierten Volumes zugreifen.

Sie können Zugriffsgruppen erstellen, indem Sie iSCSI-Initiator-IQNs oder Fibre Channel-WWPNs in einer Sammlung von Volumes zuordnen. Jeder IQN, den Sie einer Zugriffsgruppe hinzufügen, kann auf jedes Volume in der Gruppe zugreifen, ohne dass eine CHAP-Authentifizierung erforderlich ist.

Es gibt zwei Arten von CHAP-Authentifizierungsmethoden:

* CHAP-Authentifizierung auf Kontoebene: Sie können CHAP-Authentifizierung für das Konto zuweisen.
* CHAP-Authentifizierung auf Initiatorebene: Sie können bestimmten Initiatoren eindeutige CHAP-Ziele und Schlüssel zuweisen, ohne an ein einziges CHAP-Konto gebunden zu sein. Diese CHAP-Authentifizierung auf Initiatorebene ersetzt Anmeldeinformationen auf Kontoebene.


Optional können Sie mit CHAP pro Initiator die Initiatorautorisierung und die CHAP-Authentifizierung per Initiator erzwingen. Diese Optionen können pro Initiator definiert werden, und eine Zugriffsgruppe kann eine Kombination von Initiatoren mit verschiedenen Optionen enthalten.

Jeder WWPN, den Sie einer Zugriffsgruppe hinzufügen, ermöglicht den Fibre-Channel-Netzwerkzugriff auf die Volumes in der Zugriffsgruppe.


NOTE: Volume-Zugriffsgruppen verfügen über die folgenden Grenzen:

* In einer Zugriffsgruppe sind maximal 64 IQNs oder WWPNs zulässig.
* Eine Zugriffsgruppe kann aus maximal 2000 Volumes bestehen.
* Ein IQN oder WWPN kann nur zu einer Zugriffsgruppe gehören.
* Ein einzelnes Volume kann zu maximal vier Zugriffsgruppen gehören.




== Weitere Informationen

* xref:task_data_manage_vol_access_group_create_a_volume_access_group.adoc[Erstellen einer Volume-Zugriffsgruppe]
* xref:task_data_manage_vol_access_group_add_volumes.adoc[Fügen Sie einer Zugriffsgruppe Volumes hinzu]
* xref:task_data_manage_vol_access_group_remove_volumes.adoc[Volumes aus einer Zugriffsgruppe entfernen]
* xref:task_data_manage_vol_access_group_create_an_initiator.adoc[Erstellen eines Initiators]
* xref:task_data_manage_vol_access_group_edit_an_initiator.adoc[Bearbeiten Sie einen Initiator]
* xref:task_data_manage_vol_access_group_add_a_single_initiator.adoc[Fügen Sie einen einzelnen Initiator einer Volume-Zugriffsgruppe hinzu]
* xref:task_data_manage_vol_access_group_add_multiple_initiators.adoc[Fügen Sie einer Volume-Zugriffsgruppe mehrere Initiatoren hinzu]
* xref:task_data_manage_vol_access_group_remove_initiators_from_an_access_group.adoc[Entfernen Sie Initiatoren aus einer Zugriffsgruppe]
* xref:task_data_manage_vol_access_group_delete.adoc[Löschen Sie eine Zugriffsgruppe]
* xref:task_data_manage_vol_access_group_delete_an_initiator.adoc[Löschen eines Initiators]

