---
permalink: storage/concept_data_protection_volume_snapshot_backup_operations.html 
sidebar: sidebar 
keywords: volume snapshot, backup operations, back up volume snapshot, cluster, object store 
summary: Sie können die integrierte Backup-Funktion verwenden, um einen Volume-Snapshot zu sichern. Sie können ein Backup von Snapshots aus einem SolidFire Cluster auf einem externen Objektspeicher oder auf einem anderen SolidFire Cluster erstellen. Wenn Sie einen Snapshot in einem externen Objektspeicher sichern, müssen Sie über eine Verbindung zum Objektspeicher verfügen, der Lese-/Schreibvorgänge ermöglicht. 
---
= Sichern Sie einen Volume-Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die integrierte Backup-Funktion verwenden, um einen Volume-Snapshot zu sichern. Sie können ein Backup von Snapshots aus einem SolidFire Cluster auf einem externen Objektspeicher oder auf einem anderen SolidFire Cluster erstellen. Wenn Sie einen Snapshot in einem externen Objektspeicher sichern, müssen Sie über eine Verbindung zum Objektspeicher verfügen, der Lese-/Schreibvorgänge ermöglicht.

* link:task_data_protection_back_up_a_volume_snapshot_to_an_amazon_s3_object_store["Sichern Sie einen Volume Snapshot in einem Amazon S3-Objektspeicher"]
* link:task_data_protection_back_up_a_volume_snapshot_to_openstack_swift["Sichern Sie einen Volume Snapshot in einem OpenStack Swift Objektspeicher"]
* link:task_data_protection_back_up_volume_to_solidfire["Sichern Sie einen Volume Snapshot auf einem SolidFire Cluster"]

