---
permalink: storage/concept_system_manage_key_get_started_with_external_key_management.html 
sidebar: sidebar 
keywords: kmip, master key, key management, encryption at rest, software encryption at rest, ekm, ak, eks, seds 
summary: 'Externes Verschlüsselungsmanagement \(EKM\) bietet sichere Authentifizierungsschlüssel \(AK\)-Verwaltung in Verbindung mit einem externen Server \(EKS\) aus dem Cluster. Die AKS werden zum Sperren und Entsperren von Self-Encrypting Drives (SEDs) verwendet, wenn die Verschlüsselung im Ruhezustand auf dem Cluster aktiviert ist.' 
---
= Erste Schritte mit externem Verschlüsselungsmanagement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EKM (External Key Management) bietet eine sichere Verwaltung des Authentifizierungsschlüssels (AK) in Verbindung mit einem externen EKS-Server (Off-Cluster). Die AKS werden verwendet, um Self-Encrypting Drives (SEDs) zu sperren und zu entsperren link:../concepts/concept_solidfire_concepts_security.html["Verschlüsselung für Daten im Ruhezustand"] Ist auf dem Cluster aktiviert. Der EKS sorgt für die sichere Erzeugung und Lagerung der AKS. Der Cluster verwendet für die Kommunikation mit dem EKS das Key Management Interoperability Protocol (KMIP), ein OASIS-definiertes Standardprotokoll.

* link:task_system_manage_key_set_up_external_key_management.html["Externe Verwaltung einrichten"]
* link:task_system_manage_rekey_software_ear_master_key.html["Verschlüsselung der Software beim Rest-Master-Schlüssel"]
* link:concept_system_manage_key_recover_inaccessible_or_invalid_authentication_keys["Wiederherstellen von nicht zugänglichen oder ungültigen Authentifizierungsschlüsseln"]
* link:concept_system_manage_key_external_key_management_api_commands.html["Befehle für externes Verschlüsselungsmanagement-API"]


[discrete]
== Weitere Informationen

* link:../api/reference_element_api_createcluster.html["CreateCluster API, die zur Aktivierung der Softwareverschlüsselung im Ruhezustand verwendet werden kann"]
* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen von NetApp SolidFire und Element Produkten"^]

