---
permalink: storage/concept_system_manage_mfa_additional_information_for_multi_factor_authentication.html 
sidebar: sidebar 
keywords: mfa, idp, certificates, api method 
summary: Beachten Sie die folgenden Einschränkungen bei der Multi-Faktor-Authentifizierung. 
---
= Zusätzliche Informationen für Multi-Faktor-Authentifizierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beachten Sie die folgenden Einschränkungen bei der Multi-Faktor-Authentifizierung.

* Um nicht mehr gültige IdP-Zertifikate zu aktualisieren, müssen Sie einen nicht-IdP-Admin-Benutzer verwenden, um die folgende API-Methode aufrufen zu können: `UpdateIdpConfiguration`
* MFA ist nicht kompatibel mit Zertifikaten, die weniger als 2048 Bit lang sind. Standardmäßig wird auf dem Cluster ein 2048-Bit-SSL-Zertifikat erstellt. Sie sollten beim Aufruf der API-Methode vermeiden, ein kleineres Zertifikat einzurichten: `SetSSLCertificate`
+

NOTE: Wenn das Cluster ein Zertifikat verwendet, das vor dem Upgrade weniger als 2048-Bit enthält, muss das Cluster-Zertifikat nach dem Upgrade auf Element 12.0 oder höher mit einem Zertifikat von mindestens 2048 Bit aktualisiert werden.

* IDP Admin-Benutzer können nicht dazu verwendet werden, API-Aufrufe direkt (beispielsweise über SDKs oder Postman) zu tätigen oder andere Integrationen (z. B. OpenStack Cinder oder vCenter Plug-in) zu verwenden. Fügen Sie entweder LDAP-Cluster-Administratorbenutzer oder lokale Cluster-Admin-Benutzer hinzu, wenn Sie Benutzer mit diesen Fähigkeiten erstellen müssen.




== Weitere Informationen

* link:../api/index.html["Storage-Management mit der Element API"]
* https://www.netapp.com/data-storage/solidfire/documentation["Seite „SolidFire und Element Ressourcen“"^]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

