---
permalink: storage/concept_system_manage_virtual_manage_virtual_networks.html 
sidebar: sidebar 
keywords: virtual networks, manage, traffic, clients, vlan tagging 
summary: Durch das virtuelle Netzwerk im SolidFire Storage kann der Datenverkehr zwischen mehreren Clients, die sich in separaten logischen Netzwerken befinden, mit einem Cluster verbunden werden. Die Verbindungen zum Cluster werden im Netzwerk-Stack durch VLAN-Tagging getrennt. 
---
= Managen Sie virtuelle Netzwerke
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch das virtuelle Netzwerk im SolidFire Storage kann der Datenverkehr zwischen mehreren Clients, die sich in separaten logischen Netzwerken befinden, mit einem Cluster verbunden werden. Die Verbindungen zum Cluster werden im Netzwerk-Stack durch VLAN-Tagging getrennt.



== Weitere Informationen

* xref:task_system_manage_virtual_add_a_virtual_network.adoc[Fügen Sie ein virtuelles Netzwerk hinzu]
* xref:task_system_manage_virtual_enable_virtual_routing_and_forwarding.adoc[Aktivieren Sie virtuelles Routing und Forwarding]
* xref:task_system_manage_virtual_edit_a_virtual_network.adoc[Bearbeiten eines virtuellen Netzwerks]
* xref:task_system_manage_virtual_edit_vrf_vlans.adoc[VRF-VLANs bearbeiten]
* xref:task_system_manage_virtual_delete_a_virtual_network.adoc[Löschen Sie ein virtuelles Netzwerk]

