---
permalink: storage/concept_data_manage_data_management.html 
sidebar: sidebar 
keywords: virtual volumes, volumes, manage 
summary: 'Sie können die Daten in einem Cluster verwalten, auf dem die Element Software ausgeführt wird, auf der Registerkarte Management in der Element UI. Verfügbare Cluster-Managementfunktionen umfassen die Erstellung und das Management von Daten-Volumes, Benutzerkonten, Volume-Zugriffsgruppen, Initiatoren und Quality of Service \(QoS\)-Richtlinien.' 
---
= Management von Volumes und virtuellen Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Daten in einem Cluster verwalten, auf dem die Element Software ausgeführt wird, auf der Registerkarte Management in der Element UI. Verfügbare Cluster-Managementfunktionen umfassen die Erstellung und das Management von Daten-Volumes, Volume-Zugriffsgruppen, Initiatoren und QoS-Richtlinien (Quality of Service).

* link:task_data_manage_volumes_work_with_volumes_task.html["Arbeiten mit Volumes"]
* link:concept_data_manage_vvol_work_virtual_volumes.html["Arbeiten mit virtuellen Volumes"]
* link:concept_data_manage_vol_access_group_work_with_volume_access_groups_and_initiators.html["Arbeiten Sie mit Volume-Zugriffsgruppen und -Initiatoren"]




== Finden Sie weitere Informationen

* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

