---
permalink: storage/concept_system_manage_system_management.html 
sidebar: sidebar 
keywords: element, cluster, fips, cluster, multi-factor authentication, authentication 
summary: 'Sie können Ihr System in der Element UI verwalten. Dies ermöglicht die Multi-Faktor-Authentifizierung, das Managen von Cluster-Einstellungen, unterstützt FIPS (Federal Information Processing Standards) und nutzt externes Verschlüsselungsmanagement.' 
---
= Management des Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihr System in der Element UI verwalten. Dies ermöglicht die Multi-Faktor-Authentifizierung, das Managen von Cluster-Einstellungen, unterstützt FIPS (Federal Information Processing Standards) und nutzt externes Verschlüsselungsmanagement.

* link:concept_system_manage_mfa_enable_multi_factor_authentication.html["Multi-Faktor-Authentifizierung aktivieren"]
* link:concept_system_manage_cluster_configure_cluster_settings.html["Konfigurieren Sie Cluster-Einstellungen"]
* link:task_system_manage_fips_create_a_cluster_supporting_fips_drives.html["Erstellen eines Clusters, das FIPS-Laufwerke unterstützt"]
* link:concept_system_manage_key_get_started_with_external_key_management.html["Erste Schritte mit externem Verschlüsselungsmanagement"]




== Finden Sie weitere Informationen

* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

