---
permalink: storage/reference_system_manage_fips_ssl_cipher_changes.html 
sidebar: sidebar 
keywords: fips, ssl ciphers, 140-2, encryption algorithms 
summary: SSL-Chiffren sind Verschlüsselungsalgorithmen, die von Hosts zur Einrichtung einer sicheren Kommunikation verwendet werden. Es gibt Standardchiffren, die Element Software unterstützt und nicht-Standardchiffren, wenn der FIPS 140-2-Modus aktiviert ist. 
---
= SSL-Chiffren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSL-Chiffren sind Verschlüsselungsalgorithmen, die von Hosts zur Einrichtung einer sicheren Kommunikation verwendet werden. Es gibt Standardchiffren, die Element Software unterstützt und nicht-Standardchiffren, wenn der FIPS 140-2-Modus aktiviert ist.

Die folgenden Listen enthalten die von der Element-Software unterstützten Standard-SSL-Chiffren (Secure Socket Layer) und die SSL-Chiffren, die unterstützt werden, wenn der FIPS 140-2-Modus aktiviert ist:

* *FIPS 140-2 deaktiviert*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (DH 2048) - A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (DH 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (DH 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (DH 2048) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECP256R1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECP256R1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECP256R1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECP256R1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (RSA 2048) – C

+
TLS_RSA_WITH_AES_128_CBC_SHA (RSA 2048) – A

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA (RSA 2048) – A

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (RSA 2048) - A

+
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_IDEA_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_RC4_128_MD5 (RSA 2048) – C

+
TLS_RSA_WITH_RC4_128_SHA (RSA 2048) – C

+
TLS_RSA_WITH_SEED_CBC_SHA (RSA 2048) - A

* *FIPS 140-2 aktiviert*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (DH 2048) - A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (DH 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (DH 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (DH 2048) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECT571R1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECP256R1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECP256R1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECT571R1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECT571R1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECP256R1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECP256R1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECT571R1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (RSA 2048) – C

+
TLS_RSA_WITH_AES_128_CBC_SHA (RSA 2048) – A

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA (RSA 2048) – A

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (RSA 2048) - A





== Weitere Informationen

xref:task_system_manage_fips_enable_fips_140_2_for_https.adoc[Aktivieren Sie FIPS 140-2 für HTTPS auf dem Cluster]
