---
permalink: storage/task_data_protection_back_up_volume_to_amazon_s3.html 
sidebar: sidebar 
keywords: volume backup, amazon s3 object store 
summary: Sie können Backups von Volumes auf externen Objektspeichern erstellen, die mit Amazon S3 kompatibel sind. 
---
= Volumes werden in einem Amazon S3-Objektspeicher gesichert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Backups von Volumes auf externen Objektspeichern erstellen, die mit Amazon S3 kompatibel sind.

. Klicken Sie Auf *Management* > *Volumes*.
. Klicken Sie auf das Symbol Aktionen für das zu Sicherungsvolumen.
. Klicken Sie im Menü Ergebnis auf *Sichern nach*.
. Wählen Sie im Dialogfeld * Integriertes Backup* unter *Backup in* die Option *S3* aus.
. Wählen Sie eine Option unter *Datenformat* aus:
+
** *Native*: Ein komprimiertes Format, das nur von SolidFire-Speichersystemen lesbar ist.
** *Unkomprimiert*: Ein unkomprimiertes Format, das mit anderen Systemen kompatibel ist.


. Geben Sie einen Hostnamen ein, der für den Zugriff auf den Objektspeicher im Feld *Hostname* verwendet werden soll.
. Geben Sie im Feld *Zugriffsschlüssel-ID* eine Zugriffsschlüssel-ID für das Konto ein.
. Geben Sie den geheimen Zugriffsschlüssel für das Konto im Feld * Secret Access Key* ein.
. Geben Sie den S3-Bucket ein, in dem die Sicherung im Feld *S3 Bucket* gespeichert werden soll.
. Geben Sie im Feld *Nametag* einen Namensschild ein, der an das Präfix angefügt werden soll.
. Klicken Sie Auf *Lesen Starten*.

