---
permalink: storage/task_data_protection_schedule_a_snapshot_task.html 
sidebar: sidebar 
keywords: snapshot, schedule, volume snapshots, group snapshots 
summary: Sie können Daten auf einem Volume oder einer Gruppe von Volumes schützen, indem Sie die Volume Snapshots in bestimmten Intervallen planen. Sie können entweder einzelne Volume-Snapshots planen oder Snapshots gruppieren, um automatisch auszuführen. 
---
= Planen Sie einen Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Daten auf einem Volume oder einer Gruppe von Volumes schützen, indem Sie die Volume Snapshots in bestimmten Intervallen planen. Sie können entweder einzelne Volume-Snapshots planen oder Snapshots gruppieren, um automatisch auszuführen.

Wenn Sie einen Snapshot-Zeitplan konfigurieren, können Sie zwischen verschiedenen Zeitabständen wählen, die auf Wochentagen oder Tagen des Monats basieren. Sie können auch Tage, Stunden und Minuten festlegen, bevor der nächste Snapshot erstellt wird. Sie können die resultierenden Snapshots auf einem Remote-Storage-System speichern, wenn das Volume repliziert wird.



== Weitere Informationen

* xref:task_data_protection_create_a_snapshot_schedule.adoc[Erstellen eines Snapshot-Zeitplans]
* xref:task_data_protection_edit_a_snapshot_schedule.adoc[Bearbeiten eines Snapshot-Zeitplans]
* xref:task_data_protection_delete_a_snapshot_schedule.adoc[Löschen Sie einen Snapshot-Zeitplan]
* xref:task_data_protection_copy_a_snapshot_schedule.adoc[Snapshot-Zeitplan kopieren]

