---
permalink: storage/task_data_protection_use_group_snapshots_for_data_protection.html 
sidebar: sidebar 
keywords: group snapshots, data protection, set of volumes, backup, rollback 
summary: Sie können einen Gruppen-Snapshot einer verwandten Gruppe von Volumes erstellen, um eine zeitpunktgenaue Kopie der Metadaten für jedes Volume aufzubewahren. Sie können den Gruppen-Snapshot zukünftig als Backup oder Rollback verwenden, um den Zustand der Volume-Gruppe in einen vorherigen Zustand wiederherzustellen. 
---
= Gruppen-Snapshots für Datenschutzaufgabe wird verwendet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Gruppen-Snapshot einer verwandten Gruppe von Volumes erstellen, um eine zeitpunktgenaue Kopie der Metadaten für jedes Volume aufzubewahren. Sie können den Gruppen-Snapshot zukünftig als Backup oder Rollback verwenden, um den Zustand der Volume-Gruppe in einen vorherigen Zustand wiederherzustellen.



== Weitere Informationen

* xref:task_data_protection_create_a_group_snapshot.adoc[Erstellen Sie einen Gruppen-Snapshot]
* xref:task_data_protection_edit_group_snapshots.adoc[Gruppenschnappschüsse bearbeiten]
* xref:task_data_protection_edit_members_of_group_snapshot.adoc[Mitglieder des Gruppenschnappschusses bearbeiten]
* xref:task_data_protection_delete_a_group_snapshot.adoc[Löschen eines Gruppen-Snapshots]
* xref:task_data_protection_roll_back_volumes_to_a_group_snapshot.adoc[Rollback von Volumes zu einem Gruppen-Snapshot]
* xref:task_data_protection_clone_multiple_volumes.adoc[Klonen mehrerer Volumes]
* xref:task_data_protection_clone_multiple_volumes_from_a_group_snapshot.adoc[Mehrere Volumes aus einem Gruppen-Snapshot klonen]

