---
permalink: storage/task-element-replication-enable-snapmirror-cluster.html 
sidebar: sidebar 
keywords: ontap, cli, enable, snapmirror, element, cluster 
summary: Sie müssen SnapMirror auf dem Element-Cluster aktivieren, bevor Sie eine Replizierungsbeziehung erstellen können. Sie können diese Aufgabe nur in der Webbenutzeroberfläche der Element-Software oder mit der API-Methode ausführen. 
---
= Aktivieren Sie SnapMirror auf dem Element Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen SnapMirror auf dem Element-Cluster aktivieren, bevor Sie eine Replizierungsbeziehung erstellen können. Sie können diese Aufgabe nur in der Web-Benutzeroberfläche der Element-Software oder über die ausführenlink:../api/reference_element_api_enablefeature.html["API-Methode"].

.Bevor Sie beginnen
* Auf dem Element Cluster muss die NetApp Element Softwareversion 10.1 oder höher ausgeführt werden.
* SnapMirror kann nur für Element Cluster aktiviert werden, die in NetApp ONTAP Volumes verwendet werden.


.Über diese Aufgabe
Das Element System wird standardmäßig mit SnapMirror deaktiviert. SnapMirror wird im Rahmen einer neuen Installation oder eines Upgrades nicht automatisch aktiviert.

[NOTE]
====
Nach der Aktivierung kann SnapMirror nicht deaktiviert werden. Sie können die SnapMirror Funktion nur deaktivieren und die Standardeinstellungen wiederherstellen, indem Sie das Cluster wieder an das Werkseinstellungen zurücksetzen.

====
.Schritte
. Klicken Sie Auf *Cluster* > *Einstellungen*.
. Suchen Sie die Cluster-spezifischen Einstellungen für SnapMirror.
. Klicken Sie auf *SnapMirror aktivieren*.

