---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'Sie können das Standard-Administratorpasswort für die Intelligent Platform Management Interface (IPMI) ändern, sobald Sie Remote-IPMI-Zugriff auf den Node haben. Sie möchten dies möglicherweise tun, wenn Installationsupdates vorhanden sind.' 
---
= Ändern Sie das Standard-IPMI-Passwort für Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Standard-Administratorpasswort für die Intelligent Platform Management Interface (IPMI) ändern, sobald Sie Remote-IPMI-Zugriff auf den Node haben. Sie möchten dies möglicherweise tun, wenn Installationsupdates vorhanden sind.

Weitere Informationen zur Konfiguration des IPM-Zugriffs für Knoten finden Sie unter link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["Konfigurieren Sie IPMI für jeden Node"^].

Sie können das IPM-Passwort für diese Knoten ändern:

* H410S Nodes
* H610S Nodes




== Ändern Sie das Standard-IPMI-Passwort für H410S-Nodes

Sie sollten das Standardpasswort für das IPMI-Administratorkonto auf jedem Speicherknoten ändern, sobald Sie den IPMI-Netzwerkport konfigurieren.

.Was Sie benötigen
Sie sollten die IPMI-IP-Adresse für jeden Storage-Node konfiguriert haben.

.Schritte
. Öffnen Sie einen Webbrowser auf einem Computer, der das IPMI-Netzwerk erreichen kann, und navigieren Sie zu der IPMI-IP-Adresse für den Knoten.
. Geben Sie den Benutzernamen ein `ADMIN` Und Passwort `ADMIN` In der Eingabeaufforderung für die Anmeldung.
. Klicken Sie beim Anmelden auf die Registerkarte *Konfiguration*.
. Klicken Sie Auf *Benutzer*.
. Wählen Sie die aus `ADMIN` Benutzer und klicken Sie auf *Benutzer ändern*.
. Aktivieren Sie das Kontrollkästchen *Passwort ändern*.
. Geben Sie ein neues Passwort in die Felder *Passwort* und *Passwort bestätigen* ein.
. Klicken Sie auf *Ändern* und dann auf *OK*.
. Wiederholen Sie dieses Verfahren für alle anderen H410S-Nodes mit Standard-IPMI-Kennwörtern.




== Ändern Sie das Standard-IPMI-Passwort für H610S-Nodes

Sie sollten das Standardpasswort für das IPMI-Administratorkonto auf jedem Speicherknoten ändern, sobald Sie den IPMI-Netzwerkport konfigurieren.

.Was Sie benötigen
Sie sollten die IPMI-IP-Adresse für jeden Storage-Node konfiguriert haben.

.Schritte
. Öffnen Sie einen Webbrowser auf einem Computer, der das IPMI-Netzwerk erreichen kann, und navigieren Sie zu der IPMI-IP-Adresse für den Knoten.
. Geben Sie den Benutzernamen ein `root` Und Passwort `calvin` In der Eingabeaufforderung für die Anmeldung.
. Wenn Sie sich anmelden, klicken Sie oben links auf der Seite auf das Symbol für die Menünavigation, um das Fach für die Seitenleiste zu öffnen.
. Klicken Sie Auf *Einstellungen*.
. Klicken Sie Auf *Benutzerverwaltung*.
. Wählen Sie den *Administrator*-Benutzer aus der Liste aus.
. Aktivieren Sie das Kontrollkästchen *Passwort ändern*.
. Geben Sie ein neues, starkes Passwort in die Felder *Passwort* und *Passwort bestätigen* ein.
. Klicken Sie unten auf der Seite auf *Speichern*.
. Wiederholen Sie dieses Verfahren für alle anderen H610S-Nodes mit Standard-IPMI-Kennwörtern.




== Weitere Informationen

* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

