---
permalink: storage/task_snapmirror_use_replication_between_element_and_ontap_clusters.html 
sidebar: sidebar 
keywords: replication, snapmirror, data protection 
summary: Sie können SnapMirror Beziehungen auf der Registerkarte Datensicherheit in der NetApp Element Benutzeroberfläche erstellen. Um dies in der Benutzeroberfläche zu sehen, muss die SnapMirror Funktionalität aktiviert sein. 
---
= SnapMirror Replizierung zwischen Element und ONTAP Clustern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können SnapMirror Beziehungen auf der Registerkarte Datensicherheit in der NetApp Element Benutzeroberfläche erstellen. Um dies in der Benutzeroberfläche zu sehen, muss die SnapMirror Funktionalität aktiviert sein.

IPv6 wird für die SnapMirror Replizierung zwischen NetApp Element Software und ONTAP Clustern nicht unterstützt.

https://www.youtube.com/embed/kerGI1ZtnZQ?rel=0["NetApp Video: SnapMirror für NetApp HCI und Element Software"^]

Systeme mit NetApp Element Software unterstützen SnapMirror Funktionen zum Kopieren und Wiederherstellen von Snapshot Kopien mit NetApp ONTAP Systemen. Der Hauptgrund für den Einsatz dieser Technologie ist die Disaster Recovery von NetApp HCI auf ONTAP. Endpunkte sind ONTAP, ONTAP Select und Cloud Volumes ONTAP. Siehe TR-4641 NetApp HCI Datensicherung.

https://www.netapp.com/pdf.html?item=/media/17048-tr4641pdf.pdf["Technischer Bericht 4641 zu NetApp HCI Datensicherung"^]



== Weitere Informationen

* https://www.netapp.com/pdf.html?item=/media/16991-tr4748pdf.pdf["Ihr Weg zur eigenen Data Fabric – mit NetApp HCI, ONTAP und konvergenter Infrastruktur"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-sdbak/home.html["Replizierung zwischen NetApp Element Software und ONTAP"^]

