---
permalink: storage/task_system_manage_virtual_enable_virtual_routing_and_forwarding.html 
sidebar: sidebar 
keywords: virtual routing, forwarding, enable, vrf, storage networks, create a vlan 
summary: 'Sie können virtuelles Routing und Forwarding \(VRF\) aktivieren, wodurch mehrere Instanzen einer Routingtabelle in einem Router existieren und gleichzeitig arbeiten können. Diese Funktion ist nur für Speichernetzwerke verfügbar.' 
---
= Aktivieren Sie virtuelles Routing und Forwarding
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können virtuelles Routing und Forwarding (VRF) aktivieren, wodurch mehrere Instanzen einer Routing-Tabelle in einem Router existieren und gleichzeitig arbeiten können. Diese Funktion ist nur für Speichernetzwerke verfügbar.

Sie können VRF nur zum Zeitpunkt der Erstellung eines VLANs aktivieren. Wenn Sie wieder zu nicht-VRF wechseln möchten, müssen Sie das VLAN löschen und neu erstellen.

. Klicken Sie Auf *Cluster* > *Netzwerk*.
. Um VRF auf einem neuen VLAN zu aktivieren, wählen Sie *VLAN erstellen*.
+
.. Geben Sie relevante Informationen für das neue VRF/VLAN ein. Siehe Hinzufügen eines virtuellen Netzwerks.
.. Aktivieren Sie das Kontrollkästchen *VRF aktivieren*.
.. *Optional*: Geben Sie ein Gateway ein.


. Klicken Sie auf *VLAN erstellen*.




== Weitere Informationen

xref:task_system_manage_virtual_add_a_virtual_network.adoc[Fügen Sie ein virtuelles Netzwerk hinzu]
