---
permalink: storage/task-element-replication-initialize-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, initialize, replication, relationship 
summary: 'Bei allen Beziehungstypen führt die Initialisierung einen Basistransfer durch: Es erstellt eine Snapshot-Kopie des Quell-Volume und überträgt dann die Kopie mit allen Datenblöcken, die sie auf das Ziel-Volume referenzieren.' 
---
= Initialisieren Sie eine Replikationsbeziehung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei allen Beziehungstypen führt die Initialisierung eine _Baseline Transfer_ durch: Es erstellt eine Snapshot Kopie des Quell-Volume und überträgt dann die Kopie mit allen Datenblöcken, die es auf das Ziel-Volume verweist.

.Bevor Sie beginnen
* Der Element-Node, der das zu replizierende Volume enthält, muss ONTAP zugänglich gemacht werden.
* Das Element Volume muss für die SnapMirror Replizierung aktiviert worden sein.
* Wenn Sie den Richtlinientyp „`mmirror-Vault`“ verwenden, muss für die Replikation der Element Snapshot-Kopien ein SnapMirror-Label konfiguriert sein.
+
[NOTE]
====
Sie können diese Aufgabe nur im oder mit der ausführenlink:concept_snapmirror_labels.html["Web-UI der Element Software"]link:../api/concept_element_api_snapshots_overview.html["API-Methoden"].

====


.Über diese Aufgabe
Sie müssen den Quellpfad des Elements im Formular angeben `<hostip:>/lun/<name>`, wobei „`lun`“ die tatsächliche Zeichenfolge „`lun`“ ist und `_name_` der Name des Element-Volumes ist.

Initialisierung kann sehr zeitaufwendig sein. Möglicherweise möchten Sie den Basistransfer in Zeiten geringerer Auslastung durchführen.

[NOTE]
====
Wenn die Initialisierung einer Beziehung von einer ONTAP Quelle zu einem Element Ziel aus irgendeinem Grund fehlschlägt, wird sie weiterhin fehlschlagen, selbst wenn Sie das Problem behoben haben (z. B. ein ungültiger LUN-Name). Die Behelfslösung sieht wie folgt aus:

. Löschen Sie die Beziehung.
. Löschen Sie das Element Ziel-Volume.
. Erstellung eines neuen Element Ziel-Volume
. Erstellen und Initialisieren einer neuen Beziehung von der ONTAP Quelle auf das Ziel-Volume des Element


====
.Schritt
. Initialisieren einer Replikationsbeziehung:
+
`snapmirror initialize -source-path <hostip:>/lun/<name> -destination-path <SVM:volume|cluster://SVM/volume>`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Das folgende Beispiel initialisiert die Beziehung zwischen dem Quell-Volume `0005` an der IP-Adresse 10.0.0.11 und dem Ziel-Volume `volA_dst` auf `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

