---
permalink: storage/task_snapmirror_add_labels_to_snapshot_schedules.html 
sidebar: sidebar 
keywords: snapmirror labels, add labels to snapshot schedules, snapmirror policies 
summary: Sie können SnapMirror Beschriftungen zu Snapshot-Zeitplänen hinzufügen, um sicherzustellen, dass eine SnapMirror-Richtlinie angewendet wird. Sie können verfügbare Labels aus einem vorhandenen SnapMirror-Beziehungsdialogfeld oder NetAppONTAP System Manager anzeigen. 
---
= Fügen Sie SnapMirror-Beschriftungen zu Snapshot-Zeitplänen hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können SnapMirror Beschriftungen zu Snapshot-Zeitplänen hinzufügen, um sicherzustellen, dass eine SnapMirror-Richtlinie angewendet wird. Sie können verfügbare Labels aus einem vorhandenen SnapMirror-Beziehungsdialogfeld oder NetAppONTAP System Manager anzeigen.

.Was Sie und#8217;ll benötigen
* SnapMirror muss auf Cluster-Ebene aktiviert sein.
* Die Beschriftung, die Sie hinzufügen möchten, ist bereits in ONTAP vorhanden.


.Schritte
. Klicken Sie Auf *Datenschutz* > *Termine*.
. Sie können einem Zeitplan auf eine der folgenden Arten ein SnapMirror-Label hinzufügen:
+
[cols="25,75"]
|===
| Option | Schritte 


 a| 
Erstellen eines neuen Zeitplans
 a| 
.. Wählen Sie *Zeitplan Erstellen*.
.. Geben Sie alle anderen relevanten Details ein.
.. Wählen Sie *Zeitplan Erstellen*.




 a| 
Ändern des vorhandenen Zeitplans
 a| 
.. Klicken Sie auf das Symbol *Aktionen* für den Zeitplan, dem Sie eine Bezeichnung hinzufügen möchten, und wählen Sie *Bearbeiten*.
.. Geben Sie im daraufhin angezeigten Dialogfeld Text in das Feld *SnapMirror Label* ein.
.. Wählen Sie *Änderungen Speichern*.


|===




== Weitere Informationen

xref:task_data_protection_create_a_snapshot_schedule.adoc[Erstellen eines Snapshot-Zeitplans]
