---
permalink: storage/task_replication_pair_volumes_using_a_volume_id.html 
sidebar: sidebar 
keywords: volume pairings, volume id, replication 
summary: Sie können ein Volume mit einem anderen Volume in einem Remote-Cluster koppeln, wenn Sie über Cluster-Administratorberechtigungen für das Remote-Cluster verfügen. 
---
= Kombinieren Sie Volumes mit einer Volume-ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Volume mit einem anderen Volume in einem Remote-Cluster koppeln, wenn Sie über Cluster-Administratorberechtigungen für das Remote-Cluster verfügen.

.Was Sie und#8217;ll benötigen
* Stellen Sie sicher, dass die Cluster, die die Volumes enthalten, gekoppelt sind.
* Erstellen Sie ein neues Volume auf dem Remote-Cluster.
+

NOTE: Sie können eine Replikationsquelle und ein Replikationsziel nach dem Pairing-Prozess zuweisen. Eine Replikationsquelle oder ein Replikationsziel kann ein Volume in einem Volume-Paar sein. Sie sollten ein Ziel-Volume erstellen, das keine Daten enthält und exakt die Merkmale des Quell-Volume hat, z. B. Größe, Einstellung der Blockgröße für die Volumes (512 oder 4 kb) und QoS-Konfiguration. Wenn Sie ein vorhandenes Volume als Replikationsziel zuweisen, werden die Daten auf diesem Volume überschrieben. Das Zielvolume kann größer oder gleich groß sein wie das Quellvolume, kann aber nicht kleiner sein.

* Die Ziel-Volume-ID kennen.


.Schritte
. Wählen Sie *Management* > *Volumes*.
. Klicken Sie auf das Symbol *Aktionen* für das Volume, das Sie koppeln möchten.
. Klicken Sie Auf *Paar*.
. Wählen Sie im Dialogfeld *Pair Volume* die Option *Pairing starten* aus.
. Wählen Sie *i do* aus, um anzugeben, dass Sie Zugriff auf den Remote-Cluster haben.
. Wählen Sie aus der Liste einen *Replikationsmodus* aus:
+
** *Echtzeit (Asynchron)*: Schreibvorgänge werden dem Client bestätigt, nachdem sie auf dem Quellcluster erstellt wurden.
** *Real-Time (Synchronous)*: Schreibvorgänge werden dem Client bestätigt, nachdem sie sowohl auf den Quell- als auch auf den Ziel-Clustern festgelegt sind.
** *Nur Snapshots*: Nur Snapshots, die auf dem Quellcluster erstellt wurden, werden repliziert. Aktive Schreibvorgänge vom Quell-Volume werden nicht repliziert.


. Wählen Sie aus der Liste einen Remote-Cluster aus.
. Wählen Sie eine Remote-Volume-ID aus.
. Klicken Sie Auf *Pairing Starten*.
+
Das System öffnet eine Webbrowser-Registerkarte, die eine Verbindung mit der Element-UI des Remote-Clusters herstellt. Unter Umständen müssen Sie sich mit den Anmeldedaten des Cluster-Administrators im Remote-Cluster anmelden.

. Wählen Sie in der Element-UI des Remote-Clusters die Option *Complete Pairing*.
. Bestätigen Sie die Details unter *Volume Pairing bestätigen*.
. Klicken Sie Auf *Pairing Abschließen*.
+
Nachdem Sie die Paarung bestätigt haben, beginnen die beiden Cluster den Prozess, die Volumes zum Koppeln zu verbinden. Während des Pairings können Sie Meldungen in der Spalte *Volume Status* des Fensters *Volume Pairs* sehen. Das Volume-Paar wird angezeigt `PausedMisconfigured` Bis die Quelle und das Ziel des Volume-Paars zugewiesen sind.

+
Nach erfolgreichem Abschluss der Paarung wird empfohlen, die Volumetabelle zu aktualisieren, um die *Pair*-Option aus der *Aktionen*-Liste für das gepaarte Volumen zu entfernen. Wenn Sie die Tabelle nicht aktualisieren, bleibt die Option *Paar* zur Auswahl verfügbar. Wenn Sie die Option *Pair* erneut auswählen, wird eine neue Registerkarte geöffnet, und da das Volume bereits gekoppelt ist, meldet das System einen `StartVolumePairing Failed: xVolumeAlreadyPaired` Fehlermeldung im Fenster *Pair Volume* der Element UI Seite.





== Weitere Informationen

* xref:reference_replication_volume_pairing_messages.adoc[Meldungen zur Volume-Kopplung]
* xref:reference_replication_volume_pairing_warnings.adoc[Warnungen zum Volume-Pairing]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[Weisen Sie gepaarten Volumes eine Replikationsquelle und ein Replikationsziel zu]

