---
permalink: esds/concept_esds_networking_best_practices.html 
sidebar: sidebar 
keywords: solidfire esds, software-defined storage, networks, linux host routing, networking 
summary: Vor der Installation von SolidFire ESDS sollten Sie die erforderlichen Netzwerke auf den Speicherknoten einrichten, auf denen RHEL ausgeführt wird. Sie sind für das Netzwerk-Routing in Ihrer Umgebung verantwortlich. Sie können die Best Practices, die als Framework zur Verfügung gestellt werden, verwenden. 
---
= Überlegungen bei der Netzwerkkonfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Installation von SolidFire ESDS sollten Sie die erforderlichen Netzwerke auf den Speicherknoten einrichten, auf denen RHEL ausgeführt wird. Sie sind für das Netzwerk-Routing in Ihrer Umgebung verantwortlich. Sie können die Best Practices, die als Framework zur Verfügung gestellt werden, verwenden.

[IMPORTANT]
====
* Verwenden Sie gebundene oder geteamte Schnittstellen.
* Verwenden Sie die gleichen Schnittstellennamen für alle Knoten im Cluster (z. B. Team-Management für die Managementoberfläche jedes Node und Team-stg für die Storage-Schnittstelle jedes Node).
* Stellen Sie sicher, dass NetworkManager ausgeführt wird.
* Stellen Sie sicher, dass das Paket „NetworkManager-Dispatcher-Routing-Rules“ auf allen Storage-Nodes für richtlinienbasiertes Routing installiert ist.
* Siehe https://www.netapp.com/us/media/tr-4763.pdf["Best Practices für die Netzwerk- und Netzwerkwartung bei NetApp SolidFire Storage-Systemen"].
* Konfigurieren Sie das Management- und die Storage-Netzwerke auf jedem Node so, dass mehrere redundante physische Schnittstellen über Bond oder Team-Konfigurationen verwendet werden.


====
Weitere Informationen zur Netzwerkbildung finden Sie unter https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-configure_network_teaming["Konfiguration der Netzwerk-Teaming"^]. Standardmäßig sind alle Storage-Node-10-GbE-Schnittstellen mit einer Maximum Transmission Unit (MTU) von 9000 Byte aktiviert. Für optimale Performance konfigurieren Sie alle Server-seitigen Storage-Schnittstellen mit derselben MTU wie die NetApp SolidFire Storage-Nodes. Sie sollten Netzwerk-Switches so konfigurieren, dass eine MTU von mindestens 9016 Byte oder mehr unterstützt wird, um den Jumbo Frame Overhead und die ordnungsgemäße Weiterleitung über das Netzwerk zu berücksichtigen. Wenn Sie diese Konfiguration ändern möchten, um eine niedrigere MTU-Einstellung zu unterstützen, wenden Sie sich an den NetApp Support.

In der folgenden Tabelle finden Sie Informationen zu den Speicher- und Verwaltungsnetzwerken, die SolidFire ESDS für die verschiedenen Arten von Datenverkehr benötigt:

[cols="2*"]
|===
| Netzwerktyp | Beschreibung 


 a| 
Datennetzwerk Storage-Netzwerk
 a| 
* Umfasst den gesamten Storage-/iSCSI-Datenverkehr.
* Sie können weitergeleitet werden, wenn Sie Hosts bereitstellen möchten, die sich auf einem anderen Layer-3-Netzwerk befinden, oder wenn Sie Daten zwischen Clustern replizieren möchten.
* Sollte mit Netzwerkschnittstellen auf derselben Layer 2 Broadcast-Domäne konfiguriert sein.




 a| 
Managementnetzwerk
 a| 
* Umfasst den gesamten Verwaltungsverkehr.
* Kann geroutet werden, wenn Sie über ein anderes Layer 3-Netzwerk auf die Cluster-API oder -UI zugreifen möchten.
* Sollte mit Netzwerkschnittstellen auf derselben Layer 2 Broadcast-Domäne konfiguriert sein.
* Sollte mit einer Netzwerkschnittstellenkarte mit einer MTU von mindestens 1500 Bytes konfiguriert werden.


|===

TIP: Beispiele und Tipps zur Konfiguration des Hostnetzwerks finden Sie unter link:task_esds_configure_the_interface_config_files.adoc["Hier"].



== Weitere Informationen

* https://www.netapp.com/data-storage/solidfire/documentation/["Ressourcen-Seite zu NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen von NetApp SolidFire und Element Produkten"^]

