---
permalink: esds/concept_esds_monitor_clusters.html 
sidebar: sidebar 
keywords: solidfire esds installation, hcc, hybrid cloud control, esds clusters 
summary: Sie können die Performance Ihrer SolidFire ESDS Cluster überwachen und den Bestand über die Benutzeroberfläche von NetApp Hybrid Cloud Control anzeigen. Sie können auch Protokolle zur Fehlerbehebung über die Benutzeroberfläche von NetApp Hybrid Cloud Control erfassen.“ 
---
= Monitoring der Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Performance Ihrer SolidFire ESDS Cluster überwachen und den Bestand über die Benutzeroberfläche von NetApp Hybrid Cloud Control anzeigen. Sie können auch Protokolle zur Fehlerbehebung über die Benutzeroberfläche von NetApp Hybrid Cloud Control erfassen.

Die folgenden Links führen zu den Informationen zum Monitoring Ihrer Cluster in der Benutzeroberfläche von NetApp Hybrid Cloud Control:

* link:hccstorage/task-hcc-nodes.html["Zeigen Sie Ihren Bestand auf der Seite Knoten an"]
* link:hccstorage/task-hcc-volumes.html["Überwachung von Volumes auf Ihrem Storage-Cluster"]




== Weitere Informationen

* https://www.netapp.com/data-storage/solidfire/documentation/["Ressourcen-Seite zu NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen von NetApp SolidFire und Element Produkten"^]

