---
permalink: esds/reference_esds_use_maintenance_mode.html 
sidebar: sidebar 
keywords: element, solidfire esds, maintenance, maintenance mode 
summary: Wenn Sie einen Storage Node für Wartungsarbeiten, wie z. B. Software-Upgrades oder Host-Reparaturen, offline schalten müssen, können Sie die Auswirkungen auf den Rest des Storage-Clusters durch Aktivierung des Wartungsmodus für diesen Node auf ein Minimum minimieren. 
---
= Verwenden Sie den Wartungsmodus auf SolidFire ESDS Clustern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen Storage Node für Wartungsarbeiten, wie z. B. Software-Upgrades oder Host-Reparaturen, offline schalten müssen, können Sie die Auswirkungen auf den Rest des Storage-Clusters durch Aktivierung des Wartungsmodus für diesen Node auf ein Minimum minimieren.


TIP: Wenn Sie den aktuellen Status des Wartungsmodus auf Ihrem Knoten überprüfen möchten, verwenden Sie den Link:./API/reference_element_api_listactivenodes.html[`ListActiveNodes`^] API-Methode. Das Node-Objekt enthält eine `maintenanceMode` Parameter, der den aktuellen Status des Wartungsmodus auf dem Node angibt.


NOTE: Stellen Sie sicher, dass Sie die Wartung durchführen, sobald der Wartungsmodus aktiviert ist. Verlassen Sie den Node nicht mehr als erforderlich im Wartungsmodus.

Sie können einen Storage Node nur in den Wartungsmodus versetzen, wenn der Node ordnungsgemäß ist (keine Blockierung von Cluster-Fehlern) und das Storage Cluster einem Ausfall einzelner Nodes gegenüber tolerant ist. Nachdem Sie den Wartungsmodus für einen gesunden und toleranten Node aktiviert haben, wird der Node nicht sofort migriert. Er wird überwacht, bis die folgenden Bedingungen erfüllt sind:

* Alle auf dem Node gehosteten Volumes haben einen Failover durchgeführt, und der Node hostet für jedes Volume nicht mehr als primärer Volume.
* Jedem Failover eines Volumes wird ein temporärer Standby-Node zugewiesen.


Nachdem diese Kriterien erfüllt sind, wird der Node in den Wartungsmodus versetzt. Wenn diese Kriterien innerhalb von fünf Minuten nicht erfüllt werden, wechselt der Node in den Wartungsmodus.

Wenn Sie den Wartungsmodus für einen Storage-Node deaktivieren, wird der Node überwacht, bis die folgenden Bedingungen erfüllt sind:

* Alle Daten werden vollständig zum Node repliziert.
* Alle blockierenden Cluster-Fehler werden behoben.
* Alle temporären Standby-Node-Zuweisungen für die auf dem Node gehosteten Volumes wurden deaktiviert.


Nachdem diese Kriterien erfüllt sind, wird der Node aus dem Wartungsmodus migriert. Wenn diese Kriterien nicht innerhalb einer Stunde erfüllt werden, kann der Node nicht in den Wartungsmodus wechseln.



== Mögliche Szenarien bei Verwendung des Wartungsmodus

* Wenn sich ein Node im Wartungsmodus befindet, ihn jedoch noch nicht neu gebootet wurde und/oder keine Wartung durchgeführt wurde oder Wartungsarbeiten durchgeführt wurden, und der Node wieder verfügbar ist und sich in einem ordnungsgemäßen Zustand befindet, der Wartungsmodus nicht deaktiviert ist, Und ein weiterer Node ausfällt. Der Wartungsmodus auf dem ersten Node wird automatisch deaktiviert.
* Wenn sich einer der Nodes im Wartungsmodus befindet und ein anderer Node gleichzeitig ausfällt, kommt es zu einem Ausfall. Sie müssen warten, bis der Node im Wartungsmodus wieder online geschaltet wird.
* Wenn Sie einen Knoten, der ein Mitglied eines Ensembles ist, für einen langen Zeitraum in den Wartungsmodus versetzen, wird das System ihn automatisch aus dem Ensemble entfernen, wenn andere Knoten an seiner Stelle hinzugefügt werden können.




== Aktivieren Sie den Wartungsmodus

Sie können den Wartungsmodus mit aktivieren `EnableMaintenanceMode` API-Methode. Diese Methode verfügt über die folgenden Eingabeparameter:

[cols="5*"]
|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
`forceWithUnresolvedFaults`
 a| 
Aktivierung des Wartungsmodus für diesen Node erzwingen, selbst wenn Cluster-Fehler blockiert sind.
 a| 
boolesch
 a| 
Falsch
 a| 
Nein



 a| 
`nodes`
 a| 
Die Liste der Node-IDs, die in den Wartungsmodus versetzt werden sollen. Es wird nur jeweils ein Node unterstützt.
 a| 
Integer-Array
 a| 
Keine
 a| 
Ja.



 a| 
`perMinutePrimarySwapLimit`
 a| 
Die Anzahl der primären Schichten, die pro Minute ausgetauscht werden sollen. Wenn nicht angegeben, werden alle primären Schichten gleichzeitig ausgetauscht.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Nein



 a| 
`timeout`
 a| 
Gibt an, wie lange der Wartungsmodus aktiviert bleiben soll, bevor er automatisch deaktiviert wird. Formatiert als Zeitzeichenfolge (z. B. HH:mm:ss). Wenn nicht angegeben, bleibt der Wartungsmodus aktiviert, bis er explizit deaktiviert ist.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein

|===
Diese Methode verfügt über die folgenden Rückgabewerte:

[cols="3*"]
|===
| Name | Beschreibung | Typ 


 a| 
`asyncHandle`
 a| 
Sie können das verwenden `GetAsyncResult` Nutzen Sie diese Methode, um diese Async zu abrufen und zu bestimmen, wann die Transition des Wartungsmodus abgeschlossen ist.
 a| 
Ganzzahl



 a| 
`currentMode`
 a| 
Der aktuelle Status des Wartungsmodus des Node. Mögliche Werte:

* Deaktiviert: Es wurde keine Wartung angefordert.
* FailedToRecover: Der Knoten konnte nicht aus dem Wartungsmodus wiederherstellen.
* RecoveringFromMaintenance: Der Knoten wird gerade vom Wartungsmodus wiederhergestellt.
* VorbereitungForMaintenance: Es werden Maßnahmen ergriffen, um einen Knoten vorzubereiten, der gewartet werden soll.
* ReadyForMaintenance: Der Knoten ist zur Durchführung der Wartung bereit.

 a| 
Wartungsmodus (String)



 a| 
`requestedMode`
 a| 
Der angeforderte Wartungsmodus des Node. Mögliche Werte:

* Deaktiviert: Es wurde keine Wartung angefordert.
* FailedToRecover: Der Knoten konnte nicht aus dem Wartungsmodus wiederherstellen.
* RecoveringFromMaintenance: Der Knoten wird gerade vom Wartungsmodus wiederhergestellt.
* VorbereitungForMaintenance: Es werden Maßnahmen ergriffen, um einen Knoten vorzubereiten, der gewartet werden soll.
* ReadyForMaintenance: Der Knoten ist zur Durchführung der Wartung bereit.

 a| 
Wartungsmodus (String)

|===


== Deaktivieren des Wartungsmodus

Sie können den Wartungsmodus mit deaktivieren `DisableMaintenanceMode` API-Methode. Diese Methode verfügt über den folgenden Eingabeparameter:

[cols="5*"]
|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
`nodes`
 a| 
Liste der Storage-Node-IDs, die den Wartungsmodus nicht verlassen sollen
 a| 
Integer-Array
 a| 
Keine
 a| 
Ja.

|===
Diese Methode verfügt über die folgenden Rückgabewerte:

[cols="3*"]
|===
| Name | Beschreibung | Typ 


 a| 
`asyncHandle`
 a| 
Sie können das verwenden `GetAsyncResult` Nutzen Sie diese Methode, um diese Async zu abrufen und zu bestimmen, wann die Transition des Wartungsmodus abgeschlossen ist.
 a| 
Ganzzahl



 a| 
`currentMode`
 a| 
Der aktuelle Status des Wartungsmodus des Node. Mögliche Werte:

* Deaktiviert: Es wurde keine Wartung angefordert.
* FailedToRecover: Der Knoten konnte nicht aus dem Wartungsmodus wiederherstellen.
* Unerwartete: Der Node wurde offline gefunden, war aber im deaktivierten Modus.
* RecoveringFromMaintenance: Der Knoten wird gerade vom Wartungsmodus wiederhergestellt.
* VorbereitungForMaintenance: Es werden Maßnahmen ergriffen, um einen Knoten vorzubereiten, der gewartet werden soll.
* ReadyForMaintenance: Der Knoten ist zur Durchführung der Wartung bereit.

 a| 
Wartungsmodus (String)



 a| 
`requestedMode`
 a| 
Der angeforderte Wartungsmodus des Node. Mögliche Werte:

* Deaktiviert: Es wurde keine Wartung angefordert.
* FailedToRecover: Der Knoten konnte nicht aus dem Wartungsmodus wiederherstellen.
* Unerwartete: Der Node wurde offline gefunden, war aber im deaktivierten Modus.
* RecoveringFromMaintenance: Der Knoten wird gerade vom Wartungsmodus wiederhergestellt.
* VorbereitungForMaintenance: Es werden Maßnahmen ergriffen, um einen Knoten vorzubereiten, der gewartet werden soll.
* ReadyForMaintenance: Der Knoten ist zur Durchführung der Wartung bereit.

 a| 
Wartungsmodus (String)

|===


== Weitere Informationen

* https://www.netapp.com/data-storage/solidfire/documentation/["Ressourcen-Seite zu NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen von NetApp SolidFire und Element Produkten"^]

