---
permalink: esds/task_esds_uninstall.html 
sidebar: sidebar 
keywords: solidfire esds, uninstalling solidfire esds, ansible role 
summary: Sie können einen Knoten, auf dem Sie SolidFire ESDS installiert haben, durch Entfernen von SolidFire ESDS auf dem Knoten „zurücksetzen“. Zum Reaktivieren von SolidFire ESDS auf dem Knoten sollten Sie alle Installationsschritte durchführen. 
---
= Deinstallieren Sie SolidFire ESDS auf dem Knoten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Knoten, auf dem Sie SolidFire ESDS installiert haben, durch Entfernen von SolidFire ESDS auf dem Knoten * zurücksetzen. Zum Reaktivieren von SolidFire ESDS auf dem Knoten sollten Sie alle Installationsschritte durchführen.


NOTE: Sie können den Link:https://github.com/NetApp-Automation/nar_solidfire_sds_uninstall verwenden[`nar_solidfire_sds_uninstall`^] Ansible-Rolle von NetApp zur Durchführung des Vorgangs Wenn Sie SolidFire ESDS auf dem Knoten manuell entfernen möchten, lesen Sie die folgenden Schritte.

.Schritte
. Entfernen Sie Laufwerke aus dem Cluster mithilfe der Element-UI oder der[`RemoveDrives`^] API-Methode.
+
Daher werden Daten im System von Laufwerken des Node auf andere Laufwerke im Cluster migriert. Die Dauer dieses Prozesses hängt davon ab, wie viele Daten migriert werden müssen.

. Entfernen Sie den Knoten mithilfe der Element-UI oder der aus dem Cluster[`RemoveNodes`^] API-Methode.
. Verwenden Sie SSH, um eine Verbindung zum Node herzustellen, der aus dem Cluster entfernt wird.
. Entfernen Sie SolidFire ESDS wie folgt aus dem Knoten:
+
[listing]
----
yum remove solidfire-element
----
. Entfernen Sie persistente Daten aus dem Verzeichnis wie folgt:
+
[listing]
----
rm -rf /opt/sf
----




== Weitere Informationen

* https://www.netapp.com/data-storage/solidfire/documentation/["Ressourcen-Seite zu NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen von NetApp SolidFire und Element Produkten"^]

