---
permalink: api/concept_element_api_administrator_api_methods.html 
sidebar: sidebar 
keywords: API,administration,method,administrator 
summary: Mithilfe von Administrator-API-Methoden können Storage-Cluster-Administratoren Storage-Cluster-Administratoren erstellen, ändern, anzeigen und entfernen sowie Zugriffsebenen und Berechtigungen für Benutzer mit Zugriff auf ein Storage-Cluster zuweisen. 
---
= Administrator-API-Methoden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe von Administrator-API-Methoden können Storage-Cluster-Administratoren Storage-Cluster-Administratoren erstellen, ändern, anzeigen und entfernen sowie Zugriffsebenen und Berechtigungen für Benutzer mit Zugriff auf ein Storage-Cluster zuweisen.

* xref:reference_element_api_addclusteradmin.adoc[AddClusterAdmin]
* xref:reference_element_api_getcurrentclusteradmin.adoc[GetCurrentClusterAdmin]
* xref:reference_element_api_getloginbanner.adoc[GetLoginBanner]
* xref:reference_element_api_listclusteradmins.adoc[ListenClusteradministratoren]
* xref:reference_element_api_modifyclusteradmin.adoc[ModifyClusterAdmin]
* xref:reference_element_api_removeclusteradmin.adoc[RemoveClusterAdmin]
* xref:reference_element_api_setloginbanner.adoc[SetLoginBanner]




== Weitere Informationen

* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen von NetApp SolidFire und Element Produkten"^]

