---
permalink: api/concept_element_api_replication_api_methods.html 
sidebar: sidebar 
keywords: replication,api,methods 
summary: 'Mit den Replication-API-Methoden können Sie zwei Cluster verbinden, um einen kontinuierlichen Datenschutz zu ermöglichen \(CDP\). Wenn Sie zwei Cluster verbinden, können aktive Volumes innerhalb eines Clusters kontinuierlich auf ein zweites Cluster repliziert werden, um eine Datenwiederherstellung bereitzustellen. Durch das Pairing von Volumes zur Replikation können Sie Ihre Daten vor Ereignissen schützen, die den Zugriff auf diese Dateien möglicherweise nicht ermöglichen.' 
---
= Replizierungs-API-Methoden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit den Replication-API-Methoden können Sie zwei Cluster verbinden, um einen kontinuierlichen Datenschutz (CDP) zu ermöglichen. Wenn Sie zwei Cluster verbinden, können aktive Volumes innerhalb eines Clusters kontinuierlich auf ein zweites Cluster repliziert werden, um eine Datenwiederherstellung bereitzustellen. Durch das Pairing von Volumes zur Replikation können Sie Ihre Daten vor Ereignissen schützen, die den Zugriff auf diese Dateien möglicherweise nicht ermöglichen.

* xref:reference_element_api_cluster_pairing_order_of_operations.adoc[Reihenfolge der Vorgänge für die Cluster-Paarung]
* xref:reference_element_api_volume_pairing_order_of_operations.adoc[Reihenfolge der Vorgänge für die Volume-Kopplung]
* xref:reference_element_api_supported_modes_of_replication.adoc[Unterstützte Replikationsmodi für gepaarte Cluster]
* xref:reference_element_api_completeclusterpairing.adoc[CompleteClusterPairing]
* xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]
* xref:reference_element_api_listclusterpairs.adoc[ListenClusterpaare]
* xref:reference_element_api_listactivepairedvolumes.adoc[ListeActivePairedVolumes]
* xref:reference_element_api_modifyvolumepair.adoc[ModifyVolumePair]
* xref:reference_element_api_removeclusterpair.adoc[RemoveClusterPair]
* xref:reference_element_api_removevolumepair.adoc[RemoveVolumePair]
* xref:reference_element_api_startclusterpairing.adoc[StartClusterPairing]
* xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing]




== Weitere Informationen

* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen von NetApp SolidFire und Element Produkten"^]

