---
permalink: api/concept_element_api_vvols_api_methods.html 
sidebar: sidebar 
keywords: virtual,volume,vvol,API,method 
summary: 'Mit den API-Methoden der Element Software für virtuelle Volumes können Sie virtuelle Volumes \ (VVols\) managen. Vorhandene VVols können mit diesen API-Methoden angezeigt werden sowie Storage Container für virtuelle Volumes erstellen, ändern und löschen. Obwohl Sie diese Methoden nicht zum Betrieb auf normalen Volumes verwenden können, können Sie die normalen Volume-API-Methoden verwenden, um Informationen über VVols aufzulisten.' 
---
= API-Methoden für virtuelle Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit Element Software können Sie Virtual Volume API-Methoden (VVols) managen. Vorhandene VVols können mit diesen API-Methoden angezeigt werden sowie Storage Container für virtuelle Volumes erstellen, ändern und löschen. Obwohl Sie diese Methoden nicht zum Betrieb auf normalen Volumes verwenden können, können Sie die normalen Volume-API-Methoden verwenden, um Informationen über VVols aufzulisten.

* xref:reference_element_api_createstoragecontainer.adoc[CreateStorageContainer]
* xref:reference_element_api_deletestoragecontainers.adoc[DeleteStorageContainers]
* xref:reference_element_api_getstoragecontainerefficiency.adoc[GetStorageContainerEffizienz]
* xref:reference_element_api_getvirtualvolumecount.adoc[GetVirtualVolumeCount]
* xref:reference_element_api_listprotocolendpoints.adoc[ListProtocolEndpunkte]
* xref:reference_element_api_liststoragecontainers.adoc[ListStorageContainer]
* xref:reference_element_api_listvirtualvolumebindings.adoc[ListVirtualVolumeBindungen]
* xref:reference_element_api_listvirtualvolumehosts.adoc[ListVirtualVolumeHosts]
* xref:reference_element_api_listvirtualvolumes.adoc[ListVirtualVolumes]
* xref:reference_element_api_listvirtualvolumetasks.adoc[ListVirtualVolumeTasks]
* xref:reference_element_api_modifystoragecontainer.adoc[ModifyStorageContainer]




== Weitere Informationen

* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen von NetApp SolidFire und Element Produkten"^]

