---
permalink: api/concept_element_api_request_endpoints.html 
sidebar: sidebar 
keywords: request,endpoints 
summary: 'In der API \ (Storage-Cluster, Storage-Cluster-Erstellung und pro Node\) werden drei Typen von Anforderungsendpunkten verwendet. Sie sollten immer den neuesten Endpunkt verwenden, der von Ihrer Version der Element Software unterstützt wird.' 
---
= Endpunkte anfordern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die API verwendet drei Typen von Anforderungsendpunkten (Storage-Cluster, Storage-Cluster-Erstellung und pro Node). Sie sollten immer den neuesten Endpunkt verwenden, der von Ihrer Version der Element Software unterstützt wird.

Die drei Anforderungsendpunkte in der API sind wie folgt gekennzeichnet:



== Cluster-API-Methoden

Der HTTPS-Endpunkt für Storage-Cluster-weite API-Anforderungen ist `+https://<mvip>/json-rpc/<api-version>+`, Wo:

* `<mvip>` Ist die Management-virtuelle IP-Adresse für das Storage-Cluster.
* `<api-version>` Ist die Version der API, die Sie verwenden.




== API-Methoden für die Cluster-Erstellung und das Bootstrap

Der HTTPS-Endpunkt zum Erstellen eines Storage-Clusters und zum Zugriff auf Bootstrap-API-Anforderungen ist `+https://<nodeIP>/json-rpc/<api-version>+`, Wo:

* `<nodeIP>` Die IP-Adresse des Node, den Sie dem Cluster hinzufügen.
* `<api-version>` Ist die Version der API, die Sie verwenden.




== API-Methoden pro Node

Der HTTPS-Endpunkt für individuelle API-Anforderungen an den Storage-Node ist `+https://<nodeIP>:442/json-rpc/<api-version>+`, Wo:

* `<nodeIP>` Ist die Management-IP-Adresse des Storage-Node; 442 ist der Port, auf dem der HTTPS-Server ausgeführt wird.
* `<api-version>` Ist die Version der API, die Sie verwenden.




== Weitere Informationen

* https://www.netapp.com/data-storage/solidfire/documentation/["Ressourcen-Seite zu NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen von NetApp SolidFire und Element Produkten"^]

