---
permalink: api/reference_element_api_account.html 
sidebar: sidebar 
keywords: account,object,accounts 
summary: Das Kontoobjekt enthält Informationen zu einem Konto. Dieses Objekt enthält nur „konfigurierte“ Informationen über das Konto, keine Laufzeitinformationen oder Nutzungsinformationen. 
---
= Konto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Kontoobjekt enthält Informationen zu einem Konto. Dieses Objekt enthält nur „konfigurierte“ Informationen über das Konto, keine Laufzeitinformationen oder Nutzungsinformationen.



== Objektmitglieder verwenden

Dieses Objekt enthält die folgenden Mitglieder:

|===
| Name | Beschreibung | Typ 


 a| 
AccountID
 a| 
Die eindeutige Konto-ID für das Konto.
 a| 
Ganzzahl



 a| 
Merkmale
 a| 
Liste von Name-Wert-Paaren im JSON-Objektformat.
 a| 
JSON-Objekt



 a| 
AbleableAbtlg
 a| 
Gibt an, ob CHAP-Kontoanmeldeinformationen von einem Initiator für den Zugriff auf Volumes verwendet werden können.
 a| 
boolesch



 a| 
InitiatorSecret
 a| 
Der Initiator-CHAP-Schlüssel.
 a| 
Zeichenfolge



 a| 
Status
 a| 
Der aktuelle Status des Kontos. Mögliche Werte:

* Aktiv: Ein aktives Konto.
* Gesperrt: Ein gesperrtes Konto.
* Entfernt: Ein Konto, das gelöscht und gelöscht wurde.

 a| 
Zeichenfolge



 a| 
SpeicherkontainerID
 a| 
Die eindeutige ID des mit diesem Konto verknüpften Speichercontainers für virtuelle Volumes.
 a| 
UUID



 a| 
TargetSecret
 a| 
Der CHAP-Schlüssel des Ziels.
 a| 
Zeichenfolge



 a| 
Benutzername
 a| 
Der Benutzername für das Konto.
 a| 
Zeichenfolge



 a| 
Volumes
 a| 
Eine Liste der Volume-IDs für Volumes, die dem Konto gehören.
 a| 
Integer-Array

|===


== Weitere Informationen

* xref:reference_element_api_addaccount.adoc[AddAccount]
* xref:reference_element_api_getaccountbyid.adoc[GetAccountByID]
* xref:reference_element_api_getaccountbyname.adoc[GetAccountByName]
* xref:reference_element_api_listaccounts.adoc[Listenkonten]

