---
permalink: api/reference_element_api_disablemaintenancemode.html 
sidebar: sidebar 
keywords: disable,maintenance,mode 
summary: Sie können die Verwendung der DisableInstandhaltungmodus-Methode verwenden, um den Wartungsmodus eines Speicherknoten zu beenden. Nachdem Sie die Wartung abgeschlossen haben und der Node online ist, sollten Sie den Wartungsmodus nur deaktivieren. 
---
= Instandhaltungmodus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `DisableMaintenanceMode` Methode, um den Wartungsmodus eines Storage-Node zu beenden. Nachdem Sie die Wartung abgeschlossen haben und der Node online ist, sollten Sie den Wartungsmodus nur deaktivieren.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Knoten
 a| 
Liste der Storage-Node-IDs, die den Wartungsmodus nicht verlassen sollen
 a| 
Integer-Array
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===


| Name | Beschreibung | Typ 


 a| 
Asynchron
 a| 
Sie können die Methode GetAsyncResult verwenden, um diese Async Handle abzurufen und zu bestimmen, wann die Transition des Wartungsmodus abgeschlossen ist.
 a| 
Ganzzahl



 a| 
Stromstärkemodus
 a| 
Der aktuelle Status des Wartungsmodus des Node. Mögliche Werte:

* Deaktiviert: Es wurde keine Wartung angefordert.
* FailedToRecover: Der Knoten konnte nicht aus dem Wartungsmodus wiederherstellen.
* Unerwartete: Der Node wurde offline gefunden, war aber im deaktivierten Modus.
* RecoveringFromMaintenance: Der Knoten wird gerade vom Wartungsmodus wiederhergestellt.
* VorbereitungForMaintenance: Es werden Maßnahmen ergriffen, um einen Knoten vorzubereiten, der gewartet werden soll.
* ReadyForMaintenance: Der Knoten ist zur Durchführung der Wartung bereit.

 a| 
Wartungsmodus (String)



 a| 
Anforderungsmodus
 a| 
Der angeforderte Wartungsmodus des Node. Mögliche Werte:

* Deaktiviert: Es wurde keine Wartung angefordert.
* FailedToRecover: Der Knoten konnte nicht aus dem Wartungsmodus wiederherstellen.
* Unerwartete: Der Node wurde offline gefunden, war aber im deaktivierten Modus.
* RecoveringFromMaintenance: Der Knoten wird gerade vom Wartungsmodus wiederhergestellt.
* VorbereitungForMaintenance: Es werden Maßnahmen ergriffen, um einen Knoten vorzubereiten, der gewartet werden soll.
* ReadyForMaintenance: Der Knoten ist zur Durchführung der Wartung bereit.

 a| 
Wartungsmodus (String)

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "DisableMaintenanceMode",
  "params": {
    "nodes": [6]
  },
"id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 1,
   "result":
      {
        "requestedMode": "Disabled",
        "asyncHandle": 1,
        "currentMode": "Enabled"
    }
}
----


== Neu seit Version

12.2



== Weitere Informationen

http://docs.netapp.com/us-en/hci/docs/concept_hci_storage_maintenance_mode.html["Konzepte des NetApp HCI Storage-Wartungsmodus"^]
