---
permalink: api/reference_element_api_listfibrechannelportinfo.html 
sidebar: sidebar 
keywords: fibre,channel,port,ports,list,listing,listfibrechannelportinfo 
summary: Sie können mit der Methode ListFiberChannelPortInfo Informationen zu den Fibre Channel-Ports auflisten. 
---
= ListFiberChannelPortInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListFibreChannelPortInfo` „Methode“ zum Auflisten von Informationen zu den Fibre Channel-Ports.

Diese API-Methode ist für die Verwendung auf einzelnen Knoten bestimmt. Für den Zugriff auf einzelne Fibre Channel-Knoten sind eine Benutzer-ID und ein Passwort erforderlich. Diese Methode kann jedoch im Cluster verwendet werden, wenn der Kraft-Parameter auf „true“ gesetzt ist. Wenn Sie auf dem Cluster verwendet werden, werden alle Fibre-Channel-Schnittstellen aufgeführt.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Erzwingen
 a| 
Auf „true“ setzen, um auf allen Nodes im Cluster ausgeführt zu werden.
 a| 
boolesch
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Fibre Channel-Ports
 a| 
Eine Liste aller physischen Fibre-Channel-Ports oder ein Port für einen einzelnen Node.
 a| 
xref:reference_element_api_fibrechannelport.adoc[Fibre Channel-Port] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ListFibreChannelPortInfo",
    "params": {},
    "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "fibreChannelPortInfo": {
      "5": {
        "result": {
          "fibreChannelPorts": [
            {
             "firmware": "7.04.00 (d0d5)",
             "hbaPort": 1,
             "model": "QLE2672",
             "nPortID": "0xc70084",
             "pciSlot": 3,
             "serial": "BFE1335E03500",
             "speed": "8 Gbit",
             "state": "Online",
             "switchWwn": "20:01:00:2a:6a:98:a3:41",
             "wwnn": "5f:47:ac:c8:3c:e4:95:00",
             "wwpn": "5f:47:ac:c0:3c:e4:95:0a"
           },
           {
             "firmware": "7.04.00 (d0d5)",
             "hbaPort": 2,
             "model": "QLE2672",
             "nPortID": "0x0600a4",
             "pciSlot": 3,
             "serial": "BFE1335E03500",
             "speed": "8 Gbit",
             "state": "Online",
             "switchWwn": "20:01:00:2a:6a:9c:71:01",
             "wwnn": "5f:47:ac:c8:3c:e4:95:00",
             "wwpn": "5f:47:ac:c0:3c:e4:95:0b"
           },
           {
             "firmware": "7.04.00 (d0d5)",
             "hbaPort": 1,
             "model": "QLE2672",
             "nPortID": "0xc70044",
             "pciSlot": 2,
             "serial": "BFE1335E04029",
             "speed": "8 Gbit",
             "state": "Online",
             "switchWwn": "20:01:00:2a:6a:98:a3:41",
             "wwnn": "5f:47:ac:c8:3c:e4:95:00",
             "wwpn": "5f:47:ac:c0:3c:e4:95:08"
          },
          {
            "firmware": "7.04.00 (d0d5)",
            "hbaPort": 2,
            "model": "QLE2672",
            "nPortID": "0x060044",
            "pciSlot": 2,
            "serial": "BFE1335E04029",
            "speed": "8 Gbit",
            "state": "Online",
            "switchWwn": "20:01:00:2a:6a:9c:71:01",
            "wwnn": "5f:47:ac:c8:3c:e4:95:00",
            "wwpn": "5f:47:ac:c0:3c:e4:95:09"
          }
       ]
    }
  },
   "6": {
     "result": {
         "fibreChannelPorts": [
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 1,
           "model": "QLE2672",
           "nPortID": "0x060084",
           "pciSlot": 3,
           "serial": "BFE1335E04217",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:9c:71:01",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:02"
        },
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 2,
           "model": "QLE2672",
           "nPortID": "0xc700a4",
           "pciSlot": 3,
           "serial": "BFE1335E04217",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:98:a3:41",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:03"
        },
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 1,
           "model": "QLE2672",
           "nPortID": "0xc70064",
           "pciSlot": 2,
           "serial": "BFE1341E09515",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:98:a3:41",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:00"
        },
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 2,
           "model": "QLE2672",
           "nPortID": "0x060064",
           "pciSlot": 2,
           "serial": "BFE1341E09515",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:9c:71:01",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:01"
        }
     ]
    }
   }
  }
 }
}
----


== Neu seit Version

9.6
