---
permalink: api/reference_element_api_listvirtualvolumetasks.html 
sidebar: sidebar 
keywords: virtual,volume,hosts,host,cluster,list,listing,listvirtualvolumetasks 
summary: Sie können die ListVirtualVolumeTasks-Methode verwenden, um eine Liste der Aufgaben für virtuelle Volumes im System zu erhalten. 
---
= ListVirtualVolumeTasks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListVirtualVolumeTasks` Methode zum Abrufen einer Liste der Aufgaben für virtuelle Volumes im System.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
VirtualVolumeTaskIDs
 a| 
Eine Liste der Task-IDs für virtuelle Volumes, für die Informationen abgerufen werden sollen. Wenn Sie diesen Parameter nicht angeben, gibt die Methode Informationen zu allen Aufgaben des virtuellen Volumes zurück.
 a| 
UUID-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Aufgaben
 a| 
Eine Liste von Objekten, die die Aufgaben von virtuellen Volumes im Cluster beschreiben
 a| 
xref:reference_element_api_task_virtual_volumes.adoc[Aufgabe] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ListVirtualVolumeTasks",
    "params": {
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "tasks": [
      {
        "cancelled": false,
        "cloneVirtualVolumeID": "fafeb3a0-7dd9-4c9f-8a07-80e0bbf6f4d0",
        "operation": "clone",
        "parentMetadata": {
          "SFProfileId": "f4e5bade-15a2-4805-bf8e-52318c4ce443",
          "SFgenerationId": "0",
          "VMW_ContainerId": "abaab415-bedc-44cd-98b8-f37495884db0",
          "VMW_GosType": "windows7Server64Guest",
          "VMW_VVolName": "asdf.vmdk",
          "VMW_VVolNamespace": "/vmfs/volumes/vvol:abaab415bedc44cd-98b8f37495884db0/rfc4122.269d3378-1ca6-4175-a18f-6d4839e5c746",
          "VMW_VVolType": "Data",
          "VMW_VmID": "502e0676-e510-ccdd-394c-667f6867fcdf",
          "VMW_VvolAllocationType": "4",
          "VMW_VvolProfile": "f4e5bade-15a2-4805-bf8e-52318c4ce443:0"
        },
        "parentTotalSize": 42949672960,
        "parentUsedSize": 0,
        "status": "success",
        "virtualVolumeHostID": "564de1a4-9a99-da0f-8b7c-3a41dfd64bf1",
        "virtualVolumeTaskID": "a1b72df7-66a6-489a-86e4-538d0dbe05bf",
        "virtualvolumeID": "fafeb3a0-7dd9-4c9f-8a07-80e0bbf6f4d0"
      }
    ]
  }
}
----


== Neu seit Version

9.6
