---
permalink: api/reference_element_api_listvolumestats.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,listvolumestats,activity 
summary: 'Sie können die ListVolumeStats-Methode verwenden, um übergeordnete Aktivitätsmessungen für ein einzelnes Volume, eine Liste von Volumes oder alle Volumes \ (wenn Sie den Parameter VolumeIDs\ auslassen) zu erhalten. Die Messwerte werden durch die Erstellung des Volumens kumulativ erfasst.' 
---
= ListVolumeStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListVolumeStats` Methode zum Abrufen von allgemeinen Aktivitätsmessungen für ein einzelnes Volume, eine Liste von Volumes oder alle Volumes (wenn Sie den Parameter VolumeIDs weglassen) Die Messwerte werden durch die Erstellung des Volumens kumulativ erfasst.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
InbegriffenVirtualVolumes
 a| 
Virtuelle Volumes sind standardmäßig in der Antwort enthalten. Um virtuelle Volumes auszuschließen, setzen Sie auf false.
 a| 
boolesch
 a| 
Richtig
 a| 
Nein



 a| 
VolumeIDs
 a| 
Eine Liste von Volumes, aus denen Aktivitätsinformationen abgerufen werden können.
 a| 
Integer-Array
 a| 
Nein
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
VolumeStatistik
 a| 
Liste der Volume-Aktivitätsinformationen
 a| 
xref:reference_element_api_volumestats.adoc[VolumeStatistik] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ListVolumeStats",
    "params": {
        "volumeIDs": [1]
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 1,
        "actualIOPS": 0,
        "asyncDelay": null,
        "averageIOPSize": 0,
        "burstIOPSCredit": 30000,
        "clientQueueDepth": 0,
        "desiredMetadataHosts": null,
        "latencyUSec": 0,
        "metadataHosts": {
          "deadSecondaries": [],
          "liveSecondaries": [
            47
          ],
          "primary": 33
        },
        "nonZeroBlocks": 22080699,
        "readBytes": 657262370816,
        "readBytesLastSample": 0,
        "readLatencyUSec": 0,
        "readOps": 160464446,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "throttle": 0,
        "timestamp": "2016-03-09T19:39:15.771697Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
          1
        ],
        "volumeID": 1,
        "volumeSize": 107374182400,
        "volumeUtilization": 0,
        "writeBytes": 219117547520,
        "writeBytesLastSample": 0,
        "writeLatencyUSec": 0,
        "writeOps": 53495495,
        "writeOpsLastSample": 0,
        "zeroBlocks": 4133701
      }
    ]
  }
}
----


== Neu seit Version

9.6
