---
permalink: api/reference_element_api_listauthsessionbyclusteradmin.html 
sidebar: sidebar 
keywords: cluster admin,sessions,auth sessions,list 
summary: Sie können die Methode ListAuthSessionByClusterAdmin verwenden, um alle mit der angegebenen ClusterAdminID verknüpften auth-Sitzungen aufzulisten. Wenn die angegebene ClusterAdminID einer Benutzergruppe zugeordnet ist, werden alle auth-Sitzungen für alle Mitglieder dieser Gruppe aufgeführt. 
---
= ListAuthSessionByClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListAuthSessionsByClusterAdmin` Methode zum Auflisten aller mit dem angegebenen verknüpften auth-Sitzungen `ClusterAdminID`. Wenn der angegebene `ClusterAdminID` Karten zu einer Gruppe von Benutzern werden alle Auth-Sitzungen für alle Mitglieder dieser Gruppe aufgelistet.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Cluster-AdminID
 a| 
Eindeutige Kennung für den Cluster-Administrator
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewerte

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Sitzungen
 a| 
Liste der Sitzungsinformationen für die auth Sessions.
 a| 
link:reference_element_api_authsessioninfo.md#GUID-FF0CE38C-8F99-4F23-8A6F-F6EA4487E808["AuthSessionInfo"]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
    "method": "ListAuthSessionsByClusterAdmin",
    "clusterAdminID": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Neu seit Version

12.0
