---
permalink: api/reference_element_api_deleteauthsession.html 
sidebar: sidebar 
keywords: authentication sessions,delete 
summary: Sie können die DeleteAuthSession-Methode verwenden, um eine einzelne auth-Sitzung zu löschen. Wenn sich der aufrufende Benutzer nicht in der ClusterAdmins / Administrator-Zugriffsgruppe befindet, kann nur die Sitzung des aufrufenden Benutzers gelöscht werden. 
---
= DeleteAuthSession
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `DeleteAuthSession` Methode zum Löschen einer einzelnen Benutzerauthentifizierungssitzung. Wenn sich der aufrufende Benutzer nicht in der ClusterAdmins / Administrator-Zugriffsgruppe befindet, kann nur die Authentifizierungssitzung des aufrufenden Benutzers gelöscht werden.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Sessionid
 a| 
Eindeutige Kennung für die zu löschende auth-Sitzung.
 a| 
UUID
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewerte

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Session
 a| 
Sitzungsinformationen für die Löschsitzung.
 a| 
link:reference_element_api_authsessioninfo.md#GUID-FF0CE38C-8F99-4F23-8A6F-F6EA4487E808["AuthSessionInfo"]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
    "method": "DeleteAuthSession",
    "params": {
        "sessionID": "a862a8bb-2c5b-4774-a592-2148e2304713"
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id": 1,
    "result": {
        "session": {
            "accessGroupList": [
                "administrator"
            ],
            "authMethod": "Cluster",
            "clusterAdminIDs": [
                1
            ],
            "finalTimeout": "2020-04-09T17:51:30Z",
            "idpConfigVersion": 0,
            "lastAccessTimeout": "2020-04-06T18:21:33Z",
            "sessionCreationTime": "2020-04-06T17:51:30Z",
            "sessionID": "a862a8bb-2c5b-4774-a592-2148e2304713",
            "username": "admin"
        }
    }
}
----


== Neu seit Version

12.0
