---
permalink: api/reference_element_api_getcompletestats.html 
sidebar: sidebar 
keywords:  
summary: Das NetApp Engineering Team testet neue Funktionen mithilfe der GetCompleteStats API-Methode. Die von GetCompleteStats zurückgegebenen Daten werden nicht dokumentiert, häufig geändert und sind nicht garantiert korrekt. Sie sollten GetCompleteStats nicht zum Erfassen von Performancedaten oder für irgendeine andere Managementintegration in einen Storage-Cluster mit Element Software verwenden. 
---
= GetCompleteStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Engineering verwendet das `GetCompleteStats` API-Methode zum Testen neuer Funktionen. Die von zurückgegebenen Daten `GetCompleteStats` Wird nicht dokumentiert, häufig geändert und ist nicht garantiert korrekt. Sie sollten nicht verwenden `GetCompleteStats` Zum Erfassen von Performance-Daten oder anderer Managementintegration in einen Storage-Cluster mit Element Software.

Verwenden Sie die folgenden unterstützten API-Methoden, um statistische Informationen abzurufen:

* xref:reference_element_api_getvolumestats.adoc[GetVolumeStats]
* xref:reference_element_api_getclusterstats.adoc[GetClusterStats]
* xref:reference_element_api_getnodestats.adoc[GetNodeStats]
* xref:reference_element_api_getdrivestats.adoc[GetDriveStats]




== Neu seit Version

9.6
