---
permalink: api/reference_element_api_clusterconfig.html 
sidebar: sidebar 
keywords: objects,object,clusterConfig 
summary: Das ClusterConfig-Objekt gibt Informationen zurück, die der Node zur Kommunikation mit dem Cluster verwendet. 
---
= Cluster-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `clusterConfig` Das Objekt gibt Informationen zurück, die der Node zur Kommunikation mit dem Cluster verwendet.



== Objektmitglieder verwenden

Dieses Objekt enthält die folgenden Mitglieder:

|===
| Name | Beschreibung | Typ 


 a| 
`cipi`
 a| 
Für die Cluster-Kommunikation verwendete Netzwerkschnittstelle.
 a| 
Zeichenfolge



 a| 
`cluster`
 a| 
Eindeutiger Name des Clusters.
 a| 
Zeichenfolge



 a| 
`encryptionCapable`
 a| 
Gibt an, ob der Node die Verschlüsselung unterstützt.
 a| 
boolesch



 a| 
`ensemble`
 a| 
Nodes, die am Cluster teilnehmen.
 a| 
String-Array



 a| 
`fipsDriveConfiguration`
 a| 
Gibt an, ob der Node FIPS 140-2-2-zertifizierte Laufwerke unterstützt.
 a| 
boolesch



 a| 
`hasLocalAdmin`
 a| 
Gibt an, ob der Cluster über einen lokalen Administrator verfügt.
 a| 
boolesch



 a| 
`mipi`
 a| 
Für das Node-Management verwendete Netzwerkschnittstelle.
 a| 
Zeichenfolge



 a| 
`name`
 a| 
Eindeutige Kennung für das Cluster
 a| 
Zeichenfolge



 a| 
`nodeID`
 a| 
Eindeutige Kennung für den Knoten.
 a| 
Ganzzahl



 a| 
`pendingNodeID`
 a| 
Eindeutige Kennung für den ausstehenden Node.
 a| 
Ganzzahl



 a| 
`role`
 a| 
Gibt die Rolle des Knotens an.
 a| 
Zeichenfolge



 a| 
`sipi`
 a| 
Für den Storage verwendete Netzwerkschnittstelle.
 a| 
Zeichenfolge



 a| 
`state`
 a| 
Gibt den Status des Node an.
 a| 
Zeichenfolge



 a| 
`version`
 a| 
Zeigt die Version des Node an.
 a| 
Zeichenfolge

|===