---
permalink: api/reference_element_api_createbackuptarget.html 
sidebar: sidebar 
keywords: create,creating,backup,target,CreateBackupTarget 
summary: Mit CreateBackupTarget können Sie Backup-Zielinformationen erstellen und speichern, damit Sie bei jeder Backup-Erstellung nicht jedes Mal ein neues Backup eingeben müssen. 
---
= CreateBackupTarget
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie können `CreateBackupTarget` So erstellen und speichern Sie Backup-Zielinformationen, damit Sie sie nicht jedes Mal, wenn ein Backup erstellt wird, erneut eingeben müssen.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Name
 a| 
Name für das Backup-Ziel.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Ja.



 a| 
Merkmale
 a| 
Liste von Name-Wert-Paaren im JSON-Objektformat.
 a| 
JSON-Objekt
 a| 
Keine
 a| 
Ja (kann aber leer sein)

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
BackupTargetID
 a| 
Eindeutige Kennung, die dem neuen Backupziel zugewiesen ist.
 a| 
Ganzzahl

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "CreateBackupTarget",
   "params": {
      "name": "mytargetbackup"
   },
"id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 1,
   "result": {
      "backupTargetID": 1
   }
}
----


== Neu seit Version

9.6
