---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: Sie können die ModifyVirtualNetwork-Methode verwenden, um die Attribute eines vorhandenen virtuellen Netzwerks zu ändern. 
---
= ModifyVirtualNetwork
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ModifyVirtualNetwork` Methode zum Ändern der Attribute eines vorhandenen virtuellen Netzwerks.

Mit dieser Methode können Sie Adressblöcke hinzufügen oder entfernen, die Netmask ändern oder den Namen oder die Beschreibung des virtuellen Netzwerks ändern. Sie können damit auch Namespaces aktivieren oder deaktivieren sowie ein Gateway hinzufügen oder entfernen, wenn Namespaces auf dem virtuellen Netzwerk aktiviert sind.


NOTE: Diese Methode erfordert entweder die VirtualNetworkID oder die virtualNetworkTag als Parameter, aber nicht beides.

ACHTUNG:

Durch das Aktivieren oder Deaktivieren der Routingfähige Speicher-VLANs-Funktion für ein vorhandenes virtuelles Netzwerk wird der vom virtuellen Netzwerk abgeführte Datenverkehr durch Änderung des Namespace-Parameters unterbrochen. Am besten, wenn Sie den Namespace-Parameter während eines geplanten Wartungsfensters ändern.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===


| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
VirtualNetworkID
 a| 
Eindeutige Kennung des zu ändernden virtuellen Netzwerks Dies ist die vom Cluster zugewiesene virtuelle Netzwerk-ID.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Nein



 a| 
VirtualNetworkTag
 a| 
Das Netzwerk-Tag, das das zu ändernde virtuelle Netzwerk identifiziert.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Nein



 a| 
AdressenSperren
 a| 
Der neue Adressblock, den für dieses virtuelle Netzwerk festgelegt werden soll. Dies kann neue Adressblöcke umfassen, die dem vorhandenen Objekt hinzugefügt werden müssen oder ungenutzte Adressblöcke weglassen, die entfernt werden müssen. Alternativ können Sie die Größe vorhandener Adressblöcke erweitern oder verkleinern. Sie können nur die Größe der StartadressenSperren für ein virtuelles Netzwerkobjekt erhöhen; Sie können es nie verkleinern. Erforderliche Mitglieder für dieses Objekt:

* Start: Der Beginn des IP-Adressbereichs. (Zeichenfolge)
* Größe: Die Anzahl der IP-Adressen, die in den Block einbezogen werden sollen. (Ganze Zahl)

 a| 
JSON-Objekt
 a| 
Keine
 a| 
Nein



 a| 
Gateway
 a| 
Die IP-Adresse eines Gateways des virtuellen Netzwerks. Dieser Parameter ist nur gültig, wenn der Namespace-Parameter auf „true“ gesetzt ist.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein



 a| 
Merkmale
 a| 
Liste von Name-Wert-Paaren im JSON-Objektformat.
 a| 
JSON-Objekt
 a| 
Keine
 a| 
Nein



 a| 
Name
 a| 
Der neue Name für das virtuelle Netzwerk.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein



 a| 
Namespace
 a| 
Wenn auf „true“ gesetzt ist, wird die Funktion für routingfähige Speicher-VLANs aktiviert, indem das virtuelle Netzwerk neu erstellt und ein Namespace konfiguriert wird, der darin enthalten ist. Wenn Sie auf false setzen, deaktiviert die VRF-Funktion für das virtuelle Netzwerk. Durch die Änderung dieses Werts wird der Datenverkehr in diesem virtuellen Netzwerk unterbrochen.
 a| 
boolesch
 a| 
Keine
 a| 
Nein



 a| 
Netzmaske
 a| 
Neue Netzwerkmaske für dieses virtuelle Netzwerk.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein



 a| 
svip
 a| 
Die virtuelle Speicher-IP-Adresse für dieses virtuelle Netzwerk. Der SVIP für ein virtuelles Netzwerk kann nicht geändert werden. Sie müssen ein neues virtuelles Netzwerk erstellen, um eine andere SVIP-Adresse verwenden zu können.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode hat keine Rückgabewerte.



== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== Neu seit Version

9.6
