---
permalink: api/reference_element_api_clusterstats.html 
sidebar: sidebar 
keywords: objects,clusterStats 
summary: Das clusterStats-Objekt enthält statistische Daten für ein Cluster. Viele der im Objekt enthaltenen Statistiken zum Volume werden über alle Volumes im Cluster abgemittelt. Sie können diese Informationen über die Methode GetClusterStats für einen Cluster abrufen. 
---
= ClusterStatistik
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das clusterStats-Objekt enthält statistische Daten für ein Cluster. Viele der im Objekt enthaltenen Statistiken zum Volume werden über alle Volumes im Cluster abgemittelt. Sie können diese Informationen über die Methode GetClusterStats für einen Cluster abrufen.



== Objektmitglieder verwenden

Dieses Objekt enthält die folgenden Mitglieder:

|===
| Name | Beschreibung | Berechnung | Typ 


 a| 
AktualIOPS
 a| 
Der aktuelle tatsächliche IOPS für den gesamten Cluster in den letzten 500 Millisekunden.
 a| 
Zeitpunktgenau
 a| 
Ganzzahl



 a| 
MittelungIOPSize
 a| 
Durchschnittliche Größe in Byte der letzten I/O-Vorgänge für den Cluster in den letzten 500 Millisekunden.
 a| 
Zeitpunktgenau
 a| 
Ganzzahl



 a| 
ClientQueueDepth
 a| 
Die Anzahl der ausstehenden Lese- und Schreibvorgänge auf dem Cluster.
 a| 
K. A.
 a| 
Ganzzahl



 a| 
ClusterAuslastung
 a| 
Der Prozentsatz der maximalen IOPS des Clusters, die derzeit genutzt werden. Dies wird als clusterUtilisation = normalizedIOPS/maxIOPS (von GetClusterCapacity) berechnet.
 a| 
K. A.
 a| 
Schweben



 a| 
LaticyUSec
 a| 
Der durchschnittliche Zeitaufwand in Mikrosekunden, um den Betrieb eines Clusters in den letzten 500 Millisekunden abzuschließen.
 a| 
Zeitpunktgenau
 a| 
Ganzzahl



 a| 
NormalisiertIOPS
 a| 
Durchschnittliche IOPS-Anzahl des gesamten Clusters in den letzten 500 Millisekunden.
 a| 
Zeitpunktgenau
 a| 
Ganzzahl



 a| 
ReadBytes
 a| 
Die insgesamt gesammelten Bytes, die vom Cluster seit der Erstellung des Clusters gelesen werden.
 a| 
Monotonisch zunehmende Zahl
 a| 
Ganzzahl



 a| 
LesBytesLastBeispiel
 a| 
Die Gesamtzahl der Bytes, die im letzten Probenzeitraum vom Cluster gelesen werden.
 a| 
Zeitpunktgenau
 a| 
Ganzzahl



 a| 
ReadLatencyUSec
 a| 
Die durchschnittliche Zeit in Mikrosekunden, um Lesevorgänge in dem Cluster in den letzten 500 Millisekunden abzuschließen.
 a| 
Zeitpunktgenau
 a| 
Ganzzahl



 a| 
ReadLatencyUSecTotal
 a| 
Die Gesamtzeit, die seit der Erstellung des Clusters für Lesevorgänge benötigt wurde.
 a| 
Monotonisch zunehmende Zahl
 a| 
Ganzzahl



 a| 
ReadOps
 a| 
Die gesamten kumulativen Lesevorgänge an dem Cluster seit der Erstellung des Clusters.
 a| 
Monotonisch zunehmende Zahl
 a| 
Ganzzahl



 a| 
LesesOpsLastSample
 a| 
Die Gesamtzahl der Leseoperationen während des letzten Probenzeitraums.
 a| 
Zeitpunktgenau
 a| 
Ganzzahl



 a| 
SamplePeriodMSec
 a| 
Die Länge des Probenzeitraums in Millisekunden.
 a| 
K. A.
 a| 
Ganzzahl



 a| 
ServicesAnzahl
 a| 
Die Anzahl der auf dem Cluster ausgeführten Services. Wenn der ServicesTotal entspricht, zeigt dies an, dass gültige Statistiken von allen Knoten erfasst wurden.
 a| 
Zeitpunktgenau
 a| 
Ganzzahl



 a| 
ServicesSumme
 a| 
Die Gesamtzahl der erwarteten Services, die auf dem Cluster ausgeführt werden
 a| 
K. A.
 a| 
Ganzzahl



 a| 
Zeitstempel
 a| 
Die aktuelle Zeit im UTC+0-Format.
 a| 
K. A.
 a| 
ISO 8601-Datumszeichenfolge



 a| 
UnalignedReads
 a| 
Die gesamten, kumulativen, nicht ausgerichteten Lesevorgänge an einem Cluster seit der Erstellung des Clusters.
 a| 
Monotonisch zunehmende Zahl
 a| 
Ganzzahl



 a| 
UnalignedWrites
 a| 
Die gesamten, kumulativen, nicht ausgerichteten Schreibvorgänge an einem Cluster seit der Erstellung des Clusters
 a| 
Monotonisch zunehmende Zahl
 a| 
Ganzzahl



 a| 
WriteBytes
 a| 
Die Summe der kumulativen Bytes, die seit der Erstellung des Clusters auf den Cluster geschrieben werden.
 a| 
Monotonisch zunehmende Zahl
 a| 
Ganzzahl



 a| 
Write eBytesLastSample
 a| 
Die Gesamtzahl der Bytes, die im letzten Probenzeitraum auf das Cluster geschrieben wurden.
 a| 
Monotonisch zunehmende Zahl
 a| 
Ganzzahl



 a| 
Write LatencyUSec
 a| 
Der durchschnittliche Zeitaufwand in Mikrosekunden, um Schreibvorgänge in einem Cluster in den letzten 500 Millisekunden abzuschließen.
 a| 
Zeitpunktgenau
 a| 
Ganzzahl



 a| 
Write eLatencyUSecTotal
 a| 
Die Gesamtzeit, die seit der Erstellung des Clusters für Schreibvorgänge verwendet wurde.
 a| 
Monotonisch zunehmende Zahl
 a| 
Ganzzahl



 a| 
Schreiboperationen
 a| 
Die gesamten, kumulativen Schreibvorgänge an den Cluster seit der Erstellung des Clusters
 a| 
Monotonisch zunehmende Zahl
 a| 
Ganzzahl



 a| 
WriteOpsLastSample
 a| 
Die Gesamtzahl der Schreibvorgänge im letzten Probenzeitraum.
 a| 
Zeitpunktgenau
 a| 
Ganzzahl

|===


== Weitere Informationen

xref:reference_element_api_getclusterstats.adoc[GetClusterStats]
