---
permalink: api/reference_element_api_restartnetworking.html 
sidebar: sidebar 
keywords: node,restarting,restart,networking,network,service,services,restartnetworking 
summary: Sie können die Methode „Neustart“ verwenden, um die Netzwerkdienste auf einem Knoten neu zu starten. 
---
= Netzwerk neu starten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `RestartNetworking` Methode zum Neustart der Netzwerkdienste auf einem Knoten.

ACHTUNG:

Mit dieser Methode werden alle Netzwerkdienste auf einem Node neu gestartet, was zu einem vorübergehenden Verlust der Netzwerkverbindung führt.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Erzwingen
 a| 
Auf „true“ gesetzt, um Netzwerkdienste auf einem Knoten neu zu starten.
 a| 
boolesch
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewerte

Diese Methode hat keine Rückgabewerte.



== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "RestartNetworking",
   "params": {
              "force" : true
             },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{ "id" : 1,
  "result" : {}
}
----


== Neu seit Version

9.6
