---
permalink: api/reference_element_api_getclusterstate.html 
sidebar: sidebar 
keywords: cluster,state,getting,get,getclusterstate 
summary: Sie können die GetClusterState API-Methode verwenden, um anzugeben, ob ein Knoten Teil eines Clusters ist oder nicht. 
---
= GetClusterStatus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetClusterState` API-Methode zur Angabe, ob ein Node Teil eines Clusters ist oder nicht.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
Cluster
 a| 
Der Name des Clusters.
 a| 
Zeichenfolge



 a| 
Bundesland
 a| 
* Verfügbar: Der Node wurde nicht mit einem Cluster-Namen konfiguriert.
* Ausstehend: Node steht für ein bestimmtes benanntes Cluster aus und kann hinzugefügt werden.
* Aktiv: Node ist ein aktives Mitglied eines Clusters und kann keinem anderen Cluster hinzugefügt werden.

 a| 
Zeichenfolge

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "GetClusterState",
   "params": {},
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id" : 1,
   "result" :
      "cluster" :  "Cluster101"
      "state" : "Active"
}
----


== Neu seit Version

9.6
