---
permalink: api/reference_element_api_listprotectiondomainlevels.html 
sidebar: sidebar 
keywords: list,listing,protection,domain,levels,level,listprotectiondomainlevels 
summary: Sie können die ListProtectionDomainLevels-Methode verwenden, um die Toleranz und Ausfallsicherheit des Storage-Clusters aufzulisten. Toleranzstufen geben an, dass das Cluster im Falle eines Ausfalls weiterhin Daten lesen und schreiben kann. Stabilitätsstufen geben an, dass das Storage Cluster sich selbst bei einem oder mehreren Ausfällen automatisch heilen kann. 
---
= ListeProtectionDomainLevels
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListProtectionDomainLevels` „Method to list the Tolerance and Resiliency Levels of the Storage Cluster. Toleranzstufen geben an, dass das Cluster im Fehlerfall Daten lesen und schreiben kann. Das Stabilitätsniveau gibt an, dass das Storage Cluster sich bei einem oder mehreren Ausfällen automatisch selbst heilen kann.



== Parameter

Diese Methode hat keinen Eingabeparameter.



== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
SchutzDominLevels
 a| 
Eine Liste der verschiedenen Schutz-Domain-Level, bei der jeder die Toleranz und Resiliency-Informationen des Storage-Clusters liefert.
 a| 
xref:reference_element_api_protectiondomainlevel.adoc[SchutzDomainLevel]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ListProtectionDomainLevels",
  "params": {},
  "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
	"id": 1,
	"result": {
		"protectionDomainLevels": [
			{
				"protectionDomainType": "node",
				"resiliency": {
					"protectionSchemeResiliencies": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"singleFailureThresholdBytesForBlockData": 0,
					"sustainableFailuresForEnsemble": 1
				},
				"tolerance": {
					"protectionSchemeTolerances": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"sustainableFailuresForEnsemble": 1
				}
			},
			{
				"protectionDomainType": "chassis",
				"resiliency": {
					"protectionSchemeResiliencies": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"singleFailureThresholdBytesForBlockData": 0,
					"sustainableFailuresForEnsemble": 1
				},
				"tolerance": {
					"protectionSchemeTolerances": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"sustainableFailuresForEnsemble": 1
				}
			}
		]
	}
}
----


== Neu seit Version

11.0
