---
permalink: api/reference_element_api_setnodesupplementaltlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,set,setting,list,supplemental,setnodesupplementaltlsciphers,node 
summary: Sie können die Methode SetNodeSupplementalTlsCiphers verwenden, um die Liste der zusätzlichen TLS-Chiffren anzugeben. Sie können diesen Befehl für Management-Nodes verwenden. 
---
= SetNodeSupplementalTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `SetNodeSupplementalTlsCiphers` Methode zur Angabe der Liste der zusätzlichen TLS-Chiffren. Sie können diesen Befehl für Management-Nodes verwenden.



== Parameter


NOTE: Sie müssen diese Methode für den Management-Node anrufen. Beispiel:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
SupplementalCiphers
 a| 
Die zusätzlichen Namen der Chiffre-Suite unter Verwendung des OpenSSL-Benennungsschemas. Die Groß-/Kleinschreibung wird nicht berücksichtigt.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
MandatoryCiphers
 a| 
Liste der obligatorischen TLS-Chiffren-Suites für den Knoten. Dies sind Chiffren, die auf dem Knoten immer aktiv sind.
 a| 
Zeichenfolge



 a| 
SupplementalCiphers
 a| 
Liste der zusätzlichen TLS-Chiffren-Suites für den Knoten.
 a| 
Zeichenfolge

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "SetNodeSupplementalTlsCiphers",
   "params": {
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
   },
   "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id" : 1,
  "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----