---
permalink: api/reference_element_api_listsnapshots.html 
sidebar: sidebar 
keywords: snapshot,snapshots,list,listing,attributes,listsnapshots 
summary: Sie können ListSnapshots verwenden, um die Attribute jedes auf dem Volume erstellten Snapshots zurückzugeben. 
---
= ListenSnapshots
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie können `ListSnapshots` Um die Attribute der einzelnen Snapshots, die auf dem Volume gemacht wurden, zurückzugeben.

Informationen über Snapshots, die sich auf dem Zielcluster befinden, werden auf dem Quellcluster angezeigt, wenn diese Methode vom Quellcluster aufgerufen wird.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
VolumeID
 a| 
Ruft Snapshots für ein Volume ab. Falls keine VolumeID angegeben wird, werden alle Snapshots für alle Volumes zurückgegeben.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Nein



 a| 
Snapshot-ID
 a| 
Ruft Informationen für eine einzelne Snapshot-ID ab.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Snapshots
 a| 
Informationen zu jedem Snapshot für jedes Volume. Falls keine VolumeID angegeben wird, werden alle Snapshots für alle Volumes zurückgegeben. Snapshots, die sich in einer Gruppe befinden, werden mit einer Gruppen-ID zurückgegeben.
 a| 
xref:reference_element_api_snapshot.adoc[snapshot] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "ListSnapshots",
   "params": {
             "volumeID": "1"
       },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "snapshots": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2015-05-08T13:15:00Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2015-05-08T21:15:00Z",
          "groupID": 0,
          "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
          "name": "Hourly",
          "remoteStatuses": [
              {
                "remoteStatus": "Present",
                "volumePairUUID": "237e1cf9-fb4a-49de-a089-a6a9a1f0361e"
              }
         ],
          "snapshotID": 572,
          "snapshotUUID": "efa98e40-cb36-4c20-a090-a36c48296c14",
          "status": "done",
          "totalSize": 10000269312,
          "volumeID": 1
        }
      ]
    }
  }
----


== Neu seit Version

9.6
