---
permalink: api/reference_element_api_initializesnapmirrorrelationship.html 
sidebar: sidebar 
keywords: snapmirror,relationship,relationships,initialize,initializing,initializesnapmirrorrelationship 
summary: Die Web-UI für die Element Software verwendet die InitializeSnapMirrorRelationship-Methode, um das Ziel-Volume in einer SnapMirror Beziehung zu initialisieren, indem ein anfänglicher Basistransfer zwischen den Clustern durchgeführt wird. 
---
= InitializeSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Web-UI der Element Software verwendet das `InitializeSnapMirrorRelationship` Methode zum Initialisieren des Ziel-Volumes in einer SnapMirror Beziehung, indem ein erster Basistransfer zwischen den Clustern durchgeführt wird.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
SnapMirrorEndpointID
 a| 
Die ID des Remote-ONTAP-Systems.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.



 a| 
Zielvolumen
 a| 
Der Zieldatenträger in der SnapMirror Beziehung.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeInfo]
 a| 
Keine
 a| 
Ja.



 a| 
Maximale Transferrate
 a| 
Gibt die maximale Datentransferrate zwischen den Volumes in Kilobyte pro Sekunde an. Der Standardwert 0 ist unbegrenzt und erlaubt der SnapMirror Beziehung, die verfügbare Netzwerkbandbreite voll zu nutzen.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
SnapMirror Beziehung
 a| 
Informationen zur initialisierten SnapMirror Beziehung.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[SnapMirror Beziehung]

|===


== Neu seit Version

10.1
