---
permalink: api/reference_element_api_modifyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volume,access,group,modify,modifying,updating,changing,change,update,edit,editing,modifyvolumeaccessgroup 
summary: Sie können die Methode ModifyVolumeAccessGroup verwenden, um Initiatoren zu aktualisieren und Volumes aus einer Volume Access Group hinzuzufügen oder zu entfernen. 
---
= ModifyVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ModifyVolumeAccessGroup` Methode zum Aktualisieren von Initiatoren und Hinzufügen oder Entfernen von Volumes aus einer Volume-Zugriffsgruppe.

Wenn ein angegebener Initiator oder Volume eine Duplizierung der derzeitigen vorhanden ist, bleibt die Volume-Zugriffsgruppe ohne den ist-Wert. Wenn Sie keinen Wert für Volumes oder Initiatoren angeben, wird die aktuelle Liste der Initiatoren und Volumes nicht geändert.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===


| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
VolumeAccessGroupID
 a| 
Die ID der zu ändernden Volume-Zugriffsgruppe.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.



 a| 
Name
 a| 
Der neue Name für diese Zugriffsgruppe.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein



 a| 
Merkmale
 a| 
Liste von Name-Wert-Paaren im JSON-Objektformat.
 a| 
JSON-Objekt
 a| 
Keine
 a| 
Nein



 a| 
Initiatoren
 a| 
Liste der Initiator-IDs oder Namen (IQNs und WWPNs), die in die Volume-Zugriffsgruppe aufgenommen werden sollen Wenn Sie eine Liste der Initiatornamen übergeben, werden die Initiatoren erstellt, wenn sie noch nicht vorhanden sind. Wenn Sie eine Liste der Initiator-IDs übergeben, gibt die Methode einen Fehler aus, wenn einer der Initiatoren nicht bereits vorhanden ist. Die Weitergabe von Initiatorgruppen ist veraltet. Sie sollten Initiator-IDs verwenden, sobald möglich.
 a| 
Integer-Array (empfohlen) oder String-Array (veraltet)
 a| 
Keine
 a| 
Nein



 a| 
DeleteOrphanInitiatoren
 a| 
Gibt an, ob Objekte gelöscht werden, nachdem sie aus einer Volume-Zugriffsgruppe entfernt wurden oder nicht. Mögliche Werte:

* True: Löschen von Initiatorobjekten, nachdem sie aus einer Volume-Zugriffsgruppe entfernt wurden.
* False: Löschen Sie keine Initiator-Objekte, nachdem sie aus einer Volume-Zugriffsgruppe entfernt wurden. Dies ist die Standardeinstellung.

 a| 
boolesch
 a| 
Falsch
 a| 
Nein



 a| 
Volumes
 a| 
Liste der zu ändernden Volume-IDs
 a| 
Integer-Array
 a| 
Keine
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[VolumeAccessGroup]

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
VolumeAccessGroup
 a| 
Ein Objekt mit Informationen über die neu geänderte Volume-Zugriffsgruppe.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[VolumeAccessGroup]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "ModifyVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "name": "accessgrouptest",
      "initiators": [115,114],
      "volumes": [
         346
    ],
      "attributes": {}
   }
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": null,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [
        114,
        115
      ],
      "initiators": [
        "iqn.1998-01.com.vmware:desk1-esx1-577b283a",
        "iqn.1998-01.com.vmware:donesq-esx1-421b281b"
      ],
      "name": "accessgrouptest",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== Neu seit Version

9.6



== Weitere Informationen

* xref:reference_element_api_addinitiatorstovolumeaccessgroup.adoc[AddInitiatorsToVolumeAccessGroup]
* xref:reference_element_api_addvolumestovolumeaccessgroup.adoc[AddVolumesToVolumeAccessGroup]
* xref:reference_element_api_removeinitiatorsfromvolumeaccessgroup.adoc[RemoveInitiatorsFromVolumeAccessGroup]
* xref:reference_element_api_removevolumesfromvolumeaccessgroup.adoc[EntfernenVolumeFromVolumeAccessGroup]

