---
permalink: api/reference_element_api_modifyvolume.html 
sidebar: sidebar 
keywords: volumes,volume,modifying,modify,change,changing,edit,editing,modifyvolume,settings 
summary: Sie können die ModifyVolume-Methode verwenden, um Einstellungen auf einem vorhandenen Volume zu ändern. Sie können Änderungen an einem Volume gleichzeitig vornehmen, und sofortige Änderungen finden statt. 
---
= UmfyVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ModifyVolume` Methode zum Ändern der Einstellungen für ein vorhandenes Volume Sie können Änderungen an einem Volume gleichzeitig vornehmen, und sofortige Änderungen finden statt.

Wenn Sie beim Ändern eines Volume keine QoS-Werte angeben, bleiben diese unverändert vor der Änderung. Sie können Standard-QoS-Werte für ein neu erstelltes Volume abrufen, indem Sie das ausführen `GetDefaultQoS` Methode.

Wenn Sie die Größe eines Volumes erhöhen müssen, das repliziert wird, gehen Sie folgendermaßen vor, um Replizierungsfehler zu vermeiden:

. Erhöhen Sie die Größe des Volumes mit replizierungTarget-Zugriff.
. Erhöhen Sie die Größe des Quell- oder Volume mit ReadWrite-Zugriff.


Stellen Sie sicher, dass sowohl die Ziel- als auch die Quell-Volumes dieselbe Größe haben.


NOTE: Wenn Sie den Zugriffsstatus in gesperrt oder ReplikationTarget ändern, werden alle vorhandenen iSCSI-Verbindungen beendet.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
VolumeID
 a| 
Die VolumeID des zu ändernden Volumes
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.



 a| 
Datenzugriff
 a| 
Zugriff für das Volume zulässig. Mögliche Werte:

* `readOnly`: Nur Leseoperationen sind erlaubt.
* `readWrite`: Lesen und Schreiben sind erlaubt.
* `locked`: Es sind keine Lese- oder Schreibvorgänge zulässig. Wenn nicht angegeben, ändert sich der Zugriffswert nicht.
* `replicationTarget`: Identifizieren Sie ein Volumen als Zielvolumen für eine gepaarte Menge von Volumen. Wenn das Volume nicht gekoppelt ist, ist der Zugriffsstatus gesperrt. Wenn kein Wert angegeben wird, ändert sich der Zugriffswert nicht.
* `snapMirrorTarget`: Identifizieren Sie ein Volume als Ziel-Volume für die SnapMirror Replikation.

 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein



 a| 
AccountID
 a| 
Die AccountID, der das Volumen neu zugeordnet wird. Wenn keine angegeben wird, wird der vorherige Kontoname verwendet.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Nein



 a| 
AssoziateWithQoSPolicy
 a| 
Verknüpfen Sie das Volume mit der angegebenen QoS-Richtlinie. Mögliche Werte:

* `true`: Verknüpfen Sie das Volumen mit der QoS-Richtlinie, die im Parameter QoSPolicyID angegeben ist.
* `false`: Verknüpfen Sie das Volume nicht mit der QoS-Richtlinie, die im Parameter QoSPolicyID angegeben ist. Wenn „false“, wird eine vorhandene Richtlinienzuordnung entfernt, unabhängig davon, ob Sie im Parameter QoSPolicy eine QoS-Richtlinie angeben.

 a| 
boolesch
 a| 
Keine
 a| 
Nein



 a| 
Merkmale
 a| 
Liste von Name-Wert-Paaren im JSON-Objektformat.
 a| 
JSON-Objekt
 a| 
Keine
 a| 
Nein



 a| 
CreateTime
 a| 
Eine ISO 8601-Datumszeichenfolge, die als Erstellungsdatum des neuen Volumes festgelegt werden soll. Erforderlich, wenn setCreateTime auf true gesetzt ist.
 a| 
ISO 8601-Zeichenfolge
 a| 
Keine
 a| 
Nein



 a| 
AbleSnapMirrorReplication
 a| 
Legt fest, ob das Volume für die Replizierung mit SnapMirror Endpunkten verwendet werden kann. Mögliche Werte:

* `true`
* `false`

 a| 
boolesch
 a| 
Falsch
 a| 
Nein



| FifoGröße | Gibt die maximale Anzahl von FIFO-Snapshots an, die vom Volume unterstützt werden. Beachten Sie, dass FIFO- und nicht-FIFO-Snapshots beide denselben Pool verfügbarer Snapshot-Steckplätze auf einem Volume nutzen. Verwenden Sie diese Option, um den FIFO-Snapshot-Verbrauch der verfügbaren Snapshot-Steckplätze zu begrenzen. Beachten Sie, dass Sie diesen Wert nicht so ändern können, dass er kleiner als die aktuelle FIFO-Snapshot-Anzahl ist. | Ganzzahl | Keine | Nein 


| Min50 Größe | Gibt die Anzahl der Snapshot-Steckplätze an, die nur für FIFO-Snapshots (First in First out) reserviert sind. Da FIFO- und nicht-FIFO-Snapshots sich den gleichen Pool teilen, reduziert der minFifoSize-Parameter die Gesamtzahl der möglichen Non-FIFO-Schnappschüsse um die gleiche Menge. Beachten Sie, dass Sie diesen Wert nicht ändern können, damit er mit der aktuellen Anzahl nicht-FIFO-Snapshots in Konflikt steht. | Ganzzahl | Keine | Nein 


 a| 
Modus
 a| 
Volume-Replizierungsmodus Mögliche Werte:

* `asynch`: Wartet darauf, dass das System bestätigt, dass die Daten auf der Quelle gespeichert werden, bevor sie auf das Ziel geschrieben werden.
* `sync`: Wartet nicht auf die Bestätigung der Datenübermittlung von der Quelle, um mit dem Schreiben von Daten auf das Ziel zu beginnen.

 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein



 a| 
qos
 a| 
Die neue Quality of Service-Einstellungen für dieses Volume. Wenn nicht angegeben, werden die QoS-Einstellungen nicht geändert. Mögliche Werte:

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

 a| 
xref:reference_element_api_qos.adoc[QoS]
 a| 
Keine
 a| 
Nein



 a| 
QosPolicyID
 a| 
Die ID für die Richtlinie, deren QoS-Einstellungen auf die angegebenen Volumes angewendet werden sollten. Dieser Parameter schließen sich gegenseitig mit dem qos-Parameter aus.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Nein



 a| 
SetCreateTime
 a| 
Setzen Sie auf true, um das aufgezeichnete Datum der Volume-Erstellung zu ändern.
 a| 
boolesch
 a| 
Keine
 a| 
Nein



 a| 
Summengröße
 a| 
Die neue Größe des Volumes in Byte. 1000000000 entspricht 1 GB. Die Größe wird auf den nächsten Megabyte aufgerundet. Mit diesem Parameter kann nur die Größe eines Volumes erhöht werden.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Datenmenge
 a| 
Objekt mit Informationen zum neu geänderten Volume.
 a| 
xref:reference_element_api_volume.adoc[Datenmenge]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ModifyVolume",
  "params": {
     "volumeID": 5,
     "attributes": {
        "name1": "value1",
        "name2": "value2",
        "name3": "value3"
     },
     "qos": {
        "minIOPS": 60,
        "maxIOPS": 100,
        "burstIOPS": 150,
        "burstTime": 60
     },
      "access" :"readWrite"
     },
      "totalSize": 20000000000,
     "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
      "volume": {
          "access": "readWrite",
          "accountID": 1,
          "attributes": {
              "name1": "value1",
              "name2": "value2",
              "name3": "value3"
          },
          "blockSize": 4096,
          "createTime": "2016-03-28T16:16:13Z",
          "deleteTime": "",
          "enable512e": true,
          "iqn": "iqn.2010-01.com.solidfire:jyay.1459181777648.5",
          "name": "1459181777648",
          "purgeTime": "",
          "qos": {
              "burstIOPS": 150,
              "burstTime": 60,
              "curve": {
                  "4096": 100,
                  "8192": 160,
                  "16384": 270,
                  "32768": 500,
                  "65536": 1000,
                  "131072": 1950,
                  "262144": 3900,
                  "524288": 7600,
                  "1048576": 15000
              },
              "maxIOPS": 100,
              "minIOPS": 60
          },
          "scsiEUIDeviceID": "6a79617900000005f47acc0100000000",
          "scsiNAADeviceID": "6f47acc1000000006a79617900000005",
          "sliceCount": 1,
          "status": "active",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeAccessGroups": [
              1
          ],
          "volumeID": 5,
          "volumePairs": []
      }
  }
}
----


== Neu seit Version

9.6



== Weitere Informationen

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS]
