---
permalink: api/reference_element_api_listactivenodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,active,node,nodes,listactivenodes 
summary: Sie können die Methode ListActiveNodes verwenden, um die Liste der derzeit aktiven Nodes zurückzugeben, die sich im Cluster befinden. 
---
= ListenActiveNodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListActiveNodes` Die Methode zum Zurückgeben der Liste der derzeit aktiven Nodes, die sich im Cluster befinden.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Knoten
 a| 
Liste der aktiven Nodes im Cluster.
 a| 
xref:reference_element_api_node.adoc[Knoten] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "ListActiveNodes",
   "params": {},
   "id" : 1
}
----


== Antwortbeispiel

Aufgrund der Länge dieses Antwortbeispiels wird es in einem ergänzenden Thema dokumentiert.



== Neu seit Version

9.6



== Weitere Informationen

xref:reference_element_api_response_example_listactivenodes.adoc[ListenActiveNodes]
