---
permalink: api/reference_element_api_listdrivestats.html 
sidebar: sidebar 
keywords: cluster,list,listing,drive,drives,stats,statistics,listdrivestats 
summary: Sie können die ListDriveStats-Methode verwenden, um übergeordnete Aktivitätsmessungen für mehrere Laufwerke im Cluster aufzulisten. Bei dieser Methode werden standardmäßig Statistiken für alle Laufwerke im Cluster angezeigt. Die Messungen werden durch das Hinzufügen des Laufwerks zum Cluster kumulativ durchgeführt. Einige Werte, die diese Methode zurückgibt, sind speziell für Blocklaufwerke und einige für Metadaten-Laufwerke spezifisch. 
---
= ListDriveStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListDriveStats` Methode zur Auflistung grundlegender Aktivitätsmessungen für mehrere Laufwerke im Cluster. Bei dieser Methode werden standardmäßig Statistiken für alle Laufwerke im Cluster angezeigt. Die Messungen werden durch das Hinzufügen des Laufwerks zum Cluster kumulativ durchgeführt. Einige Werte, die diese Methode zurückgibt, sind speziell für Blocklaufwerke und einige für Metadaten-Laufwerke spezifisch.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Laufwerke
 a| 
Liste der Laufwerk-IDs (DriveID), für die Laufwerksstatistiken zurückgegeben werden sollen. Wenn Sie diesen Parameter nicht angeben, werden die Messungen für alle Laufwerke zurückgegeben.
 a| 
Integer-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===


| Name | Beschreibung | Typ 


 a| 
Fahrstollen
 a| 
Liste der Informationen zur Laufwerkaktivität für jedes Laufwerk
 a| 
xref:reference_element_api_drivestats.adoc[Fahrstollen] Array erledigen



 a| 
Fehler
 a| 
Diese Liste enthält die DriveID und die zugehörige Fehlermeldung. Es ist immer vorhanden und leer, wenn keine Fehler vorhanden sind.
 a| 
JSON-Objekt-Array

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "id": 1,
  "method": "ListDriveStats",
  "params": {
    "drives":[22,23]
  }
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": [
      {
        "driveID": 22,
        "failedDieCount": 0,
        "lifeRemainingPercent": 84,
        "lifetimeReadBytes": 30171004403712,
        "lifetimeWriteBytes": 103464755527680,
        "powerOnHours": 17736,
        "readBytes": 14656542,
         "readOps": 3624,
        "reallocatedSectors": 0,
        "reserveCapacityPercent": 100,
        "timestamp": "2016-03-01T00:19:24.782735Z",
        "totalCapacity": 300069052416,
        "usedCapacity": 1783735635,
        "usedMemory": 879165440,
        "writeBytes": 2462169894,
        "writeOps": 608802
      }
    ],
    "errors": [
      {
        "driveID": 23,
        "exception": {
          "message": "xStatCheckpointDoesNotExist",
          "name": "xStatCheckpointDoesNotExist"
        }
      }
    ]
  }
}
----


== Neu seit Version

9.6



== Weitere Informationen

xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
