---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: Sie können mit der Methode ListVolumes eine Liste der Volumes abrufen, die in einem Cluster vorhanden sind. Sie können die Volumes angeben, die in der Liste zurückgegeben werden sollen, indem Sie die verfügbaren Parameter verwenden. 
---
= ListVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListVolumes` Methode zum Abrufen einer Liste der Volumes in einem Cluster. Sie können die Volumes angeben, die in der Liste zurückgegeben werden sollen, indem Sie die verfügbaren Parameter verwenden.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Konten
 a| 
Es werden nur Volumes zurückgegeben, die im Besitz der hier angegebenen Konten sind. Schließen sich gegenseitig aus dem Parameter VolumeIDs.
 a| 
Integer-Array
 a| 
Keine
 a| 
Nein



 a| 
InbegriffenVirtualVolumes
 a| 
Virtuelle Volumes sind standardmäßig in der Antwort enthalten. Um virtuelle Volumes auszuschließen, setzen Sie auf false.
 a| 
boolesch
 a| 
Richtig
 a| 
Nein



 a| 
Iserlüftet
 a| 
Gibt Volumes zurück, die gekoppelt oder nicht gekoppelt sind. Mögliche Werte:

* True: Gibt alle gepaarten Volumes zurück.
* False: Gibt alle Volumes zurück, die nicht gekoppelt sind.

 a| 
boolesch
 a| 
Keine
 a| 
Nein



 a| 
Grenze
 a| 
Hiermit können Sie die maximale Anzahl an zurückgegebenen Volume-Ergebnissen festlegen. Schließen sich gegenseitig aus dem Parameter VolumeIDs.
 a| 
Ganzzahl
 a| 
10.000
 a| 
Nein



 a| 
StartVolumeID
 a| 
Es werden nur Volumes mit einer ID zurückgegeben, die größer oder gleich diesem Wert ist. Schließen sich gegenseitig aus dem Parameter VolumeIDs.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Nein



 a| 
VolumeIDs
 a| 
Eine Liste der Volume-IDs. Wenn Sie diesen Parameter angeben, werden andere Parameter nur für diesen Volume-Satz verwendet. Beide Seiten schließen sich gegenseitig aus den Konten, startVolumeID und den Grenzparametern.
 a| 
Integer-Array
 a| 
Nein
 a| 
Nein



 a| 
VolumeName
 a| 
Es werden nur Volume-Objektinformationen zurückgegeben, die mit dem Volume-Namen übereinstimmen.
 a| 
Zeichenfolge
 a| 
Nein
 a| 
Nein



 a| 
VolumeStatus
 a| 
Es werden nur Volumes mit einem Status zurückgegeben, der dem Statuswert entspricht. Mögliche Werte:

* Wird erstellt
* Snapshots
* Aktiv
* Gelöscht

 a| 
Zeichenfolge
 a| 
Nein
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Volumes
 a| 
Liste der Volumes
 a| 
xref:reference_element_api_volume.adoc[Datenmenge] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== Neu seit Version

9.6
