---
permalink: api/reference_element_api_getremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,hosts,host,get,getting,getremotelogginghosts 
summary: Sie können die GetRemoteLoggingHosts-Methode verwenden, um die aktuelle Liste der Logserver zu erhalten. 
---
= GetRemoteLoggingHosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetRemoteLoggingHosts` Methode zum Abrufen der aktuellen Liste der Protokollserver.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Abnehmbare Hosts
 a| 
Liste der IP-Adressen und Port-Informationen zu Hosts, die für den Empfang von weitergeleiteten Protokollinformationen konfiguriert sind.
 a| 
xref:reference_element_api_loggingserver.adoc[LoggingServer] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "id": 3386609,
   "method": "GetRemoteLoggingHosts",
   "params": {}
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 3386609,
   "result": {
      "remoteHosts": [
         {
           "host": "172.16.1.20",
           "port": 10514
         },
         {
           "host": "172.16.1.25"
         }
      ]
   }
}
----


== Neu seit Version

9.6



== Weitere Informationen

xref:reference_element_api_setremotelogginghosts.adoc[SetRemoteLoggingHosts]
