---
permalink: api/reference_element_api_getqospolicy.html 
sidebar: sidebar 
keywords: qos,policy,policies,get,getting,getqospolicy 
summary: Sie können die GetQoSPolicy Methode verwenden, um Details zu einer bestimmten QoS-Richtlinie aus dem System zu erhalten. 
---
= GetQoSPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetQoSPolicy` Methode zum Abrufen von Details zu einer bestimmten QoS-Richtlinie aus dem System



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
QosPolicyID
 a| 
Die ID der abzurufenden Richtlinie.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
QosPolicy
 a| 
Details der angeforderten QoS-Richtlinie
 a| 
xref:reference_element_api_qospolicy.adoc[QoSPolicy]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
	"method": "GetQoSPolicy",
    "params": {
    	"qosPolicyID": 2
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "qosPolicy": {
      "name": "bronze",
      "qos": {
        "burstIOPS": 15002,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 15002,
        "minIOPS": 51
      },
      "qosPolicyID": 2,
      "volumeIDs": [
          2
      ]
    }
  }
}
----


== Neu seit Version

10.0
