---
permalink: api/reference_element_api_listvolumesforaccount.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,account,active,pending,deleted,listvolumesforaccount 
summary: 'Sie können die Methode ListVolumesForAccount verwenden, um aktive und \(ausstehend\) gelöschte Volumes für ein Konto aufzulisten.' 
---
= ListVolumesForAccount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListVolumesForAccount` Methode zum Auflisten aktiver und (ausstehend) gelöschter Volumes für ein Konto.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
InbegriffenVirtualVolumes
 a| 
Virtuelle Volumes sind standardmäßig in der Antwort enthalten. Um virtuelle Volumes auszuschließen, setzen Sie auf false.
 a| 
boolesch
 a| 
Richtig
 a| 
Nein



 a| 
AccountID
 a| 
Alle Volumes, die dieser Buchhaltungs-ID gehören, werden zurückgegeben.
 a| 
Ganzzahl
 a| 
Nein
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Volumes
 a| 
Liste der Volume-Informationen
 a| 
xref:reference_element_api_volume.adoc[Datenmenge] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "ListVolumesForAccount",
   "params": {
      "accountID"  : 1
   },
   "id" : 1
}
----


== Antwortbeispiel

Die Antworten für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2018-07-22T16:15:25Z",
                "deleteTime": "",
                "enable512e": false,
                "iqn": "iqn.2010-01.com.solidfire:0oto.test1.25",
                "name": "test1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "306f746f00000019f47acc0100000000",
                "scsiNAADeviceID": "6f47acc100000000306f746f00000019",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 1000341504,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 25,
                "volumePairs": []
            }
        ]
    }
}
----


== Neu seit Version

9.6
