---
permalink: api/reference_element_api_getkeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,getting information,retrieving 
summary: 'Sie können die GetKeyServerKmip-Methode verwenden, um Informationen über den angegebenen Key Management Interoperability Protocol \(KMIP\)-Schlüsselserver zurückzugeben.' 
---
= GetKeyServerkmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetKeyServerKmip` Methode zur Rückgabe von Informationen zum angegebenen KMIP-Schlüsselserver (Key Management Interoperability Protocol)



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
KeyServer-ID
 a| 
Die ID des KMIP-Schlüsselservers, über den Informationen zurückgegeben werden sollen.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
KmSchlüsselserver
 a| 
Ein Objekt, das Details zum angeforderten Schlüsselserver enthält.
 a| 
link:reference_element_api_keyserverkmip.md#["KeyServerkmip"]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "GetKeyServerKmip",
  "params": {
     "keyServerID": 15
  },
"id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":15
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== Neu seit Version

11.7
