---
permalink: api/reference_element_api_getvolumeaccessgrouplunassignments.html 
sidebar: sidebar 
keywords: volume,access,group,groups,LUN,mapping,assignment,get,getting,GetVolumeAccessGroupLunAssignments 
summary: Mit der Methode GetVolumeAccessGroupLunAssignments können Sie Details zu LUN-Zuordnungen einer bestimmten Volume Access Group abrufen. 
---
= GetVolumeAccessGroupLunAssignments
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetVolumeAccessGroupLunAssignments` Methode zum Abrufen von Details in LUN-Zuordnungen einer angegebenen Volume-Zugriffsgruppe.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
VolumeAccessGroupID
 a| 
Eine eindeutige Zugriffsgruppen-ID für Volumes, mit der Informationen zurückgegeben werden.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
VolumeAccessGroupLunAssignments
 a| 
Eine Liste aller physischen Fibre-Channel-Ports oder ein Port für einen einzelnen Node.
 a| 
JSON-Objekt

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "GetVolumeAccessGroupLunAssignments",
   "params": {
      "volumeAccessGroupID": 5
    },
  "id" : 1
   }
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id" : 1,
  "result" : {
    "volumeAccessGroupLunAssignments" : {
       "volumeAccessGroupID" : 5,
       "lunAssignments" : [
          {"volumeID" : 5, "lun" : 0},
          {"volumeID" : 6, "lun" : 1},
          {"volumeID" : 7, "lun" : 2},
          {"volumeID" : 8, "lun" : 3}
       ],
       "deletedLunAssignments" : [
           {"volumeID" : 44, "lun" : 44}
       ]
    }
  }
}
----


== Neu seit Version

9.6
