---
permalink: api/reference_element_api_gethardwareinfo.html 
sidebar: sidebar 
keywords: node,hardware,info,get,getting,gethardwareinfo 
summary: Sie können die Methode GetHardwareInfo verwenden, um Hardwareinformationen und -Status für einen einzelnen Knoten abzurufen. Hardwareinformationen umfassen im Allgemeinen Hersteller, Anbieter, Versionen, Laufwerke und andere damit verbundene Identifikationsinformationen. 
---
= GetHardwareInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetHardwareInfo` Methode zum Abrufen von Live-Hardware-Informationen und -Status für einen einzelnen Node Hardwareinformationen umfassen im Allgemeinen Hersteller, Anbieter, Versionen, Laufwerke und andere damit verbundene Identifikationsinformationen.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Erzwingen
 a| 
Setzen Sie diesen Parameter „Force“ auf „true“, um auf allen Nodes im Cluster ausgeführt zu werden.
 a| 
boolesch
 a| 
Falsch
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
HardwareInfo
 a| 
Hardwareinformationen für den Node
 a| 
xref:reference_element_api_hardwareinfo.adoc[HardwareInfo]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "GetHardwareInfo",
   "params": {
   },
"id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "hardwareInfo": {
      "bus": {
        "core_DMI:0200": {
          "description": "Motherboard",
          "physid": "0",
          "product": "0A47AA",
          "serial": "..AB123456C12354.",
          "version": "C07"
        }
      },
      "driveHardware": [
        {
          "canonicalName": "sdh",
          "connected": true,
          "dev": 2160,
          "devPath": "/dev/disk/by-path/pci-0000:41:00.0-sas-0x500056b37789abf0-lun-0",
          "driveEncryptionCapability": "fips",
          "driveType": "Block",
          "lifeRemainingPercent": 92,
          "lifetimeReadBytes": 175436696911872,
          "lifetimeWriteBytes": 81941097349120,
          "name": "scsi-SATA_INTEL_SSDSC2BB3BTWL12345686300AAA",
          "path": "/dev/sdh",
          "pathLink": "/dev/disk/by-path/pci-0000:41:00.0-sas-0x500056b37789abf0-lun-0",
          "powerOnHours": 17246,
          "product": "INTEL SSDAA2AA300A4",
          "reallocatedSectors": 0,
          "reserveCapacityPercent": 100,
          "scsiCompatId": "scsi-SATA_INTEL_SSDSC2BB3BTWL12345686300AAA",
          "scsiState": "Running",
          "securityAtMaximum": false,
          "securityEnabled": false,
          "securityFrozen": false,
          "securityLocked": false,
          "securitySupported": true,
          "serial": "AAAA33710886300AAA",
          "size": 300069052416,
          "slot": 1,
          "smartSsdWriteCapable": false,
          "uuid": "aea178b9-c336-6bab-a61d-87b615e8120c",
          "vendor": "Intel",
          "version": "D2010370"
        },
      ...
      ]
    }
  }
}
----


== Neu seit Version

9.6
