---
permalink: api/reference_element_api_listvolumeqoshistograms.html 
sidebar: sidebar 
keywords: qos,usage,volume,histogram,generate,listvolumeqoshistograms,histograms 
summary: Sie können die ListVolumeQoSHistogramme-Methode verwenden, um ein Histogramm der QoS-Nutzung von Volumes für ein oder mehrere Volumes zu erstellen. Dadurch können Sie besser verstehen, wie Volumes QoS verwenden. 
---
= ListVolumeQoSHistogramme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListVolumeQoSHistograms` Methode zum Generieren eines Histogramm der QoS-Nutzung von Volumes für ein oder mehrere Volumes Dadurch können Sie besser verstehen, wie Volumes QoS verwenden.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
VolumeIDs
 a| 
Eine optionale Liste von Volume-IDs, in der festgelegt wird, welche Volumes QoS-Histogramme generiert werden sollen.
 a| 
Integer-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
QosHistogramme
 a| 
Liste von Objekten, die die Volume-Nutzung für ein oder mehrere Volumes beschreiben
 a| 
JSON-Objekt-Array

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
	"method": "ListVolumeQoSHistograms",
		"params": {
			"volumeIDs": [1]
		},
	"id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
	"id": 1,
	"result": {
		"qosHistograms": [
		{
			"histograms": {
			"belowMinIopsPercentages": {
				"Bucket1To19": 2406,
				"Bucket20To39": 3,
				"Bucket40To59": 0,
				"Bucket60To79": 4,
				"Bucket80To100": 0
			},
				"minToMaxIopsPercentages": {
				"Bucket101Plus": 0,
				"Bucket1To19": 0,
				"Bucket20To39": 0,
				"Bucket40To59": 2,
				"Bucket60To79": 0,
				"Bucket80To100": 0
			},
				"readBlockSizes": {
				"Bucket131072Plus": 0,
				"Bucket16384To32767": 0,
				"Bucket32768To65535": 0,
				"Bucket4096To8191": 0,
				"Bucket65536To131071": 0,
				"Bucket8192To16383": 0
			},
				"targetUtilizationPercentages": {
				"Bucket0": 134943,
				"Bucket101Plus": 0,
				"Bucket1To19": 2409,
				"Bucket20To39": 4,
				"Bucket40To59": 0,
				"Bucket60To79": 2,
				"Bucket80To100": 0
			},
				"throttlePercentages": {
				"Bucket0": 137358,
				"Bucket1To19": 0,
				"Bucket20To39": 0,
				"Bucket40To59": 0,
				"Bucket60To79": 0,
				"Bucket80To100": 0
			},
				"writeBlockSizes": {
				"Bucket131072Plus": 0,
				"Bucket16384To32767": 0,
				"Bucket32768To65535": 0,
				"Bucket4096To8191": 0,
				"Bucket65536To131071": 0,
				"Bucket8192To16383": 0
			}
		},
			"timestamp": "2018-06-21T18:45:52.010844Z",
			"volumeID": 1
		}
	]
}
}
----