---
permalink: api/reference_element_api_getlicensekey.html 
sidebar: sidebar 
keywords: cluster,get,getting,license,key 
summary: Bei SolidFire-SDS-Storage-Clustern können Sie mithilfe der Methode GetLicenseKey den aktuellen Lizenzschlüssel für das Storage-Cluster abrufen. Der Lizenzschlüssel für einen Speicher-Cluster besteht aus der Bestellnummer des Clusters kombiniert mit der Seriennummer und aktiviert das Kapazitätsmodell, das Sie für Element Software erworben haben. 
---
= GetLicenseKey
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei SolidFire-SDS-Storage-Clustern können Sie den verwenden `GetLicenseKey` Methode zum Abrufen des aktuellen Lizenzschlüssels für das Storage-Cluster. Der Lizenzschlüssel für ein Storage-Cluster besteht aus der Bestellnummer des Clusters kombiniert mit der Seriennummer und aktiviert das Kapazitätsmodell, das Sie für Element Software erworben haben.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
Auftragsnummer
 a| 
Auftragsnummer des Storage Clusters.
 a| 
Zeichenfolge



 a| 
Seriennummer
 a| 
Die Seriennummer des Storage-Clusters.
 a| 
Zeichenfolge

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "GetLicenseKey",
   "params": {
     },
   "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id" : 1,
   "result" : {
      "serialNumber": "30G56E3WV",
      "orderNumber": "33601"
     }
   }
}
----


== Neu seit Version

12.2
