---
permalink: api/reference_element_api_disableclusterssh.html 
sidebar: sidebar 
keywords: SSH,disable,disabling,cluster,DisableClusterSsh 
summary: Sie können die DisableClusterSsh-Methode verwenden, um den SSH-Dienst für den gesamten Storage-Cluster zu deaktivieren. Wenn Sie dem Storage-Cluster Nodes hinzufügen, übernehmen die neuen Nodes die Cluster-weite Einstellung. 
---
= DisableClusterSsh
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `DisableClusterSsh` „Methode“ zum Deaktivieren des SSH-Service für das gesamte Storage-Cluster. Wenn Sie dem Storage-Cluster Nodes hinzufügen, übernehmen die neuen Nodes die Cluster-weite Einstellung.


NOTE: SolidFire Enterprise SDS unterstützt diese Methode nicht. Wenn Sie diese Methode auf einem SolidFire ESDS-System verwenden, gibt die Methode einen Fehler aus.



== Parameter

Diese Methode hat keinen Eingabeparameter.



== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Ergebnis
 a| 
Ein JSON-Objekt, das den Status des SSH-Service für das Storage-Cluster enthält, die verbleibende Zeit bis SSH deaktiviert ist, und den SSH-Servicestatus für jeden Node.
 a| 
JSON-Objekt

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "DisableClusterSsh",
  "params": {
      },
  "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
	"id": 1,
	"result" : {
    "enabled": true,
    "timeRemaining": "00:43:21",
    "nodes": [
    {
        "nodeID": 1,
        "enabled": true
    },
    {
        "nodeID": 2,
        "enabled": true
    },
    {
        "nodeID": 3,
        "enabled": false
    },
    {
        "nodeID": 4,
        "enabled": false
    } ]
			}
	}
----


== Neu seit Version

10.3
