---
permalink: api/reference_element_api_testconnectmvip.html 
sidebar: sidebar 
keywords: management,connection,test,testing,mvip,testconnectmvip 
summary: Sie können die Managementverbindung zum Storage-Cluster mit der TestConnectMvip Methode testen. Der Test pingt den MVIP an und führt eine einfache API-Methode zur Überprüfung der Konnektivität durch. 
---
= TestConnectMvip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `TestConnectMvip` Methode zum Testen der Managementverbindung zum Storage-Cluster. Der Test pingt den MVIP an und führt eine einfache API-Methode zur Überprüfung der Konnektivität durch.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


| mvip | Sie können diesen Wert übergeben, um die Verwaltungsverbindung eines anderen MVIP zu testen. Sie müssen diesen Wert nicht verwenden, wenn Sie die Verbindung zum Ziel-Cluster testen. | Zeichenfolge | Keine | Nein 
|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


| Details  a| 
Informationen zum Testverfahren (JSON-Objekt):

* `connected`: Gibt an, ob der Test eine Verbindung zum MVIP herstellen könnte (boolescher Wert)
* `mvip`: Die MVIP getestet gegen (String)
* `pingBytes`: Einzelheiten der Ping-Tests mit 56 Bytes und 1500 Bytes (Objekt)
+
** `56`: Ergebnisse des 56 Byte Ping Tests (JSON Objekt):
+
*** `individualResponseTimes`: Liste der Reaktionszeiten von jedem Ensemble-Knoten (String-Array)
*** `individualStatus`: Liste des Ping-Status von jedem Ensemble-Knoten (boolescher Array)
*** `responseTime`: Durchschnittliche Ping-Antwortzeit (String)
*** `successful`: Gibt an, ob der Ping-Test erfolgreich war (boolesch)


** `1500`: Ergebnisse des 1500-Byte-Ping-Tests (JSON-Objekt):
+
*** `individualResponseTimes`: Liste der Reaktionszeiten von jedem Ensemble-Knoten (String-Array)
*** `individualStatus`: Liste des Ping-Status von jedem Ensemble-Knoten (boolescher Array)
*** `responseTime`: Durchschnittliche Ping-Antwortzeit (String)
*** `successful`: Ob der Ping-Test erfolgreich war (boolesch)


** `duration`: Dauer für die Durchführung des Tests (Zeichenkette)
** `result`: Ergebnis des gesamten Tests (String)



| JSON-Objekt 
|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "TestConnectMvip",
   "params": {
       "mvip" : "172.27.62.50"
       },
    "id":1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "connected": true,
      "mvip": "172.27.62.50",
      "pingBytes": {
        "1500": {
          "individualResponseTimes": [
            "00:00:00.000250",
            "00:00:00.000206",
            "00:00:00.000200",
            "00:00:00.000199",
            "00:00:00.000199"
         ],
          "individualStatus": [
             true,
             true,
             true,
             true,
             true
         ],
         "responseTime": "00:00:00.000211",
         "successful": true
       },
       "56": {
          "individualResponseTimes": [
            "00:00:00.000217",
            "00:00:00.000122",
            "00:00:00.000117",
            "00:00:00.000119",
            "00:00:00.000121"
         ],
         "individualStatus": [
            true,
            true,
            true,
            true,
            true
         ],
         "responseTime": "00:00:00.000139",
         "successful": true
        }
      }
    },
    "duration": "00:00:00.271244",
    "result": "Passed"
  }
}
----


== Neu seit Version

9.6
