---
permalink: api/reference_element_api_getnvraminfo.html 
sidebar: sidebar 
keywords: nvram,info,get,getting,getnvraminfo 
summary: Sie können die Methode GetNvramInfo verwenden, um von jedem Knoten Informationen über die NVRAM-Karte zu erhalten. 
---
= GetNvramInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetNvramInfo` Methode zum Abrufen von Informationen von jedem Node über die NVRAM-Karte.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Erzwingen
 a| 
Der Force-Parameter muss bei dieser Methode enthalten sein, um auf allen Nodes im Cluster erfolgreich ausgeführt zu werden.
 a| 
boolesch
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
NvramInformationen
 a| 
Arrays von Ereignissen und Fehlern, die auf der NVRAM-Karte erkannt wurden.
 a| 
JSON-Objekt

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "GetNvramInfo",
  "params": {
      "force": true
	  },
  "id" : 1
}
----


== Antwortbeispiel

Aufgrund der Länge dieses Antwortbeispiels wird es in einem ergänzenden Thema dokumentiert.



== Neu seit Version

9.6



== Weitere Informationen

xref:reference_element_api_response_example_getnvraminfo.adoc[GetNvramInfo]
