---
permalink: api/reference_element_api_listactivepairedvolumes.html 
sidebar: sidebar 
keywords: active,pairs,paired,pair,volume,volumes,list,listing,listactivepairedvolumes 
summary: Sie können die Methode ListActivePairedVolumes verwenden, um alle aktiven Volumes aufzulisten, die mit einem Volume gekoppelt sind. Diese Methode gibt Informationen zu Volumes mit aktiven und ausstehenden Paarungen zurück. 
---
= ListeActivePairedVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListActivePairedVolumes` Methode zum Auflisten aller aktiven Volumes, die mit einem Volume gekoppelt sind. Diese Methode gibt Informationen zu Volumes mit aktiven und ausstehenden Paarungen zurück.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Volumes
 a| 
Volume-Informationen für die gepaarten Volumes.
 a| 
xref:reference_element_api_volumepair.adoc[Volumepaar] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "ListActivePairedVolumes",
   "params": {
      },
   "id" : 1
}
----


== Antwortbeispiel

Die Antworten für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-06-24T15:21:59Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:0oto.bk.24",
                "name": "BK",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "306f746f00000018f47acc0100000000",
                "scsiNAADeviceID": "6f47acc100000000306f746f00000018",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 10737418240,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 24,
                "volumePairs": [
                    {
                        "clusterPairID": 2,
                        "remoteReplication": {
                            "mode": "Async",
                            "pauseLimit": 3145728000,
                            "remoteServiceID": 14,
                            "resumeDetails": "",
                            "snapshotReplication": {
                                "state": "Idle",
                                "stateDetails": ""
                            },
                            "state": "Active",
                            "stateDetails": ""
                        },
                        "remoteSliceID": 8,
                        "remoteVolumeID": 8,
                        "remoteVolumeName": "PairingDoc",
                        "volumePairUUID": "229fcbf3-2d35-4625-865a-d04bb9455cef"
                    }
                ]
            }
        ]
    }
}
----


== Neu seit Version

9.6
