---
permalink: api/reference_element_api_modifyqospolicy.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,qos,policy,policies,modifyqospolicy 
summary: Sie können die ModifyQoSPolicy-Methode verwenden, um eine bestehende QoS-Richtlinie auf dem System zu ändern. 
---
= ModifyQoSPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ModifyQoSPolicy` Methode zum Ändern einer vorhandenen QoS-Richtlinie im System



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===


| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
QosPolicyID
 a| 
Die ID der Richtlinie, die geändert werden soll.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.



 a| 
Name
 a| 
Sofern angegeben, wird der Name der QoS-Richtlinie (z. B. Gold, Platin, Silber) in diesen Wert geändert.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein



 a| 
qos
 a| 
Falls angegeben, werden die QoS-Einstellungen für diese Richtlinie auf diese Einstellungen geändert. Sie können teilweise QoS-Werte liefern und nur einige der QoS-Einstellungen ändern.
 a| 
QoS-Objekt
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===


| Name | Beschreibung | Typ 


 a| 
QosPolicy
 a| 
Details der neu geänderten QoS-Richtlinie
 a| 
xref:reference_element_api_qospolicy.adoc[QoSPolicy]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "id": 1950,
  "method": "ModifyQoSPolicy",
  "params": {
    "qosPolicyID": 2,
    "qos": {
      "minIOPS": 51,
      "maxIOPS": 15002,
      "burstIOPS": 15002
    }
  }
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1950,
  "result": {
    "qosPolicy": {
      "name": "bronze",
      "qos": {
        "burstIOPS": 15002,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 15002,
        "minIOPS": 51
      },
      "qosPolicyID": 2,
      "volumeIDs": [
        2
      ]
    }
  }
}
----


== Neu seit Version

10.0
