---
permalink: api/reference_element_api_completeclusterpairing.html 
sidebar: sidebar 
keywords: CompleteClusterPairing,cluster,pair,pairing,complete,completing 
summary: Die CompleteClusterPairing-Methode ist der zweite Schritt im Cluster-Pairing-Prozess. Verwenden Sie diese Methode mit dem kodierten Schlüssel, der von der StartClusterPairing-Methode empfangen wurde, um den Cluster-Pairing-Prozess abzuschließen. 
---
= CompleteClusterPairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `CompleteClusterPairing` Die Methode ist der zweite Schritt der Cluster-Paarung. Verwenden Sie diese Methode mit dem kodierten Schlüssel, der vom empfangen wurde `StartClusterPairing` Methode zum Abschließen des Cluster-Kopplungsvorgangs.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
ClusterPairingKey
 a| 
Eine Zeichenfolge, die von zurückgegeben wird xref:reference_element_api_startclusterpairing.adoc[StartClusterPairing] API-Methode.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
ClusterPairID
 a| 
Eindeutige Kennung für das Cluster-Paar.
 a| 
Ganzzahl

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "CompleteClusterPairing",
   "params": {
        "clusterPairingKey" : "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
   },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id" : 1,
   "result" : {
       "clusterPairID" : 1
   }
}
----


== Neu seit Version

9.6



== Weitere Informationen

xref:reference_element_api_startclusterpairing.adoc[StartClusterPairing]
