---
permalink: api/reference_element_api_listvirtualvolumes.html 
sidebar: sidebar 
keywords: virtual,volume,volumes,vvol,list,listing,listvirtualvolumes 
summary: Sie können die ListVirtualVolumes-Methode verwenden, um die virtuellen Volumes anzuzeigen, die sich derzeit im System befinden. Mit dieser Methode können Sie alle virtuellen Volumes auflisten oder nur eine Teilmenge auflisten. 
---
= ListVirtualVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListVirtualVolumes` Methode zum Auflisten der virtuellen Volumes, die sich derzeit im System befinden. Mit dieser Methode können Sie alle virtuellen Volumes auflisten oder nur eine Teilmenge auflisten.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Details
 a| 
Das Niveau der Details in der Antwort. Mögliche Werte:

* Richtig: Fügen Sie weitere Details zu jedem VVol in der Antwort ein.
* Falsch: Fügen Sie die Standarddetailebene über jedes VVol in der Antwort ein.

 a| 
boolesch
 a| 
Falsch
 a| 
Nein



 a| 
Grenze
 a| 
Die maximale Anzahl der virtuellen Volumes, die aufgelistet werden sollen.
 a| 
Ganzzahl
 a| 
10.000
 a| 
Nein



 a| 
Rekursiv
 a| 
Gibt an, ob Informationen zu den Kindern jedes VVol in der Antwort enthalten sind oder nicht. Mögliche Werte:

* Wahr: Include Informationen über die Kinder jedes VVol in der Antwort.
* Falsch: Nehmen Sie keine Informationen über die Kinder jedes VVol in die Antwort auf.

 a| 
boolesch
 a| 
Falsch
 a| 
Nein



 a| 
StartVirtualVolumeID
 a| 
Die ID des virtuellen Volumes, bei dem die Liste in der Antwort gestartet werden soll.
 a| 
UUIDType
 a| 
Keine
 a| 
Nein



 a| 
VirtualVolumeIDs
 a| 
Eine Liste der virtuellen Volume-IDs, für die Informationen abgerufen werden sollen. Wenn Sie diesen Parameter nicht angeben, gibt die Methode nur Informationen zu diesen virtuellen Volumes zurück.
 a| 
VirtualVolumeID UUID-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===


| Name | Beschreibung | Typ 


 a| 
NextVirtualVolumeID
 a| 
Die ID des nächsten virtuellen Volumes in der Liste.
 a| 
UUID



 a| 
VirtuellesVolumes
 a| 
Eine Liste von Objekten, die die virtuellen Volumes beschreiben, die sich derzeit im System befinden.
 a| 
xref:reference_element_api_virtualvolume.adoc[VirtualVolume] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ListVirtualVolumes",
    "params": {
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "nextVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
    "virtualVolumes": [
      {
        "bindings": [
          177
        ],
        "children": [],
        "metadata": {
          "SFProfileId": "f4e5bade-15a2-4805-bf8e-52318c4ce443",
          "SFgenerationId": "0",
          "VMW_ContainerId": "abaab415-bedc-44cd-98b8-f37495884db0",
          "VMW_VVolName": "asdf",
          "VMW_VVolType": "Config",
          "VMW_VmID": "502e0676-e510-ccdd-394c-667f6867fcdf",
          "VMW_VvolProfile": "f4e5bade-15a2-4805-bf8e-52318c4ce443:0"
        },
        "parentVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
        "snapshotID": 0,
        "snapshotInfo": null,
        "status": "done",
        "storageContainer": {
          "accountID": 1,
          "initiatorSecret": "B5)D1y10K)8IDN58",
          "name": "test",
          "protocolEndpointType": "SCSI",
          "status": "active",
          "storageContainerID": "abaab415-bedc-44cd-98b8-f37495884db0",
          "targetSecret": "qgae@{o{~8\"2U)U^"
        },
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeType": "config",
        "volumeID": 166,
        "volumeInfo": null
      }
    ]
  }
}
----


== Neu seit Version

9.6
