---
permalink: api/reference_element_api_listidpconfigurations.html 
sidebar: sidebar 
keywords: configs configurations,idp configs,list 
summary: Mit der Methode ListIdpConfigurations können Sie Konfigurationen für IDPs von Drittanbietern auflisten. Optional können Sie entweder das enabledOnly-Flag zum Abrufen der aktuell aktivierten IdP-Konfiguration oder eine IdP-Metadaten-UUID oder einen IdP-Namen angeben, um Informationen für eine bestimmte IdP-Konfiguration abzufragen. 
---
= ListIdpConfigurations
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListIdpConfigurations` Methode zum Auflisten von Konfigurationen für IDPs von Drittanbietern. Optional können Sie entweder die angeben `enabledOnly` Flag zum Abrufen der derzeit aktivierten IdP-Konfiguration oder einer IdP-Metadaten-UUID oder IdP-Namen, um Informationen für eine bestimmte IdP-Konfiguration abzufragen.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Barbardnur
 a| 
Filtert das Ergebnis, um die aktuell aktivierte IdP-Konfiguration zurückzugeben.
 a| 
boolesch
 a| 
Keine
 a| 
Nein



 a| 
IdpKonfigurationID
 a| 
UUID für die IdP-Konfiguration eines Drittanbieters.
 a| 
UUID
 a| 
Keine
 a| 
Nein



 a| 
IdpName
 a| 
Ruft IdP-Konfigurationsinformationen für einen bestimmten IdP-Namen ab.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
IdpConfigInfos
 a| 
Informationen zu den IdP-Konfigurationen von Drittanbietern.
 a| 
link:reference_element_api_idpconfiginfo.html["IdpConfigInfo"] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ListIdpConfigurations",
  "params": {}
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "result": {
        "idpConfigInfo": {
        "enabled": true,
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n
        <EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"\r\n
        xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"\r\n
        xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"\r\n
        xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n
        ...</Organization>\r\n
        </EntityDescriptor>",
        "idpName": "https://privider.name.url.com",
        "serviceProviderCertificate": "-----BEGIN CERTIFICATE-----\n
        MI...BHi\n
        -----END CERTIFICATE-----\n",
        "spMetadataUrl": "https://10.193.100.100/auth/ui/saml2"
        }
    }
}
----


== Neu seit Version

12.0
