---
permalink: api/reference_element_api_liststoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,containers,list,listing,liststoragecontainers 
summary: Mit der ListStorageContainers-Methode können Sie Informationen zu allen virtuellen Speichercontainern abrufen, die dem System bekannt sind. 
---
= ListStorageContainer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListStorageContainers` Methode zum Abrufen von Informationen über alle dem System bekannten virtuellen Volume Storage-Container



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
SpeicherkontainerIDs
 a| 
Eine Liste der Speicher-Container-IDs, für die Informationen abgerufen werden können. Wenn Sie diesen Parameter nicht angeben, gibt die Methode Informationen zu allen Storage-Containern im System zurück.
 a| 
UUID-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Speicherkontainer
 a| 
Liste der Objekte, die Informationen zu allen Speichercontainern im System enthalten
 a| 
xref:reference_element_api_storagecontainer.adoc[Storage Container] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "ListStorageContainers",
   "params": {
      "storageContainerIDs": ["efda8307-b916-4424-979e-658a3f16894d"]
   },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 6395,
  "result": {
    "storageContainers": [
      {
        "accountID": 64,
        "initiatorSecret": "EJ:08An1MyNQmL!7",
        "name": "VvolContainer",
        "protocolEndpointType": "SCSI",
        "status": "active",
        "storageContainerID": "efda8307-b916-4424-979e-658a3f16894d",
        "targetSecret": "g38}zWBK%206jQr~",
        "virtualVolumes": []
      }
    ]
  }
}
----


== Neu seit Version

9.6
