---
permalink: api/reference_element_api_getdriveconfig.html 
sidebar: sidebar 
keywords: drive,config,configuration,get,getting,getdriveconfig 
summary: Sie können die Methode GetDriveConfig verwenden, um Laufwerksinformationen für die erwartete Anzahl von Scheiben- und Blocklaufwerken sowie die Anzahl von Schichten und Blocklaufwerken zu erhalten, die derzeit mit dem Knoten verbunden sind. 
---
= GetDriveConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetDriveConfig` Methode zum Abrufen von Laufwerksinformationen für die erwartete Anzahl von Slices und Blocklaufwerken sowie die Anzahl der Schichten und Blocklaufwerke, die derzeit mit dem Node verbunden sind.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Auffahrt Konfiguration
 a| 
Informationen zu den Laufwerken, die mit dem Node verbunden sind.
 a| 
xref:reference_element_api_drive.adoc[Laufwerk]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "GetDriveConfig",
   "params": {},
   "id" : 1
}
----


== Antwortbeispiel

Die Antworten für diese Methode sind dem folgenden Beispiel ähnlich. Aufgrund der Länge enthält die Antwort nur Informationen für ein Laufwerk eines Storage-Node.

[listing]
----
{
	"id": 1,
	"result": {
			"driveConfig": {
					"drives": [
						{
							"canonicalName": "sda",
							"connected": true,
							"dev": 2052,
							"devPath": "/dev/sdimm0p4",
							"driveType": "Slice",
							"name": "scsi-SATA_VRFSD3400GNCVMT205581853-part4",
							"path": "/dev/sda4",
							"pathLink": "/dev/sdimm0p4",
							"product": "VRFSD3400GNCVMTKS1",
							"scsiCompatId": "scsi-SATA_VRFSD3400GNCVMT205581853-part4",
							"scsiState": "Running",
							"securityAtMaximum": false,
							"securityEnabled": false,
							"securityFrozen": true,
							"securityLocked": false,
							"securitySupported": true,
							"serial": "205581853",
							"size": 299988156416,
							"slot": -1,
							"uuid": "9d4b198b-5ff9-4f7c-04fc-3bc4e2f38974",
							"vendor": "Viking",
							"version": "612ABBF0"
						}
					],
					"numBlockActual": 10,
					"numBlockExpected": 10,
					"numSliceActual": 1,
					"numSliceExpected": 1,
					"numTotalActual": 11,
					"numTotalExpected": 11
			}
	}
}
----