---
permalink: api/reference_element_api_getfeaturestatus.html 
sidebar: sidebar 
keywords: feature,status,cluster,get,getting,getfeaturestatus 
summary: Mit der Methode GetFeatureStatus können Sie den Status einer Cluster-Funktion abrufen. 
---
= GetFeatureStatus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetFeatureStatus` Methode zum Abrufen des Status einer Cluster-Funktion.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

[cols="1a,3a,1a,1a,1a"]
|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Merkmal
 a| 
Der Status einer Cluster-Funktion. Wenn kein Wert angegeben wird, gibt das System den Status aller Funktionen zurück. Mögliche Werte:

* `Vvols`: Status der VVols Cluster-Funktion abrufen.
* `SnapMirror`: Status der SnapMirror-Replikationscluster-Funktion abrufen.
* `Fips`: Status der Verschlüsselung nach FIPS 140-2 für HTTPS-Kommunikation abrufen.
* `FipsDrives`: Status der FIPS 140-2-Laufwerksverschlüsselung abrufen.
* `VolumeLoadBalanceOnActualIOPS`: Status für den Slice-Balancing auf tatsächlichen IOPS statt auf Min IOPS-Funktion abrufen. Verfügbar ab Element 12.8.

 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Funktionen
 a| 
Ein Array von Feature-Objekten, das den Funktionsnamen und seinen Status angibt. Objektmitglieder:

* Feature: (String) der Name des Features.
* Aktiviert: (boolesch) ob die Funktion aktiviert ist oder nicht.

 a| 
JSON-Objekt-Array

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "GetFeatureStatus",
    "params": {
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id": 1,
    "result": {
        "features": [
            {
                "enabled": true,
                "feature": "Vvols"
            },
            {
                "enabled": true,
                "feature": "SnapMirror"
            },
            {
                "enabled": true,
                "feature": "Fips"
            },
            {
                "enabled": true,
                "feature": "FipsDrives"
            },
            {
                "enabled": true,
                "feature": "VolumeLoadBalanceOnActualIOPS"
            }
        ]
    }
}
----


== Neu seit Version

9.6
