---
permalink: api/reference_element_api_listpendingactivenodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,pending,active,node,nodes,listpendingactivenodes 
summary: Sie können die Methode ListPendingActiveNodes verwenden, um Nodes im Cluster aufzulisten, die sich im Status PendingActive befinden, zwischen ausstehenden und aktiven Status. Knoten in diesem Status werden an das Werkseinstellungen zurückgegeben. 
---
= ListPendingActiveNodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListPendingActiveNodes` Methode zum Auflisten von Nodes im Cluster, die sich im Status „PendingActive“ befinden, zwischen dem Status „Ausstehend“ und „aktiv“. Knoten in diesem Status werden an das Werkseinstellungen zurückgegeben.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Hängende ActiveNodes
 a| 
Liste der Objekte mit Informationen zu allen PendingActive Nodes im System.
 a| 
xref:reference_element_api_pendingactivenode.adoc[HängenActiveNode] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "ListPendingActiveNodes",
   "params": {},
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  id: null,
  result: {
    pendingActiveNodes: [
    {
      activeNodeKey: "5rPHP3lTAO",
      assignedNodeID: 5,
      asyncHandle: 2,
      cip: "10.10.5.106",
      mip: "192.168.133.106",
      pendingNodeID: 1,
      platformInfo: {
        chassisType: "R620",
        cpuModel: "Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz",
        nodeMemoryGB: 72,
        nodeType: "SF3010"
      },
     sip: "10.10.5.106",
     softwareVersion: "9.0.0.1077"
    }
    ]
  }
}
----


== Neu seit Version

9.6
