---
permalink: api/reference_element_api_modifystoragecontainer.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,vvol,modify,modifying,change,changing,edit,editing 
summary: Sie können die ModifyStorageContainer-Methode verwenden, um Änderungen an einem vorhandenen virtuellen Volume-Storage-Container vorzunehmen. 
---
= ModifyStorageContainer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ModifyStorageContainer` Methode zum Ändern eines vorhandenen virtuellen Volume-Storage-Containers.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===


| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
SpeicherkontainerID
 a| 
Die eindeutige ID des zu ändernden virtuellen Volume-Speichercontainers.
 a| 
UUID
 a| 
Keine
 a| 
Ja.



 a| 
InitiatorSecret
 a| 
Der neue Schlüssel für die CHAP-Authentifizierung für den Initiator.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein



 a| 
TargetSecret
 a| 
Der neue Schlüssel zur CHAP-Authentifizierung für das Ziel.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Storage Container
 a| 
Informationen über den neu erstellten Speicher-Container.
 a| 
xref:reference_element_api_storagecontainer.adoc[Storage Container]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ModifyStorageContainer",
    "params": {
      "storageContainerID": "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1",
      "targetSecret": "O,IM;tOQdn9$JJ*8"
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "storageContainer": {
      "accountID": 8,
      "initiatorSecret": "T$|5TO>2IY5sk4@k",
      "name": "doctest1",
      "protocolEndpointType": "SCSI",
      "status": "active",
      "storageContainerID": "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1",
      "targetSecret": "O,IM;tOQdn9$JJ*8"
    }
  }
}
----


== Neu seit Version

9.6
