---
permalink: api/reference_element_api_getnodestats.html 
sidebar: sidebar 
keywords: node,get,getting,stats,getnodestats 
summary: Sie können die Methode GetNodeStats verwenden, um die allgemeinen Aktivitätsmessungen eines einzelnen Knotens abzurufen. 
---
= GetNodeStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetNodeStats` Methode zum Abrufen der allgemeinen Aktivitätsmessungen für einen einzelnen Knoten.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
NodeID
 a| 
Gibt die ID des Node an, für den Statistiken zurückgegeben werden sollen.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
KnotenStatistiken
 a| 
Informationen zu Node-Aktivitäten
 a| 
xref:reference_element_api_nodestats.adoc[KnotenStatistiken]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "GetNodeStats",
   "params": {
     "nodeID": 5
   },
   "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id" : 1,
   "result" : {
     "nodeStats": {
       "cBytesIn": 1579657943924,
       "cBytesOut": 1683056745816,
       "count": 119529,
       "cpu": 0,
       "cpuTotal": 56289,
       "mBytesIn": 475476878,
       "mBytesOut": 269270423,
       "networkUtilizationCluster": 0,
       "networkUtilizationStorage": 0,
       "nodeHeat": {
         "primaryTotalHeat": 0.00098,
         "recentPrimaryTotalHeat": 0.00099,
         "recentTotalHeat": 0.00099,
         "totalHeat": 0.00098
       },
       "readLatencyUSecTotal": 10125300382,
       "readOps": 15640075,
       "sBytesIn": 1579657943924,
       "sBytesOut": 1683056745816,
       "ssLoadHistogram": {
         "Bucket0": 4873,
         "Bucket1To19": 6301620,
         "Bucket20To39": 396452,
         "Bucket40To59": 142,
         "Bucket60To79": 0,
         "Bucket80To100": 0
       },
       "timestamp": "2024-03-04T20:13:22.105428Z",
       "usedMemory": 106335510528,
       "writeLatencyUSecTotal": 7314512535,
       "writeOps": 59154830
     }
   }
}
----


== Neu seit Version

9.6
