---
permalink: api/reference_element_api_listprotocolendpoints.html 
sidebar: sidebar 
keywords: protocol,endpoints,endpoint,list,listing,listprotocolendpoints 
summary: Mit der ListProtocolEndpoints-Methode können Sie Informationen über alle Protokollendpunkte im Cluster abrufen. Protokollendpunkte regeln den Zugriff auf die zugehörigen virtuellen Volume-Storage-Container. 
---
= ListProtocolEndpunkte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListProtocolEndpoints` Methode zum Abrufen von Informationen über alle Protokollendpunkte im Cluster Protokollendpunkte regeln den Zugriff auf die zugehörigen virtuellen Volume-Storage-Container.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Protokoll-EndpointIDs
 a| 
Eine Liste der Protokollendpunkt-IDs, für die Informationen abgerufen werden sollen. Wenn Sie diesen Parameter nicht angeben, gibt die Methode Informationen zu allen Protokollendpunkten zurück.
 a| 
ProtocolEndpointID UUID-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Protokoll-Endpunkte
 a| 
Liste der Objekte, die Informationen zu den einzelnen Protokollendpunkstellen im System enthalten.
 a| 
xref:reference_element_api_protocolendpoint.adoc[ProtocolEndpoint] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "id": 1,
  "method": "ListProtocolEndpoints",
  "params": {}
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "protocolEndpoints": [
      {
        "primaryProviderID": 1,
        "protocolEndpointID": "1387e257-d2e3-4446-be6d-39db71583e7b",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000016970687200000000",
        "secondaryProviderID": 2
      },
      {
        "primaryProviderID": 2,
        "protocolEndpointID": "1f16ed86-3f31-4c76-b004-a1251187700b",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000026970687200000000",
        "secondaryProviderID": 3
      },
      {
        "primaryProviderID": 4,
        "protocolEndpointID": "c6458dfe-9803-4350-bb4e-68a3feb7e830",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000046970687200000000",
        "secondaryProviderID": 1
      },
      {
        "primaryProviderID": 3,
        "protocolEndpointID": "f3e7911d-0e86-4776-97db-7468c272213f",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000036970687200000000",
        "secondaryProviderID": 4
      }
    ]
  }
}
----


== Neu seit Version

9.6
