---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: Sie können die StartVolumePairing-Methode verwenden, um einen kodierten Schlüssel aus einem Volume zu erstellen, das zur Kopplung mit einem anderen Volume verwendet wird. Der Schlüssel, den diese Methode erzeugt, wird in der CompleteVolumePairing-Methode verwendet, um eine Volume-Paarung zu erstellen. 
---
= StartVolumePairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `StartVolumePairing` Methode zum Erstellen eines kodierten Schlüssels aus einem Volume, das für das Pairing mit einem anderen Volume verwendet wird. Der Schlüssel, den diese Methode erstellt, wird in verwendet `CompleteVolumePairing` Methode zum Erstellen einer Volume-Kopplung.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Modus
 a| 
Der Modus des Volumens, auf dem der Kopplungsprozess gestartet werden soll. Der Modus kann nur eingestellt werden, wenn das Volume das Quellvolume ist. Mögliche Werte:

* `Async`: Die Schreibvorgänge werden anerkannt, wenn sie lokal abgeschlossen werden. Das Cluster wartet nicht, bis Schreibvorgänge zum Ziel-Cluster repliziert werden. (Standard, wenn kein Modusparameter angegeben wurde.)
* `Sync`: Quelle bestätigt Schreiben, wenn die Daten lokal und auf dem entfernten Cluster gespeichert werden.
* `SnapshotsOnly`: Nur Snapshots, die auf dem Quellcluster erstellt wurden, werden repliziert. Aktive Schreibvorgänge vom Quell-Volume werden nicht repliziert.

 a| 
Zeichenfolge
 a| 
Keine
 a| 
Nein



 a| 
VolumeID
 a| 
Die ID des Volumens, auf dem der Kopplungsprozess gestartet werden soll.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
VolumePairingKey
 a| 
Eine Zeichenkette, die vom verwendet wird xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing] API-Methode.
 a| 
Zeichenfolge

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== Neu seit Version

9.6



== Weitere Informationen

xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]
