---
permalink: api/reference_element_api_deletestoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,delete,deleting,vvol,DeleteStorageContainers 
summary: 'Mit der DeleteStorageContainermethode können bis zu 2000 Storage-Container für Virtual Volume \(VVol\) gleichzeitig aus dem System entfernt werden. Die aus Ihnen entfernt enthaltenen Storage-Container dürfen keine VVols enthalten.' 
---
= DeleteStorageContainers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `DeleteStorageContainers` Methode, um bis zu 2000 Virtual Volume (VVol) Storage-Container gleichzeitig aus dem System zu entfernen. Die aus Ihnen entfernt enthaltenen Storage-Container dürfen keine VVols enthalten.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
SpeicherkontainerIDs
 a| 
Eine Liste der IDs der zu löschenden Speichercontainer. Sie können bis zu 2000 IDs in der Liste angeben.
 a| 
UUID-Array
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewerte

Diese Methode hat keine Rückgabewerte.



== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "DeleteStorageContainers",
    "params": {
        "storageContainerIDs" : ["a9ec1138-e386-4a44-90d7-b9acbbc05176"]
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Neu seit Version

9.6
