---
permalink: api/reference_element_api_removenodesslcertificate.html 
sidebar: sidebar 
keywords: ssl,cert,certificate,remove,removing,node,management,removenodesslcertificate 
summary: Sie können die Methode RemoveNodeSSLCertificate verwenden, um das Benutzer-SSL-Zertifikat und den privaten Schlüssel für den Management-Node zu entfernen. Nachdem das Zertifikat und der private Schlüssel entfernt wurden, wird der Management-Node so konfiguriert, dass er das Standardzertifikat und den privaten Schlüssel verwendet. 
---
= RemoveNodeSSLZertifikat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `RemoveNodeSSLCertificate` Methode zum Entfernen des Benutzer-SSL-Zertifikats und des privaten Schlüssels für den Management-Node. Nachdem das Zertifikat und der private Schlüssel entfernt wurden, wird der Management-Node so konfiguriert, dass er das Standardzertifikat und den privaten Schlüssel verwendet.



== Parameter


NOTE: Sie müssen diese Methode für den Management-Node anrufen. Beispiel:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Diese Methode hat keine Eingabeparameter.



== Rückgabewerte

Diese Methode hat keine Rückgabewerte.



== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
    "method" : "RemoveNodeSSLCertificate",
    "params" : {},
    "id" : 3
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id" : 3,
    "result" : {}
}
----