---
permalink: api/reference_element_api_completevolumepairing.html 
sidebar: sidebar 
keywords: volume,pairing,CompleteVolumePairing,pair,volumes,complete,completing 
summary: Sie können CompleteVolumePairing verwenden, um die Paarung von zwei Volumen abzuschließen. 
---
= CompleteVolumePairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie können `CompleteVolumePairing` Um die Kopplung von zwei Volumes abzuschließen.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
VolumeID
 a| 
Die ID des Datenträgers, der das Volume-Paar abgeschlossen.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.



 a| 
VolumePairingKey
 a| 
Der Schlüssel wurde vom zurückgegeben xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing] API-Methode.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat keine Rückgabewerte.



== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "CompleteVolumePairing",
   "params": {
        "volumeID" : 12,
        "volumePairingKey" : "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
        },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
"id": 1,
"result": {}
}
----


== Neu seit Version

9.6



== Weitere Informationen

xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing]
