---
permalink: api/reference_element_api_listvolumestatsbyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,access,group,listvolumestatsbyvolumeaccessgroup,activity 
summary: Sie können die Methode ListVolumeStatsByVolumeAccessGroup verwenden, um die Gesamtaktivitätsmessungen für alle Volumes anzuzeigen, die zu den angegebenen Volume-Zugriffsgruppen gehören. 
---
= ListVolumeStatsByVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListVolumeStatsByVolumeAccessGroup` Methode zum Auflisten der Gesamtaktivitätsmessungen für alle Volumes, die zu den angegebenen Volume-Zugriffsgruppen gehören.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
InbegriffenVirtualVolumes
 a| 
Virtuelle Volumes sind standardmäßig in der Antwort enthalten. Um virtuelle Volumes auszuschließen, setzen Sie auf false.
 a| 
boolesch
 a| 
Richtig
 a| 
Nein



 a| 
VolumeAccessGroups
 a| 
Ein Array von VolumeAccessGroupIDs, für die Volume-Aktivität zurückgegeben wird. Wenn keine Angaben gemacht werden, werden Statistiken für alle Volume-Zugriffsgruppen zurückgegeben.
 a| 
Integer-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
VolumeStatistik
 a| 
Liste der Volume-Aktivitätsinformationen für alle Volumes in der angegebenen Volume Access Group.*Hinweis:* das volumeID-Mitglied ist für jeden Eintrag 0, da die Werte die Summe aller Volumes darstellen, die dem Konto gehören.
 a| 
xref:reference_element_api_volumestats.adoc[VolumeStatistik]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ListVolumeStatsByVolumeAccessGroup",
    "params": {"volumeAccessGroups": [1]},
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 0,
        "nonZeroBlocks": 149366393,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T21:04:10.712370Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
            1
        ],
        "volumeID": 0,
        "volumeSize": 1073741824000,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 112777607
      }
    ]
  }
}
----


== Neu seit Version

9.6
