---
permalink: api/reference_element_api_getnodesupportedtlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,ciphers,get,getting,supported,getnodesupportedtlsciphers 
summary: Sie können die GetNodeSupportedTlsCiphers-Methode auf einem einzelnen Knoten verwenden, um eine Liste der TLS-Chiffren zu erhalten, die derzeit auf diesem Knoten unterstützt werden. Sie können diese Methode auf Management- und Storage-Nodes verwenden. 
---
= GetNodeSupportedTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetNodeSupportedTlsCiphers` Methode auf einem einzelnen Knoten, um eine Liste der TLS-Chiffren zu erhalten, die derzeit auf diesem Knoten unterstützt werden. Sie können diese Methode auf Management- und Storage-Nodes verwenden.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
MandatoryCiphers
 a| 
Liste der obligatorischen TLS-Chiffren-Suites für den Knoten. Dies sind Chiffren, die auf dem Knoten immer aktiv sind.
 a| 
Zeichenfolge



 a| 
StandardSupplementalCiphers
 a| 
Liste der standardmäßigen zusätzlichen TLS-Chiffren-Suites für den Knoten. Die zusätzlichen Chiffren werden auf dieser Liste wiederhergestellt, wenn Sie die ResetNodeSupplementalTlsCiphers API-Methode ausführen.
 a| 
Zeichenfolge



 a| 
SupportErgänzungErgänzungCiphers
 a| 
Liste der verfügbaren zusätzlichen TLS-Chiffre-Suites, die Sie mit der SetNodeSupplementalTlsCiphers API-Methode konfigurieren können.
 a| 
Zeichenfolge

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "GetNodeSupportedTlsCiphers",
  "params": {},
  "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id" : 1,
  "result" : {
	"defaultSupplementalCiphers": [
		"DHE-RSA-AES128-SHA256",
		"DHE-RSA-AES128-GCM-SHA256",
		"ECDHE-RSA-AES128-SHA256",
		"ECDHE-RSA-AES128-GCM-SHA256"
	],
	"mandatoryCiphers": [
		"DHE-RSA-AES256-SHA256",
		"DHE-RSA-AES256-GCM-SHA384",
		"ECDHE-RSA-AES256-SHA384",
		"ECDHE-RSA-AES256-GCM-SHA384"
	],
	"supportedSupplementalCiphers": [
		"DHE-RSA-AES128-SHA256",
		"DHE-RSA-AES128-GCM-SHA256",
		"ECDHE-RSA-AES128-SHA256",
		"ECDHE-RSA-AES128-GCM-SHA256",
		"DHE-RSA-AES256-SHA",
		"ECDHE-RSA-AES256-SHA",
		"DHE-RSA-CAMELLIA256-SHA",
		"DHE-RSA-AES128-SHA",
		"ECDHE-RSA-AES128-SHA",
		"DHE-RSA-CAMELLIA128-SHA"
	]
}
}
----