---
permalink: api/reference_element_api_gethardwareconfig.html 
sidebar: sidebar 
keywords: node,hardware,config,configuration,get,getting,gethardwareconfig 
summary: Sie können die Methode GetHardwareConfig verwenden, um die Hardware-Konfigurationsinformationen für einen Knoten abzurufen. 
---
= VMware HardwareConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetHardwareConfig` Methode zum Abrufen der Hardware-Konfigurationsinformationen für einen Node. Diese Konfigurationsdaten sind für den internen Gebrauch bestimmt. Verwenden Sie den, um eine nützliche Live-Bestandsaufnahme der Systemhardwarekomponenten zu erhalten `GetHardwareInfo` Methode.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


| HardwareKonfig | Liste der Hardwareinformationen und aktuellen Einstellungen | JSON-Objekt 
|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "GetHardwareConfig",
   "params": {},
   "id" : 1
}
----


== Antwortbeispiel

Die Antworten für diese Methode sind dem folgenden Beispiel ähnlich.

[listing]
----
{
    "id": 1,
    "result": {
        "hardwareConfig": {
            "biosRevision": "1.0",
            "biosVendor": [
                "NetApp",
                "SolidFire"
            ],
            "biosVersion": "1.1.2",
            "blockDriveSizeBytes": 300069052416,
            "blockDrives": [
                "/dev/slot0",
                "/dev/slot1",
                "/dev/slot2",
                "/dev/slot3",
                "/dev/slot4",
                "/dev/slot5",
                "/dev/slot6",
                "/dev/slot7",
                "/dev/slot8",
                "/dev/slot9"
            ],
            "blockServiceFormat": "Standard",
            "bmcFirmwareRevision": "1.6",
            "bmcIpmiVersion": "2.0",
            "chassisType": "R620",
            "cpuCores": 6,
            "cpuCoresEnabled": 6,
            "cpuModel": "Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz",
            "cpuThreads": 12,
            "driveSizeBytesInternal": 400088457216,
            "fibreChannelFirmwareRevision": "",
            "fibreChannelModel": "",
            "fibreChannelPorts": {},
            "idracVersion": "1.06.06",
            "ignoreFirmware": [],
            "memoryGB": 72,
            "memoryMhz": 1333,
            "networkDriver": [
                "bnx2x"
            ],
            "nicPortMap": {
                "PortA": "eth2",
                "PortB": "eth3",
                "PortC": "eth0",
                "PortD": "eth1"
            },
            "nodeType": "SF3010",
            "numCpu": 2,
            "numDrives": 10,
            "numDrivesInternal": 1,
            "nvramTempMonitorEnable": false,
            "rootDrive": "/dev/sdimm0",
            "scsiBusExternalDriver": "mpt3sas",
            "scsiBusInternalDriver": "ahci",
            "sliceDriveSizeBytes": 299988156416,
            "sliceDrives": [
                "/dev/sdimm0p4"
            ],
            "slotOffset": 0,
            "solidfireDefaults": {
                "bufferCacheGB": 12,
                "configuredIops": 50000,
                "cpuDmaLatency": -1,
                "driveWriteThroughputMBPerSleep": 10,
                "maxDriveWriteThroughputMBPerSec": 175,
                "maxIncomingSliceSyncs": 10,
                "postCallbackThreadCount": 8,
                "sCacheFileCapacity": 100000000,
                "sliceFileLogFileCapacity": 5000000000
            }
        }
    }
}
----


== Neu seit Version

9.6
