---
permalink: api/reference_element_api_listevents.html 
sidebar: sidebar 
keywords: cluster,list,listing,event,events,listevents 
summary: Sie können die ListEvents-Methode verwenden, um auf dem Cluster erkannte Ereignisse aufzulisten, die von den ältesten bis hin zur neuesten sortiert sind. 
---
= ListEvents
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `ListEvents` Methode zum Auflisten von Ereignissen, die auf dem Cluster erkannt wurden, sortiert von älteste bis neueste.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
DriveID
 a| 
Gibt an, dass nur Ereignisse mit dieser Laufwerk-ID zurückgegeben werden.
 a| 
Ganzzahl
 a| 
0
 a| 
Nein



 a| 
EndEventID
 a| 
Identifiziert das Ende eines Bereichs von Ereignis-IDs, die zurückgegeben werden sollen.
 a| 
Ganzzahl
 a| 
(Unbegrenzt)
 a| 
Nein



 a| 
EndPublishTime
 a| 
Gibt an, dass nur Ereignisse, die früher als dieses Mal veröffentlicht wurden, zurückgegeben werden.
 a| 
Zeichenfolge
 a| 
0
 a| 
Nein



 a| 
EndReportTime
 a| 
Gibt an, dass nur Ereignisse, die früher als dieses Mal gemeldet wurden, zurückgegeben werden.
 a| 
Zeichenfolge
 a| 
0
 a| 
Nein



 a| 
EventType
 a| 
Gibt den Typ der zurückkehrenden Ereignisse an. Siehe xref:reference_element_api_event.adoc[Ereignis] Für mögliche Ereignistypen.
 a| 
Zeichenfolge
 a| 
0
 a| 
Nein



 a| 
Max Events
 a| 
Gibt die maximale Anzahl von Ereignissen an, die zurückgegeben werden sollen.
 a| 
Ganzzahl
 a| 
(Unbegrenzt)
 a| 
Nein



 a| 
NodeID
 a| 
Gibt an, dass nur Ereignisse mit dieser Node-ID zurückgegeben werden.
 a| 
Ganzzahl
 a| 
 a| 



 a| 
Service-ID
 a| 
Gibt an, dass nur Ereignisse mit dieser Service-ID zurückgegeben werden.
 a| 
 a| 
 a| 



 a| 
StartEventID
 a| 
Gibt den Beginn einer Reihe von Ereignissen an, die zurückgegeben werden sollen.
 a| 
Ganzzahl
 a| 
0
 a| 
Nein



 a| 
StartPublishTime
 a| 
Gibt an, dass nur nach diesem Zeitpunkt veröffentlichte Ereignisse zurückgegeben werden.
 a| 
Zeichenfolge
 a| 
0
 a| 
Nein



 a| 
StartBerichtUhrzeit
 a| 
Gibt an, dass nur nach diesem Zeitpunkt gemeldete Ereignisse zurückgegeben werden.
 a| 
Zeichenfolge
 a| 
0
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Veranstaltungen
 a| 
Liste der Ereignisse.
 a| 
xref:reference_element_api_event.adoc[Ereignis] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "ListEvents",
   "params": {
   },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id":1,
  "result":{
    "events":[
       {
          "details":
            {
              "paramGCGeneration":1431550800,
              "paramServiceID":2
            },
          "driveID":0,
          "eventID":2131,
          "eventInfoType":"gcEvent",
          "message":"GC Cluster Coordination Complete",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.361354Z",
          "timeOfReport":"2015-05-13T21:00:02.361269Z"
       },{
          "details":
               {
                  "eligibleBS":[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,25,26,27,28,29,30,31,40,41,42,43,44,45,46,47,52,53,54,55,56,57,58,59,60],
                  "generation":1431550800,
                  "participatingSS":[23,35,39,51]
               },
          "driveID":0,
          "eventID":2130,
          "eventInfoType":"gcEvent",
          "message":"GCStarted",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.354128Z",
          "timeOfReport":"2015-05-13T21:00:02.353894Z"
       },{
          "details":"",
          "driveID":0,
          "eventID":2129,
          "eventInfoType":"tSEvent",
          "message":"return code:2 t:41286 tt:41286 qcc:1 qd:1 qc:1 vrc:1 tt:2 ct:Write etl:524288",
          "nodeID":0,
          "serviceID":0,
          "severity":0,
          "timeOfPublish":"2015-05-13T20:45:21.586483Z",
          "timeOfReport":"2015-05-13T20:45:21.586311Z"
       }
     ]
   }
}
----


== Neu seit Version

9.6
