---
permalink: api/reference_element_api_setprotectiondomainlayout.html 
sidebar: sidebar 
keywords: layout,custom,protection domain,protection domains,setting protection domains 
summary: Sie können die Methode SetProtectionDomainLayout verwenden, um den Knoten benutzerdefinierten Schutzdomänen zuzuweisen. 
---
= SetProtectionDomainLayout
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `SetProtectionDomainLayout` Methode zum Zuweisen von Nodes zu benutzerdefinierten Schutz-Domänen

Für alle aktiven Nodes im Cluster müssen Informationen bereitgestellt werden. Für inaktive Nodes können keine Informationen bereitgestellt werden. Alle Nodes in einem bestimmten Chassis müssen derselben benutzerdefinierten Schutzdomäne zugewiesen werden. Derselbe SchutzDomainType muss für alle Knoten geliefert werden. ProtektionDomainTypes, die nicht kundenspezifisch sind, wie Knoten und Gehäuse, sollten nicht enthalten sein. Wenn eine dieser Optionen zur Verfügung gestellt wird, werden die benutzerdefinierten Schutzdomänen ignoriert und ein geeigneter Fehler zurückgegeben.


NOTE: Benutzerdefinierte Schutzdomänen werden in den folgenden Konfigurationen nicht unterstützt:

* Storage-Cluster mit Shared-Chassis
* Storage-Cluster mit zwei Nodes


Die Methode gibt einen Fehler aus, wenn sie in Storage-Clustern mit diesen Konfigurationen verwendet wird.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
SchutzDomainLayout
 a| 
Schutz-Domain-Informationen für jeden Node.
 a| 
JSON-Liste von link:reference_element_api_nodeprotectiondomains.html["NodeProtectionDomains"] Objekte:
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
SchutzDomainLayout
 a| 
Liste der Nodes mit jeweils zugehörigen Sicherungsdomänen.
 a| 
JSON-Liste von link:reference_element_api_nodeprotectiondomains.html["NodeProtectionDomains"] Objekte:

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "id": 1,
  "method": "SetProtectionDomainLayout",
  "params": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----

{
  "id": 1,
  "result": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR2914008D",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500EA",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500C3",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291400E6",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== Neu seit Version

12.0
