---
permalink: api/reference_element_api_getsnmpacl.html 
sidebar: sidebar 
keywords: snmp,acl,get,getting,getsnmpacl 
summary: Sie können die GetSnmpACL-Methode verwenden, um die aktuellen SNMP-Zugriffsberechtigungen auf den Cluster-Knoten zu erhalten. 
---
= GetSnmpACL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetSnmpACL` Methode zum Abrufen der aktuellen SNMP-Zugriffsberechtigungen auf den Cluster-Knoten.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
Netzwerke
 a| 
Liste der Netzwerke und welche Art von Zugriff sie auf die SNMP-Server haben, die auf den Cluster-Knoten laufen. Dieser Wert ist vorhanden, wenn SNMP v3 deaktiviert ist.
 a| 
xref:reference_element_api_network_snmp.adoc[Netzwerk] Array erledigen



 a| 
UsmUser
 a| 
Liste der Benutzer und der Zugriffstyp für die SNMP-Server, die auf den Clusterknoten ausgeführt werden. Dieser Wert ist vorhanden, wenn SNMP v3 aktiviert ist.
 a| 
xref:reference_element_api_usmuser.adoc[UsmUser] Array erledigen

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
"method": "GetSnmpACL",
"params": {},
"id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id" : 1,
  "result" : {
     "usmUsers"  : [
       {
          "name": "jdoe",
          "access": "rouser",
          "secLevel": "priv",
          "password": "mypassword",
          "passphrase": "mypassphrase",
       }
     ]
   }
}
----


== Neu seit Version

9.6
