---
permalink: api/reference_element_api_getvolumestats.html 
sidebar: sidebar 
keywords: volume,volumes,get,getting,stats,measurements,activity,getvolumestats 
summary: Mithilfe der Methode GetVolumeStats können Sie anspruchsvolle Aktivitätsmessungen für ein einzelnes Volume abrufen. Bei der Erstellung des Volumes werden die Werte kumuliert. 
---
= GetVolumeStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `GetVolumeStats` Methode, um allgemeine Aktivitätsmessungen für ein einzelnes Volume zu erhalten. Bei der Erstellung des Volumes werden die Werte kumuliert.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
VolumeID
 a| 
Gibt das Volume an, für das Statistiken gesammelt werden sollen.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
VolumeStatistik
 a| 
Informationen zur Volume-Aktivität
 a| 
xref:reference_element_api_volumestats.adoc[VolumeStatistik]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "GetVolumeStats",
   "params": {
      "volumeID": 32
   },
   "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
        {
            "accountID": 1,
            "actualIOPS": 4,
            "asyncDelay": null,
            "averageIOPSize": 5970,
            "burstIOPSCredit": 0,
            "clientQueueDepth": 0,
            "desiredMetadataHosts": null,
            "latencyUSec": 474,
            "metadataHosts": {
                "deadSecondaries": [],
                "liveSecondaries": [
                    13
                ],
                "primary": 25
            },
            "nonZeroBlocks": 34931222,
            "normalizedIOPS": 4,
            "readBytes": 1282491003392,
            "readBytesLastSample": 0,
            "readLatencyUSec": 0,
            "readLatencyUSecTotal": 4581669750,
            "readOps": 15592933,
            "readOpsLastSample": 0,
            "samplePeriodMSec": 500,
            "sliceIopsStats": {
                "largeStatistics": {
                    "averageReadIops": 17,
                    "averageTotalIops": 43,
                    "averageWriteIops": 26,
                    "nSamples": 24,
                    "peakReadIops": 19,
                    "peakTotalIops": 47,
                    "peakWriteIops": 30,
                    "sliceID": 1
                },
                "smallStatistics": {
                    "averageReadIops": 17,
                    "averageTotalIops": 42,
                    "averageWriteIops": 25,
                    "nSamples": 120,
                    "peakReadIops": 173,
                    "peakTotalIops": 249,
                    "peakWriteIops": 77,
                    "sliceID": 1
            }
        },
        "throttle": 0,
        "timestamp": "2025-02-03T21:18:38.880100Z",
        "unalignedReads": 167319,
        "unalignedWrites": 90836,
        "volumeAccessGroups": [
            1
        ],
        "volumeID": 1,
        "volumeSize": 2147483648000,
        "volumeUtilization": 0.0002666666666666667,
        "writeBytes": 1385173585408,
        "writeBytesLastSample": 12288,
        "writeLatencyUSec": 474,
        "writeLatencyUSecTotal": 11233350905,
        "writeOps": 157060458,
        "writeOpsLastSample": 2,
        "zeroBlocks": 489356778
    }
  }
}
----


== Neu seit Version

9.6
