---
permalink: api/reference_element_api_createidpconfiguration.html 
sidebar: sidebar 
keywords: IdP,idp,configuration,create,creating 
summary: 'Sie können die CreateIpdConfiguration Methode verwenden, um eine potenzielle Vertrauensbeziehung zur Authentifizierung mit einem Drittanbieter für Identitätsanbieter \ (IdP\) für das Cluster zu erstellen. Für die IdP-Kommunikation ist ein SAML-Service-Provider-Zertifikat erforderlich. Dieses Zertifikat wird bei Bedarf generiert und von diesem API-Aufruf zurückgegeben.' 
---
= CreateIdpConfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `CreateIpdConfiguration` Methode zum Erstellen einer potenziellen Vertrauensbeziehung für die Authentifizierung mit einem Drittanbieter-Identitätsanbieter (IdP) für den Cluster. Für die IdP-Kommunikation ist ein SAML-Service-Provider-Zertifikat erforderlich. Dieses Zertifikat wird bei Bedarf generiert und von diesem API-Aufruf zurückgegeben.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
IdpMetadaten
 a| 
IDP-Metadaten zu speichern.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Ja.



 a| 
IdpName
 a| 
Name, der zur Identifizierung eines IdP-Providers für die Single-Sign-On SAML 2.0 verwendet wird.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewerte

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
IdpConfigInfo
 a| 
Informationen zur IdP-Konfiguration (Identity Provider) eines Drittanbieters.
 a| 
link:reference_element_api_idpconfiginfo.md#GUID-7DAF8B5D-7803-417F-822B-F5B1A4E3EA93["IdpConfigInfo"]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
    "method": "CreateIdpConfiguration",
    "params": {
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
             <EntityDescriptor
               xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"
               xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"
               xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"
               xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"
               ...</Organization>
             </EntityDescriptor>",
        "idpName": "https://provider.name.url.com"
    },
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "result": {
        "idpConfigInfo": {
        "enabled": false,
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n
        <EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"\r\n
        xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"\r\n
        xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"\r\n
        xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n
        ... </Organization>\r\n
        </EntityDescriptor>",
        "idpName": "https://privider.name.url.com",
        "serviceProviderCertificate": "-----BEGIN CERTIFICATE-----\n
        MIID...SlBHi\n
        -----END CERTIFICATE-----\n",
        "spMetadataUrl": "https://10.193.100.100/auth/ui/saml2"
        }
    }
}
----


== Neu seit Version

12.0
