---
permalink: api/reference_element_api_addvolumestovolumeaccessgroup.html 
sidebar: sidebar 
keywords: volume,volumes,adding,add,access,group,addvolumestovolumeaccessgroup 
summary: Sie können die Methode AddVoluesToVolumeAccessGroup verwenden, um einer bestimmten Volume-Zugriffsgruppe Volumes hinzuzufügen. 
---
= AddVolumesToVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `AddVolumesToVolumeAccessGroup` Methode zum Hinzufügen von Volumes zu einer bestimmten Volume-Zugriffsgruppe.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Volumes
 a| 
Liste der Volume-IDs, die zur Volume-Zugriffsgruppe hinzugefügt werden sollen
 a| 
Integer-Array
 a| 
Keine
 a| 
Ja.



 a| 
VolumeAccessGroupID
 a| 
VolumeAccessGroupID der Volume Access Group, zu der Volumes hinzugefügt werden.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
VolumeAccessGroup
 a| 
Ein Objekt mit Informationen über die neu geänderte Volume-Zugriffsgruppe.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[VolumeAccessGroup]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "AddVolumesToVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "volumes": [1,2]
   },
   "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        346
      ],
      "initiatorIDs": [
        116,
        117
      ],
      "initiators": [
        "iqn.1993-08.org.debian:01:181324777",
        "iqn.1993-08.org.debian:01:181324888"
      ],
      "name": "northbanktest",
      "volumeAccessGroupID": 96,
      "volumes": [
        1,
        2
      ]
    }
  }
}
----


== Neu seit Version

9.6
