---
permalink: api/reference_element_api_enableclusterssh.html 
sidebar: sidebar 
keywords: SSH,enabling,enable,cluster,EnableClusterSsh 
summary: Sie können die EnableClusterSsh-Methode verwenden, um den SSH-Dienst auf allen Knoten im Storage-Cluster zu aktivieren. 
---
= EntleClusterSsh
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `EnableClusterSsh` Methode zum Aktivieren des SSH-Service auf allen Nodes im Storage-Cluster.


NOTE: SolidFire Enterprise SDS unterstützt diese Methode nicht. Wenn Sie diese Methode auf einem SolidFire ESDS-System verwenden, gibt die Methode einen Fehler aus.



== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Dauer
 a| 
Die Zeitspanne, während der der SSH-Dienst aktiviert bleibt.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
Ergebnis
 a| 
Ein JSON-Objekt, das den Status des SSH-Service für das Storage-Cluster enthält, die verbleibende Zeit bis SSH deaktiviert ist, und den SSH-Servicestatus für jeden Node.
 a| 
JSON-Objekt

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "EnableClusterSsh",
  "params": {
      "duration"  : "02:00:00.00"
  },
  "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
	"id": 1,
	"result" : {
    "enabled": true,
    "timeRemaining": "00:43:21",
    "nodes": [
    {
        "nodeID": 1,
        "enabled": true
    },
    {
        "nodeID": 2,
        "enabled": true
    },
    {
        "nodeID": 3,
        "enabled": false
    },
    {
        "nodeID": 4,
        "enabled": false
    } ]
			}
	}
----


== Neu seit Version

10.3
